### PR TITLE
fix: bunch of fixes for ScalaCli scripts import

### LINKED ISSUE #4447: Import Scala script as Scala Cli script breaks the compilation (in Metals) of the files in the same directory
### Describe the bug

https://github.com/tanishiking/metals-scalacli-issue

```
.
|-- build.sbt
|-- project
|   `-- build.properties
`-- src
    `-- main
        `-- scala
            |-- foo.sc
            `-- main.scala
```

```scala
// main.scala
package test

import cats.Id

object Cats extends App {
  val x: Id[Int] = 1
  println(x)
}

// foo.sc
val x = 1
```

- confirm `sbt compile` compiles `main.scala` without any compile errors
- open `foo.sc`
- import `foo.sc` as a scala-cli script
  - Screen Shot 2022-09-27 at 22 13 21
- we get wrong diagnostics in `main.scala`
  - Screen Shot 2022-09-27 at 22 12 20

This happens because ScalaCLI BSP "override" the mapping of source directory -> build target relation and Metals will follow the build setting that comes from ScalaCLI (which doesn't contain cats-core dependency, for example).

## How can we recover?
We can stop ScalaCli BSP server by hand

Screen Shot 2022-09-27 at 22 15 55

## Why this is the issue?
- I imagine it's hard for developers (who don't know this issue) to know it's caused by ScalaCLI BSP (when I hit this issue for the first time, it takes some time to determine it's caused by ScalaCLI BSP), how can developers know we can recover from this state by stopping ScalaCLI BSP?
- Alternatively, users can restart the Metals server
  - but, if developers decided to "automatically import scripts as ScalaCLI script", Metals will automatically import script and the wrong diagnostics arise again.
- I'm not sure many developers (including newcomers to Metals) know there's a command to start/stop ScalaCLI BSP
  - I imagine most users don't know how to stop ScalaCLI BSP, and hard to find the command.

### Expected behavior

Importing Scala script as ScalaCLI script affects only the `*.sc` files

---

FYI, it's not a problem if we create an independent directory such as `scripts` and import the script in that directory.

```
.
|-- build.sbt
|-- project
|   `-- build.properties
|-- scripts
|   `-- foo.sc
`-- src
    `-- main
        `-- scala
            `-- main.scala
```

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

0.11.8+177-ad148d54-SNAPSHOT

### Extra context or search terms

ScalaCLI, BSP

### PR DESCRIPTION
**Pull request by dos65**
Fixes #4447 - use correct semanticdb root for bsp connection.

Also don't import a full directory if it conflicts with the sourceItems from the main build tool

### CODE REVIEW

File: metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala [hunk 1]
```diff
@@ -2735,20 +2723,38 @@ class MetalsLanguageServer(
       // (require ./mill or ./.mill-version)
       buildTools.isMill
 
+  /**
+   * In case of Scala-Cli we can either import a single file or an entire directory
+   * However, we have to unsure that there is no clashes with other existing sourceItems
```
Comment (tanishiking) [inline metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala:2728]:
```suggestion
   * Returns the absolute path that ScalaCLI imports as ScalaCLI scripts.
   * By default, ScalaCLI tries to import the entire directory as ScalaCLI scripts.
   * However, we have to ensure that there are no clashes with other existing sourceItems
   * see: https://github.com/scalameta/metals/issues/4447
   *
   * @param path the absolute path of the ScalaCLI script to import
```

wdyt?

File: metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala [hunk 2]
```diff
@@ -2735,20 +2723,38 @@ class MetalsLanguageServer(
...
+   */
+  private def scalaCliDirOrFile(path: AbsolutePath): AbsolutePath = {
+    val dir = path.parent
+    val nioDir = dir.toNIO
+    val conflictsWithMainBsp =
+      buildTargets.sourceItems.filter(_.exists).exists { item =>
+        val nioItem = item.toNIO
+        nioDir.startsWith(nioItem) || nioItem.startsWith(nioDir)
```
Comment (tanishiking) [inline metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala:2736]: `nioDir.startsWith(nioItem)` why this is needed?

Does `buildTargets.sourceItems` contains directory? if yes, does that mean we can't import the entire directory for `scripts` directory? 

```
src
`-- main
    `-- scala
        |-- scripts
        |       `-- foo.sc
        `-- main.scala
```

File: metals/src/main/scala/scala/meta/internal/metals/scalacli/ScalaCli.scala [hunk 3]
```diff
@@ -231,60 +239,59 @@ class ScalaCli(
   }
 
   def loaded(path: AbsolutePath): Boolean =
-    roots0.contains(path)
-
-  def start(roots: Seq[AbsolutePath]): Future[Unit] = {
+    ifConnectedOrElse(st =>
+      st.path == path || path.toNIO.startsWith(st.path.toNIO)
+    )(false)
```
Comment (tanishiking) [inline metals/src/main/scala/scala/meta/internal/metals/scalacli/ScalaCli.scala:245]:
```suggestion
  /**
   * Start ScalaCLI BSP server and connect
   *
   * @param path a directory or a scalacli script's file path to import
   */
```

File: metals/src/main/scala/scala/meta/internal/metals/scalacli/ScalaCli.scala [hunk 4]
```diff
@@ -231,60 +239,59 @@ class ScalaCli(
...
   def stop(): CompletableFuture[Object] =
     disconnectOldBuildServer().asJavaObject
 
-  private def connectToNewBuildServer(
-      build: BuildServerConnection,
-      roots: Seq[AbsolutePath],
-  ): Future[BuildChange] = {
-    scribe.info(s"Connected to Scala CLI server v${build.version}")
-    cancelables.add(build)
-    buildServer0 = Some(build)
```
Comment (tanishiking) [inline metals/src/main/scala/scala/meta/internal/metals/scalacli/ScalaCli.scala:281]: [note]
now, we manage the connection to the build server in `ConnectionState.Connected`

File: metals/src/main/scala/scala/meta/internal/metals/scalacli/ScalaCli.scala [hunk 5]
```diff
@@ -231,60 +239,59 @@ class ScalaCli(
...
+      f.transform {
+        case Failure(ex) =>
+          scribe.error("Error starting Scala CLI", ex)
+          Success(())
+        case Success(_) =>
+          scribe.info("Scala CLI started")
+          Success(())
+      }
+    } else {
+      scribe.error(s"Multiply Scala CLI start calls. Failed for: $path")
```
Comment (tanishiking) [inline metals/src/main/scala/scala/meta/internal/metals/scalacli/ScalaCli.scala:287]: It sounds like, now we can't import multiple different scripts/directories to ScalaCLI at the same time, right?
It would be an issue if users create multiple scala cli scripts in source directories that belong to the base project.

I think it's ok for now, but it would be awesome if we can support importing multiple scripts/directories.

File: metals/src/main/scala/scala/meta/internal/metals/scalacli/ScalaCli.scala [hunk 6]
```diff
@@ -60,84 +59,93 @@ class ScalaCli(
...
-    if (buildServer0.isDefined)
-      scribe.info("disconnected: Scala CLI server")
-    buildServer0 match {
-      case None => Future.unit
-      case Some(value) =>
-        val allSources0 = allSources()
-        buildServer0 = None
-        lastImportedBuild0 = ImportedBuild.empty
-        roots0 = Nil
-        cancelables.cancel()
```
Comment (tanishiking) [inline metals/src/main/scala/scala/meta/internal/metals/scalacli/ScalaCli.scala:138]: [note]
cancellation is done in shutdown
https://github.com/scalameta/metals/blob/f48987e43d3b36c530da396ba94290d25e3332f9/metals/src/main/scala/scala/meta/internal/metals/BuildServerConnection.scala#L122

File: metals/src/main/scala/scala/meta/internal/metals/scalacli/ScalaCli.scala [hunk 7]
```diff
@@ -60,84 +59,93 @@ class ScalaCli(
...
+                  .exists(root => root == p || p.toNIO.startsWith(root.toNIO))
+              )
+              _ <- Future.sequence(
+                compilations
+                  .cascadeCompileFiles(toCompile) ::
+                  compilers().load(toCompile) ::
+                  Nil
+              )
+            } yield ()
+          } else importBuild()
```
Comment (tanishiking) [inline metals/src/main/scala/scala/meta/internal/metals/scalacli/ScalaCli.scala:135]: :+1:

**Review by tanishiking — COMMENTED** [review]
I left several comments/clarification questions, but overall it's LGTM!

File: metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala [hunk 8]
```diff
@@ -2735,20 +2723,38 @@ class MetalsLanguageServer(
...
 
+  /**
+   * In case of Scala-Cli we can either import a single file or an entire directory
+   * However, we have to unsure that there is no clashes with other existing sourceItems
+   */
+  private def scalaCliDirOrFile(path: AbsolutePath): AbsolutePath = {
+    val dir = path.parent
+    val nioDir = dir.toNIO
+    val conflictsWithMainBsp =
+      buildTargets.sourceItems.filter(_.exists).exists { item =>
```
[the remark this answers is not in the document]
Comment (tanishiking) [reply metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala:2734]: We might want to wait for indexing here https://github.com/scalameta/metals/blob/f48987e43d3b36c530da396ba94290d25e3332f9/metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala#L1121-L1122 too ? It should preents Metals to show popup for the `sc` files that belongs to some buildTargets.

File: metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala (hunk 2 above)
Comment (tgodzik) [reply metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala:2736]: I think it's fine not to allow it for now. It's a very niche scenario that someone would mix source directories and script directories.

File: metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala (hunk 8 above)
[the remark this answers is not in the document]
Comment (tgodzik) [reply metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala:2734]: Good idea, we should wait for indexing just in case.

File: metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala (hunk 2 above)
Comment (dos65) [reply metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala:2736]: @tanishiking 
yep in your case we won't import it.

I added this clause mainly for the following scenario:
```
workspace/
   - src/main/scala/...
   - my_script.sc   // <- if we import as `workspace` then scala-cli takes sources from /src/main/scala too
   - build.sbt
```

File: metals/src/main/scala/scala/meta/internal/metals/scalacli/ScalaCli.scala (hunk 5 above)
Comment (dos65) [reply metals/src/main/scala/scala/meta/internal/metals/scalacli/ScalaCli.scala:287]: > I think it's ok for now, but it would be awesome if we can support importing multiple scripts/directories.

yep, I was thinking to make support for multiply but it would take much more time.

Also, in general it's really close to multiply-bsp servers /multi-workspace support. I would implement it at first and then it will be easy to apply for this particular scala-cli case

Comment (tanishiking) [reply metals/src/main/scala/scala/meta/internal/metals/scalacli/ScalaCli.scala:287]: sounds good, hope users don't create many sc files in source directories 😄

File: tests/unit/src/main/scala/tests/BaseScalaCliSuite.scala [hunk 9]
```diff
@@ -294,4 +294,45 @@ abstract class BaseScalaCliSuite(scalaVersion: String)
 
     } yield ()
 
+  test("relative-semanticdb-root") {
```
[the remark this answers is not in the document]
Comment (dos65) [reply tests/unit/src/main/scala/tests/BaseScalaCliSuite.scala:297]: Oh, I haven't described that in pr.

There wasn't an issue for that but this test is for this issue described in comment:
https://github.com/scalameta/metals/pull/4359#pullrequestreview-1106784497

[the remark this answers is not in the document]
Comment (tgodzik) [reply tests/unit/src/main/scala/tests/BaseScalaCliSuite.scala:297]: ach! Thanks for explaning!

File: metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala (hunk 8 above)
[the remark this answers is not in the document]
Comment (dos65) [reply metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala:2737]: Thx, good suggestion. Changed!

**Review by tanishiking — APPROVED** [review]
LGTM! Thank you very much @dos65 great job :100:

**Review by tgodzik — APPROVED** [review]
LGTM!
