### PR TITLE
Fall back to mtags position occurrences

### LINKED ISSUE #961: Go to implementation does not work in presence of macro annotations
**Describe the bug**
When trying to find implementations of a trait that has macro annotations, Metals won't return any result.

Removing the macro annotation fixes the issue.

**To Reproduce**

Given a sealed family such as:

```scala
sealed trait MyError
object MyError {
  case object Error1 extends MyError
  case object Error2 extends MyError
}
```

trying to find the implementations of `MyError` works correctly.

Given the same family, but with a macro annotation, it does not work:

```scala
import io.circe.generic.JsonCodec

@JsonCodec sealed trait MyError
object MyError {
  case object Error1 extends MyError
  case object Error2 extends MyError
}
```

**Expected behavior**
Go to implementation works in both cases

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.7.6+71-570c5065-SNAPSHOT

**Search terms**
go to implementation, macro annotations, sealed trait, adt

### PR DESCRIPTION
**Pull request by gabro**
Fixes #961

### CODE REVIEW

File: metals/src/main/scala/scala/meta/internal/metals/DefinitionProvider.scala [hunk 1]
```diff
@@ -88,10 +88,20 @@ final class DefinitionProvider(
...
+      occurrence <- snapshot.occurrences
+        .find(
+          _.encloses(queryPosition, includeLastCharacter)
+        )
+        .orElse(
+          Mtags
+            .allToplevels(source.toInput)
+            .occurrences
+            .find(
+              _.encloses(queryPosition, includeLastCharacter)
```
Comment (olafurpg) [inline metals/src/main/scala/scala/meta/internal/metals/DefinitionProvider.scala]: This position doesn’t need to be from edit distance since we parse top levels from the latest text contents of the file.

**Comment by gabro** [comment]
As discussed offline, I've moved the fallback to `ImplementationProvider` only, so that it's not in the hot path for definitions.

File: metals/src/main/scala/scala/meta/internal/implementation/ImplementationProvider.scala [hunk 2]
```diff
@@ -90,7 +91,13 @@ final class ImplementationProvider(
         params,
         currentDocument
       )
-      symbolOccurrence <- positionOccurrence.occurrence.toIterable
+      symbolOccurrence <- {
```
Comment (tgodzik) [inline metals/src/main/scala/scala/meta/internal/implementation/ImplementationProvider.scala]: Later when we look for the implementation we load semanticDB for the file and find occurence in `textDocument.occurences`, can the same situation happen there? If the annotation is on the implementing class?

Comment (gabro) [reply metals/src/main/scala/scala/meta/internal/implementation/ImplementationProvider.scala]: ah, I think so. The occurrence of the sealed trait is not a "definition" anymore in that case (it's a "reference" IIRC). Can you think of a test case for stressing it?

Comment (tgodzik) [reply metals/src/main/scala/scala/meta/internal/implementation/ImplementationProvider.scala]: That could be a modified test case in this PR I think:
```
    """|/a/src/main/scala/a/Main.scala
       |package a
       |import io.circe.generic.JsonCodec
       |trait Be@@ing
       |@JsonCodec sealed trait <<Animal>> extends Being
       |object Animal {
       |  case object <<Dog>> extends Animal
       |  case object <<Cat>> extends Animal
       |}
       |""".stripMargin
```

this most likely will not find `Animal`

Comment (gabro) [reply metals/src/main/scala/scala/meta/internal/implementation/ImplementationProvider.scala]: you're right, I've added the (now failed) test, so that we can work on this tomorrow.

Comment (gabro) [reply metals/src/main/scala/scala/meta/internal/implementation/ImplementationProvider.scala]: ok, I've pushed a fix for that case too. There's indeed a lot of repetion and I hope we can come up with a more harmonized strategy for finding a definition of a symbol in the next days.

Comment (tgodzik) [reply metals/src/main/scala/scala/meta/internal/implementation/ImplementationProvider.scala]: Thanks @gabro !

File: metals/src/main/scala/scala/meta/internal/implementation/ImplementationProvider.scala [hunk 3]
```diff
@@ -90,7 +91,13 @@ final class ImplementationProvider(
...
+        lazy val mtagsOccurrence = Mtags
```
Comment (olafurpg) [inline metals/src/main/scala/scala/meta/internal/implementation/ImplementationProvider.scala]:
```suggestion
        def mtagsOccurrence = Mtags
```
