### PR TITLE
Check parent docs even when class is indexed

### LINKED ISSUE #5374: Hovering over symbol doesn't always work
### Describe the bug

Hovering over methods doesn't always bring back docs due to parent docs sometimes not being checked.

Create a file with...
```scala
  val foo = new java.util.ArrayList[Int]()
```

Hover over `ArrayList`.  It correctly returns the docs.

Now add `sort` to file...
```scala
  val foo = new java.util.ArrayList[Int]()
  foo.sort(null)
```

Hover over `sort`.  No docs.

When you hover over `ArrayList`, `DocStrings` indexes not just the constructor symbol but the entire class.  So `java.util.ArrayList#sort` is added to the cache but it's added with no docs as the docs are in the parent method `java.util.List#sort`.

Then when hovering over `sort`, the docs are returned from the cache and they are empty and the parents then aren't checked.

I was thinking of changing this but I wasn't sure about performance here.  Could the parents be checked everytime the docs are empty or is that slow and an additional cache would be needed?

### Expected behavior

Docs of parent method would be shown

### Operating system

Windows

### Editor/Extension

VS Code

### Version of Metals

v0.11.12

### Extra context or search terms

_No response_

### PR DESCRIPTION
**Pull request by Arthurm1**
Fixes #5374.  I hope - can't run the tests locally as they're flakey on Windows

### CODE REVIEW

File: mtags/src/main/scala/scala/meta/internal/metals/Docstrings.scala [hunk 1]
```diff
@@ -39,37 +39,26 @@ class Docstrings(index: GlobalSymbolIndex) {
...
-              }
-              .find(_.docstring().nonEmpty)
-              .fold {
-                result
-              } { withDocs =>
-                val updated = value.copy(docstring = withDocs.docstring())
-                cache(symbol) = updated
-                Some(updated)
-              }
+            Some(parentDocumentation(symbol, value, parents))
```
Comment (kasiaMarek) [inline mtags/src/main/scala/scala/meta/internal/metals/Docstrings.scala:61]: This looks like retry of `documentation` after index, so maybe we can add a flag and call the  `documentation` function again?

File: mtags/src/main/scala/scala/meta/internal/metals/Docstrings.scala [hunk 2]
```diff
@@ -39,37 +39,26 @@ class Docstrings(index: GlobalSymbolIndex) {
     cache.get(symbol) match {
       case Some(value) =>
         if (value == EmptySymbolDocumentation) Optional.empty()
-        else Optional.of(value)
+        else if (value.docstring.nonEmpty) Optional.of(value)
```
Comment (kasiaMarek) [inline mtags/src/main/scala/scala/meta/internal/metals/Docstrings.scala:42]: `Optional.of` suggests `value` can be a `null` but `value.docstring.nonEmpty` would fail in such case...

**Comment by Arthurm1** [comment]
@kasiaMarek I've rewritten the method to make the flow clearer and use of `Optional`.  The tests pass now as well.

**Review by kasiaMarek — APPROVED** [review]

**Comment by Arthurm1** [comment]
@kasiaMarek I don't think I have merge permissions anymore.  Can you merge please
