### PR TITLE
Fix nested function def not folding

### LINKED ISSUE #4629: Strange code folding with Scala 3
### Describe the bug

image

This picture shows how the second fold isn't on the line that starts the function definition (the `def` line) but rather the line below it. For some reason the function definition is not seen as a fold region even though the one above is.

image

This image shows the same code as before but with the second fold-region folded. As you can see the last line of the region isn't folded.

### Expected behavior

All `def`'s to start a fold region.

The final line of the all fold regions to be folded.

### Operating system

_No response_

### Editor/Extension

_No response_

### Version of Metals

v0.11.9

### Extra context or search terms

_No response_

### PR DESCRIPTION
**Pull request by MaciejG604**
Closes #4629

### CODE REVIEW

File: metals/src/main/scala/scala/meta/internal/parsing/FoldingRangeExtractor.scala [hunk 1]
```diff
@@ -20,7 +20,7 @@ final class FoldingRangeExtractor(
     foldOnlyLines: Boolean,
 ) {
   private val spanThreshold = 2
-  private val distanceToEnclosingThreshold = 3
+  private val distanceToEnclosingThreshold = 1
```
Comment (tgodzik) [inline metals/src/main/scala/scala/meta/internal/parsing/FoldingRangeExtractor.scala:23]: This might cause much smaller blocks to be show with folding. We should instead us the start and end of Defn, so if we hava a Block then check the parent and try to get the start of Defn and the next end marker. End markers are separate statements in the parser.

File: metals/src/main/scala/scala/meta/internal/parsing/FoldingRangeExtractor.scala [hunk 2]
```diff
@@ -31,10 +26,9 @@ final class FoldingRangeExtractor(
   }
 
   def extractFrom(tree: Tree, enclosing: Position): Unit = {
-    if (span(tree.pos) > spanThreshold) {
+    if (span(tree.pos) > 0) {
```
Comment (tgodzik) [inline metals/src/main/scala/scala/meta/internal/parsing/FoldingRangeExtractor.scala:29]: Let's revert the change if possible.

File: metals/src/main/scala/scala/meta/internal/parsing/FoldingRangeExtractor.scala [hunk 3]
```diff
@@ -31,10 +26,9 @@ final class FoldingRangeExtractor(
...
       val newEnclosing = tree match {
-        case Foldable((pos, adjust))
-            if span(enclosing) - span(pos) > distanceToEnclosingThreshold =>
+        case Foldable((pos, adjust)) =>
```
Comment (tgodzik) [inline metals/src/main/scala/scala/meta/internal/parsing/FoldingRangeExtractor.scala:31]: Note: It's probably not neccessary to limit the amount of foldable regions as users might want to fold different things anywa.

Btw. @MaciejG604 make sure that we don't add multiple at the same line.

File: metals/src/main/scala/scala/meta/internal/parsing/FoldingRangeExtractor.scala [hunk 4]
```diff
@@ -217,40 +272,79 @@ final class FoldingRangeExtractor(
...
+          case (n, _: Token.RightBrace) => n - 1
+          case (n, _) => n
+        }
+      LeftBracesNotClosed == 0
+    }
+
+    private def findFoldStartAtParentDefn(tree: Tree, parent: Tree): Int = {
+      val defnTokens = parent.tokens
+      val defnTokenSlice = defnTokens
+        .slice(0, defnTokens.indexOfSlice(tree.tokens))
```
Comment (tgodzik) [inline metals/src/main/scala/scala/meta/internal/parsing/FoldingRangeExtractor.scala:335]:
```suggestion
        .takeWhile(_.pos.start < tree.pos.start)
```
something along these lines maybe?

File: metals/src/main/scala/scala/meta/internal/parsing/FoldingRangeExtractor.scala [hunk 5]
```diff
@@ -148,7 +142,19 @@ final class FoldingRangeExtractor(
   }
 
   private object Foldable {
-    def unapply(tree: Tree): Option[(Position, Boolean)] =
+    def unapply(
+        tree: Tree
+    ): Option[(Position, Boolean)] = {
+      val parentDefnFoldStart = tree.parent
+        .filter(_.is[Defn])
+        .map(parentDefn => findFoldStartAtParentDefn(tree, parentDefn))
```
Comment (tgodzik) [inline metals/src/main/scala/scala/meta/internal/parsing/FoldingRangeExtractor.scala:150]: Could we handle in underneath in ` case _: Defn =>` ?

File: metals/src/main/scala/scala/meta/internal/parsing/FoldingRangeExtractor.scala [hunk 6]
```diff
@@ -159,10 +165,31 @@ final class FoldingRangeExtractor(
...
+            case (matchKw: Token.KwMatch) :: _ =>
+              // braceless
+              Some(
+                range(
+                  tree.pos.input,
+                  parentDefnFoldStart.getOrElse(matchKw.pos.end),
+                  term.pos.end,
+                ), /* adjust */ false,
+              )
+            case _ => None
```
Comment (tgodzik) [inline metals/src/main/scala/scala/meta/internal/parsing/FoldingRangeExtractor.scala:191]: Could you add an example when this is needed (a code sample)

Also this might simplified and resued for catch also:
```suggestion
      
          def matchCatchBlockStart[T: ClassTag]() = term.expr.trailingTokens
            .withFilter(_.isNot[Token.Whitespace]) match {
            case  (_: T) :: (brace: Token.LeftBrace) :: _ =>
              // with braces
              Some(
                  brace.pos.end,
                ), /* adjust */ true,
              )
            case (kw: T) :: _ =>
              // braceless
              Some(
                range(
                  kw.pos.end),
                ), /* adjust */ false,
              )
            case _ => None
```

parentDefnFoldStart should not be needed if we deduplicate correctly folding ranges

**Review by tgodzik — COMMENTED** [review]
It's starting to look much better, I left some comments about improving the code.

File: metals/src/main/scala/scala/meta/internal/parsing/FoldingRangeExtractor.scala (hunk 6 above)
Comment (MaciejG604) [reply metals/src/main/scala/scala/meta/internal/parsing/FoldingRangeExtractor.scala]:
```
??? match 
{
    case ??? => ???
    case ??? => ???
    case ??? => ???
    case ??? => ???
}

??? match {
    case ??? => ???
    case ??? => ???
    case ??? => ???
    case ??? => ???
}
```
With this function detecting the position of the left brace we support both configurations and they fold like this:
```
??? match 
{...
}

??? match { ...
}
```

File: metals/src/main/scala/scala/meta/internal/parsing/FoldingRangeExtractor.scala (hunk 2 above)
Comment (MaciejG604) [reply metals/src/main/scala/scala/meta/internal/parsing/FoldingRangeExtractor.scala:29]: This filter is now applied in `Foldable::unapply` so it's still in place. It just now gets overriden by expression being a `Defn`.

Comment (tgodzik) [reply metals/src/main/scala/scala/meta/internal/parsing/FoldingRangeExtractor.scala:29]: Do we need it here still then?

Comment (MaciejG604) [reply metals/src/main/scala/scala/meta/internal/parsing/FoldingRangeExtractor.scala:31]: True here it's not needed, but we'll still need something to stop oneline `Defn`s from producing folding regions.

File: metals/src/main/scala/scala/meta/internal/parsing/FoldingRangeExtractor.scala [hunk 7]
```diff
@@ -148,108 +142,211 @@ final class FoldingRangeExtractor(
...
+                  foldStartIndexAndAdjust._1,
+                  endPosition.start,
+                ),
+                true,
+              )
+            case None => None
+          }
 
         case template: Template =>
+          // TODO is this case needed now if we handle folding from defn case?
```
Comment (MaciejG604) [inline metals/src/main/scala/scala/meta/internal/parsing/FoldingRangeExtractor.scala:241]: Is handling of `Template`s still needed here? Do they ever appear without `Defn` in front of them?

Comment (MaciejG604) [reply metals/src/main/scala/scala/meta/internal/parsing/FoldingRangeExtractor.scala:241]: Okay but `Class`, `Object` and `Trait` are handled in `case defn: Defn` so the case for `Template` won't be needed I think

File: tests/unit/src/test/resources/foldingRange/expect/Try.scala [hunk 8]
```diff
@@ -1,41 +1,41 @@
...
         println()
         println()
         println()
-        println()
-<<region<<      case 3 =>
+        println()<<region<<
+      case 3 =>
         println()
       case _ => println()
-    }<<region<< finally >>region>>{
```
Comment (tgodzik) [inline tests/unit/src/test/resources/foldingRange/expect/Try.scala:34]: Looks like the catch region ends much further now?

File: tests/unit/src/test/resources/foldingRange/expect/Try.scala [hunk 9]
```diff
@@ -1,41 +1,41 @@
...
+    } finally >>region>>{
       ???
       ???
       ???
       ???
       ???
-    }<<region<<
+    }<<region<<<<region<<<<region<<
```
Comment (tgodzik) [inline tests/unit/src/test/resources/foldingRange/expect/Try.scala:40]: This should be 2 regions, no? One from finally and another from val.

File: tests/unit/src/test/resources/foldingRange/expect/Blocks.scala [hunk 10]
```diff
@@ -17,25 +17,25 @@ class A >>region>>{
 
   def longSingleLineBlock = { ???; ???; ???; }
 
-  def chain = >>region>>Seq(1).map>>region>>{
+  def chain =>>region>> Seq(1).map{
     x =>
-    x + 1
-     + 1
+    >>region>>x + 1
```
Comment (tgodzik) [inline tests/unit/src/test/resources/foldingRange/expect/Blocks.scala:22]: Why do we have a new region here? It's not a definition.

File: tests/unit/src/test/resources/foldingRange-scala3/expect/Givens.scala [hunk 11]
```diff
@@ -1,24 +1,24 @@
-trait Foo[A]:
-  def foo: String
+trait Foo[A]>>region>>:
```
Comment (tgodzik) [inline tests/unit/src/test/resources/foldingRange-scala3/expect/Givens.scala:1]: Isn't this too short to show, we should have 3+

File: metals/src/main/scala/scala/meta/internal/parsing/FoldingRangeExtractor.scala [hunk 12]
```diff
@@ -31,10 +30,12 @@ final class FoldingRangeExtractor(
   }
 
   def extractFrom(tree: Tree, enclosing: Position): Unit = {
-    if (span(tree.pos) > spanThreshold) {
-      val newEnclosing = tree match {
-        case Foldable((pos, adjust))
-            if span(enclosing) - span(pos) > distanceToEnclosingThreshold =>
+    // All Defn statements except one-liners must fold
+    if (
+      (tree.is[Defn] && span(tree.pos) > 0) || span(tree.pos) > spanThreshold
```
Comment (tgodzik) [inline metals/src/main/scala/scala/meta/internal/parsing/FoldingRangeExtractor.scala:35]: `All Defn statements except one-liners must fold` <- I would say 3 and more like for everything. This should be a clear requirement across the board. Sorry if I was unclear previously.

File: tests/unit/src/test/resources/foldingRange-scala3/expect/BlockWithNoBraces.scala [hunk 13]
```diff
@@ -21,4 +21,61 @@ object foo>>region>>:
   println("")
   println("")
   println("")
-  println("")<<region<<
\ No newline at end of file
+  println("")<<region<<
+
+def fooNested(): Unit =>>region>>
```
Comment (tgodzik) [inline tests/unit/src/test/resources/foldingRange-scala3/expect/BlockWithNoBraces.scala:26]: Could you also add tests with end markers?

File: tests/unit/src/test/resources/foldingRange/expect/Try.scala (hunk 8 above)
Comment (MaciejG604) [reply tests/unit/src/test/resources/foldingRange/expect/Try.scala:34]: fixed

File: tests/unit/src/test/resources/foldingRange/expect/Try.scala (hunk 9 above)
Comment (MaciejG604) [reply tests/unit/src/test/resources/foldingRange/expect/Try.scala:40]: fixed with the catch region

File: tests/unit/src/test/resources/foldingRange/expect/Blocks.scala (hunk 10 above)
Comment (MaciejG604) [reply tests/unit/src/test/resources/foldingRange/expect/Blocks.scala:22]: Okay so should we still keep the old if statement about the distance to enclosing fold?
```
case Foldable((pos, adjust))
             if span(enclosing) - span(pos) > distanceToEnclosingThreshold =>
```

Just make it not filter out definitions?

Comment (MaciejG604) [reply tests/unit/src/test/resources/foldingRange/expect/Blocks.scala]: It's like this now

**Review by tgodzik — APPROVED** [review]
LGTM! Looks like an overall improvement, though we might need to tinker more in the future, since this is very hard to nail for all the users.

Greato work!
