### PR TITLE
Handle fatal exceptions when evaluating worksheets.

### LINKED ISSUE #1456: Non Terminating Worksheet Evaluation for SO Condition
**Describe the bug**
Code that returns an SO in a normal App causes a non-terminating `Evaluated Worksheet` message and does not return an SO.

**To Reproduce**
Below code should reproduce issue within a `worksheet.sc` file.

```
def bigData = (1 to 1000000).toStream
def foldLeft[A, B](l: List[A], z: B)(f: (B, A) => B): B = l match {
  case Nil    => z
  case h :: t => foldLeft(t, f(z, h))(f)
}
def foldRightViaFoldLeft[A, B](l: List[A], z: B)(s: (A, B) => B): B =
  foldLeft(l, (x: B) => x)((e, f) => (x: B) => e(s(f, x)))(z)
foldRightViaFoldLeft(bigData.toList, 0)(_ + _) // doesn't terminate
```

**Installation:**
- Operating system: Linux
- Editor: Visual Studio Code
- Metals version: 
```
metals.serverVersion": "0.8.0+294-4dcdec07-SNAPSHOT
```

### PR DESCRIPTION
**Pull request by olafurpg**
Fixes #1456. Previously, fatal exceptions were not caught while
evaluating worksheet making them stay stuck in "evaluating". Now,
fatal exceptions are caught in mdoc and are reported inline
in worksheets like normal non-fatal exceptions.

### CODE REVIEW

File: metals/src/main/scala/scala/meta/internal/worksheets/WorksheetProvider.scala [hunk 1]
```diff
@@ -120,11 +119,12 @@ class WorksheetProvider(
       }
     }
     val onError: PartialFunction[Throwable, Option[EvaluatedWorksheet]] = {
-      case NonFatal(e) =>
-        scribe.error(s"worksheet: $path", e)
-        None
       case InterruptException() =>
         None
+      case e: Throwable =>
+        // NOTE(olafur): we catch all exceptions because of https://github.com/scalameta/metals/issues/1456
```
Comment (kpbochenek) [inline metals/src/main/scala/scala/meta/internal/worksheets/WorksheetProvider.scala]: catching all exceptions is handled in mdoc and they are converted to NonFatal errors which are already handled, this case is not related to mentioned issue, right?

Comment (olafurpg) [reply metals/src/main/scala/scala/meta/internal/worksheets/WorksheetProvider.scala]: It's correct that they should be caught by mdoc now but I added this case nevertheless to be sure. If there's something fatally broken about the JVM I suspect it will show up in the logs regardless.
