### PR TITLE
fix: colliding pattern and scope completions

### LINKED ISSUE #7291: Missing completion for object in pattern
### Describe the bug

Given the following snippet (cursor being `@@`):

```scala
package myPackage1 {
  class MyClass
  object MyClass {
    val TheValue = new MyClass
  }
}

object Test {
  val x = myPackage1.MyClass.TheValue
  x match {
    case My@@
  }
}
```

I get the completion `_: MyClass`, but not `MyClass`. I want the latter because the code I eventually want is `case MyClass.TheValue`.

---

Poking at the implementation, this seems to be because the `def toCaseObject` completion is tying the `case _: MyClass` completion to the `MyClass` symbol, which means that when workspace member completions are being considered, `MyClass` as a completion in its own right is incorrectly considered to be a "duplicate".

Seems like maybe the deduplication key being just on `Symbol` might be leading to some pattern completions and general member completions being incorrectly identified as duplicates. I'm not sure if the preferred appraoch would be to use a different key for deduplication (ex. `(Symbol, CompletionType)`) or find a way to make a fresh symbol that won't collide with the workspace one.

### Expected behavior

I'd expect to get a completion for both the `_` pattern and the companion object

### Operating system

Windows

### Editor/Extension

VS Code

### Version of Metals

1.5.1

### Extra context or search terms

_No response_

### PR DESCRIPTION
**Pull request by harpocrates**
This ensures that scope-based completions show up in a pattern context, even if the symbol to complete is the same as the one underlying a pattern completion (see the `underscore-and-object` test added)

This is achieved by putting case pattern completions in a new completion member with its own dedup-ing `id`.

Although it turned out to not matter in this specific case, also fixed `inverseSemanticdbSymbol` incorrectly returning an object symbol for some class symbols. That tweak on its own didn't affect any test output.

fixes #7291

### CODE REVIEW

File: mtags/src/main/scala-2/scala/meta/internal/pc/completions/MatchCaseCompletions.scala [hunk 1]
```diff
@@ -454,26 +454,38 @@ trait MatchCaseCompletions { this: MetalsGlobal =>
...
-        ),
-        sym = sym,
-        label = Some(label),
-        additionalTextEdits = autoImports
+
+      val edit = new l.TextEdit(
+        editRange,
+        label + cursorSuffix
       )
+      if (patternOnly.nonEmpty && name == pattern) {
```
Comment (harpocrates) [inline mtags/src/main/scala-2/scala/meta/internal/pc/completions/MatchCaseCompletions.scala:462]: This is a case to ensure that in something like

```scala
Option(123) match {
  case No@@
}
```

you only see `None` once instead of once for something from match completions then again from the general scope completions.

**Review by tgodzik — APPROVED** [review]
LGTM thanks!
