### PR TITLE
fix: create comption object after end marker

### LINKED ISSUE #3855: the companion object is created before the end marker in the code action
### Describe the bug

https://user-images.githubusercontent.com/93259201/164269839-283eff87-b577-4ead-83f7-c09663c55b7c.mov

### Expected behavior

Putting it after the end marker

### Operating system

_No response_

### Editor/Extension

_No response_

### Version of Metals

v0.11.3-SNAPSHOT

### Extra context or search terms

_No response_

### PR DESCRIPTION
**Pull request by dos65**
Fixes #3855

### CODE REVIEW

File: metals/src/main/scala/scala/meta/internal/metals/codeactions/CreateCompanionObjectCodeAction.scala [hunk 1]
```diff
@@ -68,6 +69,22 @@ class CreateCompanionObjectCodeAction(
 
   }
 
+  def endPosOfTree(t: Tree): Position = {
```
Comment (zmerr) [inline metals/src/main/scala/scala/meta/internal/metals/codeactions/CreateCompanionObjectCodeAction.scala:72]: I think it would be more readable if this returns `l.Position` to truly reflect the end position of the tree.

**Review by zmerr — COMMENTED** [review]
Thanks for the PR!

File: metals/src/main/scala/scala/meta/internal/metals/codeactions/CreateCompanionObjectCodeAction.scala (hunk 1 above)
Comment (dos65) [reply metals/src/main/scala/scala/meta/internal/metals/codeactions/CreateCompanionObjectCodeAction.scala:72]: In this case this is `scala.meta.inputs.Position`.
We use `l` prefix(`import org.eclipse.{lsp4j => l}`) for lsp structures.

**Review by tgodzik — APPROVED** [review]
LGTM!

File: metals/src/main/scala/scala/meta/internal/metals/codeactions/CreateCompanionObjectCodeAction.scala (hunk 1 above)
Comment (dos65) [reply metals/src/main/scala/scala/meta/internal/metals/codeactions/CreateCompanionObjectCodeAction.scala]: oh, right! changed

File: metals/src/main/scala/scala/meta/internal/metals/codeactions/CreateCompanionObjectCodeAction.scala [hunk 2]
```diff
@@ -68,6 +69,22 @@ class CreateCompanionObjectCodeAction(
...
+        // checks if the next child in parent after given tree is `EndMarker`
+        if (idx + 1 < p.children.length) {
+          p.children(idx + 1) match {
+            case marker: Term.EndMarker => Some(marker)
+            case _ => None
+          }
+        } else
+          None
+      }
+    endMarker.map(_.pos).getOrElse(t.pos).toLSP.getEnd
```
Comment (kpodsiad) [inline metals/src/main/scala/scala/meta/internal/metals/codeactions/CreateCompanionObjectCodeAction.scala:85]: Because `p.children` is a list I would rather avoid traversing it 3 times (`indexOf`, `p.children.length` and `p.children(idx + 1)`).
```suggestion
    val endMarkerPos: Option[Position] =
      t.parent.flatMap { p =>
        // check if tree just after t is its end marker
        val possibleEndMarker = p.children.dropWhile(_ != t).tail.headOption
        possibleEndMarker match {
          case Some(marker: Term.EndMarker) => Some(marker.pos)
          case _ => None
        }
      }
    endMarkerPos.getOrElse(t.pos).toLSP.getEnd
```

**Review by kpodsiad — COMMENTED** [review]
One minor suggestion

File: metals/src/main/scala/scala/meta/internal/metals/codeactions/CreateCompanionObjectCodeAction.scala (hunk 2 above)
Comment (dos65) [reply metals/src/main/scala/scala/meta/internal/metals/codeactions/CreateCompanionObjectCodeAction.scala]: thx!

**Review by kpodsiad — APPROVED** [review]
LGTM!
