### PR TITLE
Fix auto-connect BSP server without explicit choice.

### LINKED ISSUE #2291: Metals tries to connect to sbt server by default
**Describe the bug**

Metals gets stuck on "Connecting to sbt .." on clean sbt build.

**To Reproduce**

* Clean clone an sbt 1.4.3 build
* Start sbt with `sbt`
* Start Metals with `code .`
* Metals prompts to import the build (with Bloop), but Metals also tries to connect to sbt server

**Expected behavior**

I expected Metals to ignore `.bsp/sbt.json`. By default, I want Metals to only use Bloop to import sbt builds.

**Screenshots**

**Installation:**

- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.9.7

**Additional context**

**Search terms**

BSP, sbt, bloop

### PR DESCRIPTION
**Pull request by ckipp01**
Before this if a `.bsp/sbt.json` file existed and there was no `.bloop/`
yet then it would attempt to auto-connect to sbt. This behavior changes
this slightly now so that the behavior I just explains _only_ happens
if an explicit choice was made before, or if there is a `.bsp/<build-server>.json`
entry that is a Build Tool that Metals doesn't have Bloop support for.

This will supersede https://github.com/scalameta/metals/pull/2292 and closes #2291 

As always, my brain tried to over-complicate things when there was a simple solution. 😬

### CODE REVIEW

File: metals/src/main/scala/scala/meta/internal/bsp/BspConnector.scala [hunk 1]
```diff
@@ -33,7 +33,7 @@ class BspConnector(
 
   def resolve(): BspResolvedResult = {
     resolveExplicit().getOrElse {
-      if (buildTools.isBloop) ResolvedBloop
+      if (buildTools.loadSupported().nonEmpty) ResolvedBloop
```
Comment (ckipp01) [inline metals/src/main/scala/scala/meta/internal/bsp/BspConnector.scala:36]: `loadSupported` in builTools does pretty much exactly what we want. It checks if it's an sbt workspace, a gradle workspace, a maven workspace, or a mill workspace. Since we can handle all of those with Bloop, we then default to Bloop for all of them if there is no explicit choice made.

**Review by tgodzik — APPROVED** [review]
LGTM! I love when a small PR fixes an issue :+1:

**Comment by terpstra** [comment]
This change is horrible. It broke all of the new workspaces created at my company.

We now have to hand-hold developers through the process of opening the command palette and switching to the BSP implementation needed for our repositories. The BSP selection is hard to find and to a user who does not understand the BSP or how the scala-metals works, it's totally not obvious what is wrong; it just fails mysteriously now.

If a project has a .bsp/xyz.json, you should NOT USE BLOOP. The project essentially told you what is the right BSP to use for that project: xyz. scala-metals no reason to think bloop would work on that project.

In our scenario, we use neither bloop nor sbt. Any attempt to use a tool other than the BSP implementation referenced in .bsp/xyz.json will fail. The default BSP for a freshly opened workspace should definitely be the BSP referenced by that project.

**Comment by ckipp01** [comment]
> This change is horrible. It broke all of the new workspaces created at my company.

While we appreciate your feedback, I'll ask you to check your tone.

I'll address your concern in your bug report.

**Comment by terpstra** [comment]
Yeah, sorry about that. I was just super frustrated when I finally realized what had happened.
