### PR TITLE
Fix #5367: Support comma-separated paths in -Xplugin

### LINKED ISSUE #5367: Metals crashes when parsing `-Xplugin:` with comma-separated classpath
### Describe the bug

With Mill we are having problems with metals crashing (details in https://github.com/com-lihaoyi/mill/issues/2627)

It seems that Mill 0.11 passes a comma-separated list of paths as the classpath of a scalac plugin.

It seems that Metals is treating the value of `-Xplugin:` as a single path and that makes it crash.

https://github.com/scalameta/metals/blob/66a82f6279a3258842eb21472272f8d6f2df974d/metals/src/main/scala/scala/meta/internal/metals/CompilerPlugins.scala#L44-L46

### Expected behavior

Metals should handle comma-separated classpaths in the `-Xplugin:` scalac option.

### Operating system

None

### Editor/Extension

None

### Version of Metals

v0.11.12

### Extra context or search terms

Exception log:
```
2023.06.22 11:43:58 ERROR /Users/lorenzo/.ivy2/local/com.lihaoyi/mill-runner-linenumbers_2.13/0.11.0-27-d74d22-DIRTY65689b2b/jars/mill-runner-linenumbers_2.13.jar,/Users/lorenzo/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.13.11/scala-compiler-2.13.11.jar,/Users/lorenzo/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.11/scala-library-2.13.11.jar,/Users/lorenzo/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/lihaoyi/mill-moduledefs_2.13/0.10.9/mill-moduledefs_2.13-0.10.9.jar,/Users/lorenzo/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.13.11/scala-reflect-2.13.11.jar,/Users/lorenzo/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/io/github/java-diff-utils/java-diff-utils/4.12/java-diff-utils-4.12.jar,/Users/lorenzo/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/jline/jline/3.22.0/jline-3.22.0.jar,/Users/lorenzo/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/net/java/dev/jna/jna/5.13.0/jna-5.13.0.jar,/Users/lorenzo/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/lihaoyi/sourcecode_2.13/0.3.0/sourcecode_2.13-0.3.0.jar
java.nio.file.FileSystemException: /Users/lorenzo/.ivy2/local/com.lihaoyi/mill-runner-linenumbers_2.13/0.11.0-27-d74d22-DIRTY65689b2b/jars/mill-runner-linenumbers_2.13.jar,/Users/lorenzo/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.13.11/scala-compiler-2.13.11.jar,/Users/lorenzo/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.11/scala-library-2.13.11.jar,/Users/lorenzo/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/lihaoyi/mill-moduledefs_2.13/0.10.9/mill-moduledefs_2.13-0.10.9.jar,/Users/lorenzo/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.13.11/scala-reflect-2.13.11.jar,/Users/lorenzo/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/io/github/java-diff-utils/java-diff-utils/4.12/java-diff-utils-4.12.jar,/Users/lorenzo/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/jline/jline/3.22.0/jline-3.22.0.jar,/Users/lorenzo/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/net/java/dev/jna/jna/5.13.0/jna-5.13.0.jar,/Users/lorenzo/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/lihaoyi/sourcecode_2.13/0.3.0/sourcecode_2.13-0.3.0.jar: File name too long
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at sun.nio.fs.UnixFileSystemProvider.checkAccess(UnixFileSystemProvider.java:313)
	at jdk.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:127)
	at jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:109)
	at java.nio.file.FileSystems.newFileSystem(FileSystems.java:337)
	at java.nio.file.FileSystems.newFileSystem(FileSystems.java:286)
	at scala.meta.internal.io.PlatformFileIO$.newFileSystem(PlatformFileIO.scala:104)
	at scala.meta.internal.io.PlatformFileIO$.newJarFileSystem(PlatformFileIO.scala:100)
	at scala.meta.internal.io.PlatformFileIO$.withJarFileSystem(PlatformFileIO.scala:77)
	at scala.meta.internal.io.FileIO$.withJarFileSystem(FileIO.scala:44)
	at scala.meta.internal.metals.CompilerPlugins.isSupportedPlugin(CompilerPlugins.scala:65)
	at scala.meta.internal.metals.CompilerPlugins.$anonfun$filterSupportedOptions$2(CompilerPlugins.scala:46)
	at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.scala:17)
	at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:962)
	at scala.meta.internal.metals.CompilerPlugins.$anonfun$filterSupportedOptions$1(CompilerPlugins.scala:46)
	at scala.meta.internal.metals.CompilerPlugins.$anonfun$filterSupportedOptions$1$adapted(CompilerPlugins.scala:43)
	at scala.collection.immutable.List.filter(List.scala:515)
	at scala.collection.immutable.List.filter(List.scala:79)
	at scala.meta.internal.metals.CompilerPlugins.filterSupportedOptions(CompilerPlugins.scala:43)
	at scala.meta.internal.metals.Compilers.newCompiler(Compilers.scala:1027)
	at scala.meta.internal.metals.Compilers.newCompiler(Compilers.scala:1008)
	at scala.meta.internal.metals.Compilers.newCompiler(Compilers.scala:994)
	at scala.meta.internal.metals.Compilers.$anonfun$loadCompilerForTarget$2(Compilers.scala:833)
	at scala.meta.internal.metals.StatusBar.trackBlockingTask(StatusBar.scala:48)
	at scala.meta.internal.metals.Compilers.$anonfun$loadCompilerForTarget$1(Compilers.scala:833)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1134)
	at java.util.Collections$SynchronizedMap.computeIfAbsent(Collections.java:2682)
	at scala.meta.internal.metals.Compilers.loadCompilerForTarget(Compilers.scala:829)
	at scala.meta.internal.metals.Compilers.$anonfun$loadCompiler$2(Compilers.scala:818)
	at scala.Option.flatMap(Option.scala:283)
	at scala.meta.internal.metals.Compilers.loadCompiler(Compilers.scala:818)
	at scala.meta.internal.metals.Compilers.$anonfun$load$4(Compilers.scala:193)
	at scala.meta.internal.metals.Compilers.$anonfun$load$4$adapted(Compilers.scala:192)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at scala.meta.internal.metals.Compilers.$anonfun$load$1(Compilers.scala:192)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:678)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:829)
```

### PR DESCRIPTION
**Pull request by lolgab**
Fixes #5367

Required to support Mill `0.11`

### CODE REVIEW

File: metals/src/main/scala/scala/meta/internal/metals/CompilerPlugins.scala [hunk 1]
```diff
@@ -37,42 +37,45 @@ import scala.meta.io.AbsolutePath
...
-    path.isJar && {
-      try {
-        FileIO.withJarFileSystem(path, create = false, close = true) { root =>
-          val xml = XML.load(
-            Files.newInputStream(root.resolve("scalac-plugin.xml").toNIO)
-          )
-          val name = (xml \ "name").text
-          isSupportedPlugin(name)
+  private def isSupportedPlugin(paths: Seq[AbsolutePath]): Boolean = {
+    paths.exists { path =>
```
Comment (tanishiking) [inline metals/src/main/scala/scala/meta/internal/metals/CompilerPlugins.scala:61]: It seems like Metals will accept unsupported plugin in the following case like `-Xplugin:bm4,invalid-plugin` because `bm4` is supported plugin, and `paths.exists` will be true in this case.

Comment (lolgab) [reply metals/src/main/scala/scala/meta/internal/metals/CompilerPlugins.scala:61]: In Mill we use `-Xplugin:` with comma-separated list of paths for the classpath to run that specific plugin. I don't know if you can pass multiple plugins on the same `-Xplugin:` list. If you can, how can handle this scenario?

Comment (ckipp01) [reply metals/src/main/scala/scala/meta/internal/metals/CompilerPlugins.scala:61]: > I don't know if you can pass multiple plugins on the same -Xplugin: list.

So I don't think there is anything keeping someone from doing that. I was curious in Scala 3 so I took a look [here](https://github.com/lampepfl/dotty/blob/b461c943dbe47caf19f975833d686d8e666b5285/compiler/src/dotty/tools/dotc/plugins/Plugins.scala#L28-L45) and if I'm understanding what is happening correctly that classpath _could_ in theory hold multiple different plugins. Most often that's not the case and instead it's just the classpath necessary for a single plugin to work (I do the same thing in [sbt-scoverage](https://github.com/scoverage/sbt-scoverage/blob/e4a5bc7d5c3bc66c9f18a1b7ef73a54081b64858/src/main/scala/scoverage/ScoverageSbtPlugin.scala#L151)), but in theory I think this could be two independent plugins.

The tricky part is how would you know what part of the classpath is supposed to be for the plugin vs another plugin. I have a feeling that this is incredibly niche.

> It seems like Metals will accept unsupported plugin in the following case like -Xplugin:bm4,invalid-plugin because bm4 is supported plugin, and paths.exists will be true in this case.

@tanishiking out of curiosity, have you seen plugins defined like this out in the wild?

Comment (tanishiking) [reply metals/src/main/scala/scala/meta/internal/metals/CompilerPlugins.scala:61]: The plugin I had in mind was actually `sbt-scoverage`, but, right, sbt-scoverage case is "part of the classpath is supposed to be for the plugin" and they should be valid. (I overlooked this case even though `sbt-scoverage` was in my mind 😅 )

I was a bit worried at first, what if users somehow sneak in the invalid plugin this way, but now I have a second thought that it's indeed too niche.

So, never mind, about my first comment!

**Review by tanishiking — APPROVED** [review]
After some conversations, I found my concern at a first glance was not a problem, now it's LGTM. Thanks!

**Review by ckipp01 — APPROVED** [review]
Yup, LGTM from me as well. Thanks @lolgab!
