### PR TITLE
Coursier resolve to validate serverVersion, log to console if correct/incorrect

### LINKED ISSUE #303: VS Extension: Try to resolve serverVersion, alert user if not found
Plan: Extend this [code](https://github.com/scalameta/metals/blob/652cf98f0dc3c4a1861a5e583c9bf9188c54b6e4/vscode-extension/src/extension.ts#L26-L42), add a `coursier resolve` to check if the server version exists before launching it, and reply to user with informative msg if resolve fails

Arose from [gitter](https://gitter.im/scalameta/metals?at=5af003fa40f24c43045acb87)

### PR DESCRIPTION
**Pull request by benhutchison**
I'm not particularly fluent with JS nor VSCode APIs so this is a fairly basic implementation. It can definitely be refined further, such as @laughedelic suggestion of a progress bar. 

However I would say that its an improvement vs status quo; definitely better to have some feedback to user whether the metals server has been resolved successfully or not.

I have manually tested both the Happy and Unhappy paths.

Fixes #303

### CODE REVIEW

File: vscode-extension/src/extension.ts [hunk 1]
```diff
@@ -1,6 +1,7 @@
 "use strict";
 
 import * as path from "path";
+import * as cp from 'child_process';
```
Comment (gabro) [inline vscode-extension/src/extension.ts]: minor, but since you're using a single function from `child_process` I would do

```js
import { spawn } from 'child_process';
```

File: vscode-extension/src/extension.ts [hunk 2]
```diff
@@ -110,5 +124,18 @@ export async function activate(context: ExtensionContext) {
     );
   });
 
-  context.subscriptions.push(client.start(), restartServerCommand);
+
+  cp.spawn('java', resolveArgs)
+    .on('exit', function(code) {
```
Comment (gabro) [inline vscode-extension/src/extension.ts]: You can use the "fat-arrow" for conciseness:

```js
.on('exit', code => {
  ...
})
```

**Comment by benhutchison** [comment]
Thanks for review, changes made.

File: vscode-extension/src/extension.ts [hunk 3]
```diff
@@ -110,5 +124,18 @@ export async function activate(context: ExtensionContext) {
     );
   });
 
-  context.subscriptions.push(client.start(), restartServerCommand);
+
+  spawn('java', resolveArgs)
+    .on('exit', code => {
+      if (code !== 0) {
+        console.error(
```
Comment (olafurpg) [inline vscode-extension/src/extension.ts]: Do you need to have the console open to see this message? I just tried locally with a dummy serverVersion and couldn't get this message to appear 🤔

**Comment by benhutchison** [comment]
Strange. There should be output msg in the console whether it’s success or
fail, whether open or closed.

Double check..?
- the change is in the version you’re running
- you’ve triggered loading of the extension by eg opening a Scala file

**Comment by benhutchison** [comment]
What remains to get this merged? It’s testing OK for me

File: vscode-extension/src/extension.ts (hunk 3 above)
Comment (gabro) [reply vscode-extension/src/extension.ts]: how about making this a `window.showErrorMessage` instead? I think it's worth being extra explicit when this happens

Comment (benhutchison) [reply vscode-extension/src/extension.ts]: Makes sense, done. I send the errror message to both console & window because I think console should retain history log of important events like this.

File: vscode-extension/src/extension.ts [hunk 4]
```diff
@@ -128,10 +128,10 @@ export async function activate(context: ExtensionContext) {
   spawn('java', resolveArgs)
     .on('exit', code => {
       if (code !== 0) {
-        console.error(
-          `Could not find Metals server artifact, ensure that metals.serverVersion setting is correct
-           Coursier resolve failed on:${artifact} with exit code:${code}.`
-        );
+        const msg =  `Could not find Metals server artifact, ensure that metals.serverVersion setting is correct.
+                      Coursier resolve failed on:${artifact} with exit code:${code}.`.replace(/^(\s{2})+/gm, '');
```
Comment (laughedelic) [inline vscode-extension/src/extension.ts]: Does this `replace` just removes indentation from the stacktrace? Is it necessary?

File: vscode-extension/src/extension.ts [hunk 5]
```diff
@@ -110,5 +124,18 @@ export async function activate(context: ExtensionContext) {
     );
   });
 
-  context.subscriptions.push(client.start(), restartServerCommand);
+
+  spawn('java', resolveArgs)
+    .on('exit', code => {
+      if (code !== 0) {
+        const msg =  `Could not find Metals server artifact, ensure that metals.serverVersion setting is correct.
+                      Coursier resolve failed on:${artifact} with exit code:${code}.`.replace(/^(\s{2})+/gm, '');
```
Comment (laughedelic) [inline vscode-extension/src/extension.ts]: I don't know if there's a better way to do this in TS, but it wasn't obvious for me that this is meant to be like `.stripMargin` in Scala.

Comment (gabro) [reply vscode-extension/src/extension.ts]: I really miss `.stripMargin` in JavaScript.

The "trick" I usually adopt is:

```js
const msg = [
  'Could not find Metals server artifact, ensure that metals.serverVersion setting is correct.',
  `Coursier resolve failed on:${artifact} with exit code:${code}.`
].join('\n')
```

**Comment by gabro** [comment]
🎉 thank you for the contribution and for the patience @benhutchison!
