### PR TITLE
Remove unstable parts

### LINKED ISSUE #327: Drop unstable features that nobody is working on
Metals currently supports completions and diagnostics-as-you-type by using the presentation compiler. This functionality is not enabled by default because it doesn't work well, in particular for multi-module builds and longer running coding sessions. There is no ongoing effort to make this functionality work robustly so I propose to remove it altogether. Keeping the functionality is a maintenance burden both code-wise and documentation-wise.

Any objections?

### PR DESCRIPTION
**Pull request by olafurpg**
Fixes #327 

This commit removes unstable features that nobody is working on at the
moment:

- completions and signature help with the presentation compiler.
- diagnostics as you type with the presentation compiler.
- hover with an old scalafix type printer. This will be replaced
  with one of the newer type printers that is based on the new
  symbol tables.
- linting with Scalafix, the integration uses an old internal API.
  Scalafix now has a public API for build tools that we should hook into
  instead. Refactoring to use the new API is equivalent to a full
  rewrite so we may as well remove the current integration.

This commit also updates the project overview to reflect the current
status.

### CODE REVIEW

File: metals/src/test/scala/tests/provider/HoverProviderTest.scala [hunk 1]
```diff
@@ -1,302 +0,0 @@
-package tests.provider
-
-object HoverProviderTest extends BaseHoverProviderTest {
```
Comment (olafurpg) [inline metals/src/test/scala/tests/provider/HoverProviderTest.scala]: I was tempted to keep this test suite since it has many useful tests. I plan to revive it once we have upgraded to the latest Scalameta.

File: metals/src/main/scala/scala/meta/metals/providers/CodeActionProvider.scala [hunk 2]
```diff
@@ -1,21 +0,0 @@
...
-
-import scala.meta.metals.WorkspaceCommand.ScalafixUnusedImports
-import scala.meta.lsp.CodeActionParams
-import scala.meta.lsp.Command
-import scala.meta.lsp.Diagnostic
-import scala.meta.lsp.Command
-import io.circe.syntax._
-
-object CodeActionProvider {
-  def codeActions(params: CodeActionParams): List[Command] = {
```
Comment (olafurpg) [inline metals/src/main/scala/scala/meta/metals/providers/CodeActionProvider.scala]: I was tempted to keep this infrastructure but decided to remove it since it would be dead code. We can revive it once we add more code actions.

File: docs/overview.md [hunk 3]
```diff
@@ -3,60 +3,36 @@ id: overview
...
-  * Disabled by default. Can be enabled with configuration option
-    `sbt.enabled=true`.
-  * Requires a running sbt 1.1 server or later.
-* [x] Linting with [Scalafix][].
-  * Requires [semanticdb-scalac](#semanticdb-scalac).
-  * Supports both built-in and custom linter rules.
+build tool (source directories, dependencies, compiler flags) so we are still
+exploring what is the best option.
+
+- [x] sbt-metals: plugin that provides a `metalsSetup` task to export sbt build
```
Comment (gabro) [inline docs/overview.md]: I think having these checkboxes isn't helpful. Pretty much everything is under exploration so they give a false sense of accomplishment.

Comment (olafurpg) [reply docs/overview.md]: Good point, I will remove them 👍
