### PR TITLE
bugfix: Include jvm properties from build server when running from MCP

### LINKED ISSUE #8305: MCP test runner ignores Test / javaOptions from build.sbt (and .jvmopts/env vars)
### Describe the bug

When running tests via MCP, JVM options configured in `build.sbt` under `Test / javaOptions` are silently ignored, causing test failures that don't occur when running via bloop, sbt, or the editor UI (DAP).

The MCP test path in `McpTestRunner.runTests()` constructs `ScalaTestSuites` with hardcoded empty JVM options:

```scala
  // McpTestRunner.scala
  val testSuites = new b.ScalaTestSuites(
    List(testSelection).asJava,
    Nil.asJava,  // jvmOptions — always empty
    Nil.asJava,  // environmentVariables — always empty
  )
```

It then creates a `TestSuiteDebugAdapter` and runs the test directly inside Metals, completely bypassing the build server. `TestSuiteDebugAdapter.run()` forks the JVM using only `testClasses.getJvmOptions()`, which is the empty list above.

This contrasts with the DAP path, which calls `DebugProvider.startDebugSession()`. That method checks `buildServer.isDebuggingProvider || buildServer.isSbt` and — for both bloop and sbt — forwards the debug session request to the build server. The build server then handles test execution with full knowledge of `Test / javaOptions` from the build definition.

Two separate issues:

  1. `McpTestRunner` doesn't call `JvmOpts.fromWorkspaceOrEnvForTest(workspace)`, so even .test-jvmopts, TEST_JVM_OPTS, .jvmopts, and JVM_OPTS are ignored. The DAP path reads these via `DebugDiscovery.createScalaTestSuites()` and `DebugProvider.startTestSuite()`.
  2. More fundamentally, because the MCP path bypasses the build server entirely, `Test / javaOptions` defined in build.sbt can never be picked up — regardless of whether bloop or sbt is the build server.

### Expected behavior

Tests run via MCP should respect the same JVM options as when run via the editor UI or directly via the build tool.

### Operating system

macOS

### Editor/Extension

Nvim (nvim-metals)

### Version of Metals

Latest snapshot

### Scala version/s

All

### Extra context or search terms

_No response_

### PR DESCRIPTION
**Pull request by tgodzik**
Fixes https://github.com/scalameta/metals/issues/8305

## Summary by CodeRabbit

* **Bug Fixes**
  * Test execution now respects per-target JVM options and environment variables by merging workspace and build-provided settings so forked test processes run with the intended JVM flags and env vars.

* **Tests**
  * Added a test that verifies the test runner forwards workspace JVM options into the forked test JVM.

### CODE REVIEW

File: metals/src/main/scala/scala/meta/internal/metals/debug/DebugProvider.scala [hunk 1]
```diff
@@ -410,6 +410,27 @@ class DebugProvider(
...
+  )(implicit ec: ExecutionContext): Future[List[String]] = {
+    val workspaceOpts =
+      JvmOpts.fromWorkspaceOrEnvForTest(workspace).getOrElse(Nil)
+    buildTargetClasses.jvmRunEnvironment(buildTargetId, isTests = true).map {
+      envOpt =>
+        val bspOpts = envOpt
+          .flatMap(env => Option(env.getJvmOptions()))
+          .map(_.asScala.toList)
+          .getOrElse(Nil)
+        (workspaceOpts ++ bspOpts).distinct
```
[the remark this answers is not in the document]
Comment (tgodzik) [reply metals/src/main/scala/scala/meta/internal/metals/debug/DebugProvider.scala]: Forgot about env variables, added

File: metals/src/main/scala/scala/meta/internal/metals/debug/server/DebugeeParamsCreator.scala [hunk 2]
```diff
@@ -55,11 +63,14 @@ class DebugeeParamsCreator(buildTargetClasses: BuildTargetClasses) {
       val includedInLibsOrModules =
         debugLibs.map(_.absolutePath).toSet ++ modules.map(_.absolutePath).toSet
 
+      val jvmRunEnvFuture = jvmRunEnvironmentOverride.getOrElse(
```
Comment (zielinsky) [inline metals/src/main/scala/scala/meta/internal/metals/debug/server/DebugeeParamsCreator.scala]: expand `Env` -> `Environment` to stay consistent
```suggestion
      val jvmRunEnvironmentFuture = jvmEnvironmentFuture.getOrElse(
```

File: metals/src/main/scala/scala/meta/internal/metals/debug/server/DebugeeParamsCreator.scala [hunk 3]
```diff
@@ -25,11 +26,18 @@ import ch.epfl.scala.debugadapter.UnmanagedEntry
...
+   * @param isTests whether the build target is a test target
+   * @param jvmRunEnvironmentOverride when set, this future is used instead of calling
+   *        `buildTarget/jvmTestEnvironment` or `buildTarget/jvmRunEnvironment` again
+   *        (for example after the same future was used to assemble ScalaTest JVM options and env).
+   */
   def create(
       id: BuildTargetIdentifier,
       cancelPromise: Promise[Unit],
       isTests: Boolean,
+      jvmRunEnvironmentOverride: Option[Future[Option[JvmEnvironmentItem]]] =
```
Comment (zielinsky) [inline metals/src/main/scala/scala/meta/internal/metals/debug/server/DebugeeParamsCreator.scala]: maybe `jvmEnvironmentFuture` would be clearer?
```suggestion
      jvmEnvironmentFuture: Option[Future[Option[JvmEnvironmentItem]]] =
```

**Review by zielinsky — APPROVED** [review]
LGTM!:> Two minor naming nits to consider

File: metals/src/main/scala/scala/meta/internal/metals/debug/server/DebugeeParamsCreator.scala (hunk 3 above)
Comment (tgodzik) [reply metals/src/main/scala/scala/meta/internal/metals/debug/server/DebugeeParamsCreator.scala]: Sure!

File: metals/src/main/scala/scala/meta/internal/metals/debug/server/DebugeeParamsCreator.scala (hunk 2 above)
Comment (tgodzik) [reply metals/src/main/scala/scala/meta/internal/metals/debug/server/DebugeeParamsCreator.scala]: This duplicated the name, but I just inlined it into the for comprhension
