### PR TITLE
Use correct parent classloader for worksheets.

### LINKED ISSUE #2187: ClassDefNotFound error only in Worksheet
Trying to follow the Book of Doobie using a Worksheet, the following code produces a `ClassDefNotFound` exception when in a worksheet context. This same exact code works when input directly into ammonite's REPL or when compiled in a standard scala file via SBT.

**To Reproduce**

Create a worksheet (e.g. `book-of-doobie.worksheet.sc`) with the following code:

```scala
import $ivy.`org.tpolecat::doobie-core:0.9.0`
import $ivy.`org.tpolecat::doobie-postgres:0.9.0`
import $ivy.`org.tpolecat::doobie-specs2:0.9.0`

import cats._, cats.effect._, cats.data._, cats.implicits._
import doobie._
import doobie.implicits._

import doobie.util.ExecutionContexts
implicit val cs = IO.contextShift(ExecutionContexts.synchronous)

val xa = Transactor.fromDriverManager[IO](
  "org.postgresql.Driver",     // driver classname
  "jdbc:postgresql:world",     // connect URL (driver-specific)
  "postgres",                  // user
  "",                          // password
  Blocker.liftExecutionContext(ExecutionContexts.synchronous) // just for testing
)
```
```
[mdoc] [E] java.lang.NoClassDefFoundError: java/sql/Connection
  at doobie.util.transactor$Transactor$fromDriverManager$.apply(transactor.scala:377)                                                                          
  at repl.MdocSession$App.<init>(book-of-doobie.worksheet.sc:35)
  at repl.MdocSession$.app(book-of-doobie.worksheet.sc:3)
```

**Expected behavior**

Code should compile without error

**Installation:**

- Operating system: macOS
- Editor: nvim
- Metals version: v0.9.5 via coc-metals

### PR DESCRIPTION
**Pull request by ckipp01**
Instead of passing in `null` when we extend ClassLoader in our
MdocClassLoader this passes in the actual parent since on Java +9 when
using `null` that's the bootstrap classloader which doesn't contain
modules like java.sql.

Big thanks to @smarter pointing this out in https://github.com/lampepfl/dotty/pull/11658.

Fixes #2187

### CODE REVIEW

File: metals/src/main/scala/scala/meta/internal/worksheets/WorksheetClassLoader.scala [hunk 1]
```diff
@@ -8,7 +8,7 @@ package scala.meta.internal.worksheets
  * allowing the Metals server to call mdoc instances from different Scala
  * versions.
  */
-class MdocClassLoader(parent: ClassLoader) extends ClassLoader(null) {
+class MdocClassLoader(parent: ClassLoader) extends ClassLoader(parent) {
```
Comment (tgodzik) [inline metals/src/main/scala/scala/meta/internal/worksheets/WorksheetClassLoader.scala:11]: So I think this one was on purpose in order not to bring in the Scala 2.12 classes from Metals server. Maybe let's use exactly what was used in Dotty?
```suggestion
class MdocClassLoader(parent: ClassLoader) extends ClassLoader(ClassLoader.getSystemClassLoader.getParent) {
```

**Review by tgodzik — CHANGES_REQUESTED** [review]
Thanks for looking into that! We are having some issues with Scala 2.13 and Scala 3 worksheets.

File: metals/src/main/scala/scala/meta/internal/worksheets/WorksheetClassLoader.scala (hunk 1 above)
Comment (ckipp01) [reply metals/src/main/scala/scala/meta/internal/worksheets/WorksheetClassLoader.scala:11]: Ahh yes, I was just looking at the failures now. Let me try that.

**Comment by tgodzik** [comment]
Also, https://github.com/scalameta/metals/issues/2525 is probably related.

**Comment by ckipp01** [comment]
> Also, #2525 is probably related.

Playing around with it a bit, this doesn't change that behavior at all, so I don't think it is.

**Comment by tgodzik** [comment]
> > Also, #2525 is probably related.
> 
> Playing around with it a bit, this doesn't change that behavior at all, so I don't think it is.

The resources in akka are coming most likely from the classloader, which we change, so I thought it might be connected :thinking:  I will take a look at it.

**Review by tgodzik — APPROVED** [review]
LGTM!
