### PR TITLE
fix: override mtags-interfaces snapshot dependency for problematic Scala 3.x versions

### LINKED ISSUE #7780: Metals broken with Scala `3.5.0` (misleading recommandation)
### Describe the bug

Metals seems to fail downloading mtags-intrfaces for Scala `3.5.0`:
```
2025.09.09 10:37:48 ERROR Error downloading Dependency{module=Module(org.scala-lang, scala3-presentation-compiler_3), version='3.5.0', exclusions=[], configuration='', publication=null, transitive=true, overrides={}}
coursierapi.error.SimpleResolutionError$1: Error downloading org.scalameta:mtags-interfaces:1.3.0+56-a06a024d-SNAPSHOT
  not found: /Users/katarzynamarek/.ivy2/local/org.scalameta/mtags-interfaces/1.3.0+56-a06a024d-SNAPSHOT/ivys/ivy.xml
```
My understanding is that this version is no longer supported by Metals, due to dependency on some `mtags-interfaces` snapshot. However the message in the Metals doctor is misleading:

Image

### Expected behavior

The message should correctly inform that `3.5.0` is **no longer** supported and Scala version should be upgraded.
### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

1.6.2

### Scala version/s

3.5.0

### Extra context or search terms

_No response_

### PR DESCRIPTION
**Pull request by warcholjakub**
# Fixes #7780
This PR fixes an issue where Metals attempted to resolve a snapshot version of mtags-interfaces for certain Scala 3.x releases (notably 3.4.0–3.5.0), resulting in dependency resolution failures.
## Key changes include:
- Introduced `mtagsInterfaceOverride`, a map that overrides the problematic snapshot dependency with the next available stable version of mtags-interfaces for affected Scala 3.x versions.
- Added a new test suite (`MtagsResolverSuite`) to verify that mtags-interfaces can be resolved for all affected Scala versions.
## As a result:
- Metals now correctly resolves and downloads a stable mtags-interfaces artifact for these Scala versions.

### CODE REVIEW

File: metals/src/main/scala/scala/meta/internal/metals/Embedded.scala [hunk 1]
```diff
@@ -298,6 +298,14 @@ object Embedded {
       resolution: Option[ResolutionParams] = None,
   ): Fetch = {
 
+    val mtagsInterfaceOverride = Map(
+      "3.5.0" -> "1.3.1",
+      "3.4.3" -> "1.3.0",
+      "3.4.2" -> "1.3.0",
+      "3.4.1" -> "1.2.1",
+      "3.4.0" -> "1.2.0",
```
Comment (tgodzik) [inline metals/src/main/scala/scala/meta/internal/metals/Embedded.scala:306]: Could you also add a test for hover on 3.5.0 version. To make sure we don't break anything with the resolution?

**Review by tgodzik — APPROVED** [review]
