### PR TITLE
bugfix: Fix issue with uri is wrongly sent for watching

### LINKED ISSUE #8292: LSP file watcher sends invalid glob pattern (file:///.../*.sbt) causing errors in Neovim 0.12
### Describe the bug

When opening a Scala project in Neovim 0.12.x, Metals sends a `workspace/didChangeWatchedFiles` 
registration with a `globPattern` that includes a `file:///` URI prefix (e.g. 
`file:///<scala-project-path>/*.sbt`). Neovim 0.12 introduced a stricter LSP-compliant glob 
parser that rejects URI-prefixed patterns, resulting in a visible error on startup.

## Steps to reproduce

1. Install Neovim 0.12.x
2. Open a Scala/sbt project with Metals (v1.6.6)
3. Observe the error on startup

## Error Message

`LSP[metals]: Error SERVER_REQUEST_HANDLER_ERROR: ".../vim/glob.lua:373: Invalid glob: file:///<scala-project-path>/*.sbt"`

## Expected behavior

Metals should send plain glob patterns (e.g. `**/*.sbt`) in `workspace/didChangeWatchedFiles` 
registrations rather than URI-prefixed paths. Per the 
[LSP 3.17 spec](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#pattern), 
`globPattern` should be a plain pattern string, not a URI.

## Environment

- **Metals version:** 1.6.6
- **Neovim version:** 0.12.1
- **OS:** macOS (Apple Silicon)
- **Build tool:** sbt

## Additional context

This was introduced/exposed by Neovim's updated `vim.glob.to_lpeg()` implementation in 0.12, 
which now strictly follows the LSP 3.17 spec. Other LSP servers have hit the same issue 
(see [neovim/neovim#34164](https://github.com/neovim/neovim/issues/34164)).

The fix would be for Metals to send glob patterns without the `file:///` URI prefix in 
`workspace/didChangeWatchedFiles` registrations.

### Operating system

macOS

### Editor/Extension

Nvim (nvim-metals)

### Version of Metals

v1.6.6

### Scala version/s

2.13.18

### Extra context or search terms

_No response_

### PR DESCRIPTION
**Pull request by tgodzik**
Fixes https://github.com/scalameta/metals/issues/8292

## Changes

- Updated default glob syntax mode for file pattern matching in projects, changing from URI to Path mode
- Simplified glob syntax configuration naming from VSCode to Path for improved clarity and consistency
- Maintained full backward compatibility with existing glob pattern matching options including both Path and URI modes for flexible workspace configuration

### CODE REVIEW

**Review by omar-s-ta — APPROVED** [review]

**Comment by omar-s-ta** [comment]
I had a PR ready for contribution when someone acknowledges the issue. Thanks for the quick change.

File: metals/src/main/scala/scala/meta/internal/metals/Configs.scala [hunk 1]
```diff
@@ -16,13 +16,13 @@ object Configs {
...
     def isUri: Boolean = this == uri
-    def isVscode: Boolean = this == vscode
+    def isPath: Boolean = this == path
     def registrationOptions(
         workspace: AbsolutePath
     ): DidChangeWatchedFilesRegistrationOptions = {
       val root: String =
-        if (isVscode) workspace.toString()
-        else workspace.toURI.toString.stripSuffix("/")
+        if (isUri) workspace.toURI.toString.stripSuffix("/")
```
Comment (omar-s-ta) [inline metals/src/main/scala/scala/meta/internal/metals/Configs.scala:24]: Wouldn't `val root: String = workspace.toString()` be a simpler change?
As far as my simple understanding, it shall be backward compatible too.

Comment (tgodzik) [reply metals/src/main/scala/scala/meta/internal/metals/Configs.scala:24]: I am not sure which editors required the uri, so I figured that if any had that option set then we keep it as uri. Otherwise we change the new default

**Comment by tgodzik** [comment]
> I had a PR ready for contribution when someone acknowledges the issue. Thanks for the quick change.

Ach, sorry! It was simple enough change figured I can do it right away
