### PR TITLE
java version through shell

### LINKED ISSUE #3536: JavaInteractiveSemanticDb - jdk version inferring issue
### Describe the bug

It was reported [here](https://github.com/scalameta/metals/issues/3500#issuecomment-1013722332).

Currently, we detect jdk version by reading `$JVM_HOME/release` and `version` field value from it.
We expected that it should works for Jdk11+ version but it seems there is no guarantee that `release` file will be presented in jdk-distributive.

As a solution if there is no `release` file we can try to obtain it from the running `java --version`.

### Expected behavior

_No response_

### Operating system

_No response_

### Editor/Extension

_No response_

### Version of Metals

v0.11.1

### Extra context or search terms

_No response_

### PR DESCRIPTION
**Pull request by zmerr**
resolves #3536

### CODE REVIEW

File: metals/src/main/scala/scala/meta/internal/builds/ShellRunner.scala [hunk 1]
```diff
@@ -130,3 +133,80 @@ class ShellRunner(
...
+
+      //       logInfo: Boolean = true
+  ):
+  // Future[
+  Option[String]
+  //  ]
+  = {
+    //   val elapsed = new Timer(time)
+
+    val env = additionalEnv ++ maybeJavaHome.map("JAVA_HOME" -> _).toMap
```
Comment (tgodzik) [inline metals/src/main/scala/scala/meta/internal/builds/ShellRunner.scala:162]: IF we already have `"JAVA_HOME" ` we should use that. I don't think there is a need for additional env.

File: metals/src/main/scala/scala/meta/internal/builds/ShellRunner.scala [hunk 2]
```diff
@@ -130,3 +133,80 @@ class ShellRunner(
...
 
 }
+
+object ShellRunner {
+
+  /**
+   * Note: if returning a [[Future]] is more suitable, all you
+   * need to do is to uncomment the commented code.
+   */
+  def quickRunWithShortStringResult(
```
Comment (tgodzik) [inline metals/src/main/scala/scala/meta/internal/builds/ShellRunner.scala:143]: Why not add it along the other methods? We could cache the Java home in that case inside the class.

```suggestion
  def runSync(
```

File: metals/src/main/scala/scala/meta/internal/builds/ShellRunner.scala [hunk 3]
```diff
@@ -130,3 +133,80 @@ class ShellRunner(
...
+      redirectErrorOutput: Boolean,
+      additionalEnv: Map[String, String] = Map.empty,
+      processOut: String => Unit = scribe.info(_),
+      processErr: String => Unit = scribe.error(_),
+      propagateError: Boolean = false,
+      maybeJavaHome: Option[String]
+
+      //       logInfo: Boolean = true
+  ):
+  // Future[
```
Comment (tgodzik) [inline metals/src/main/scala/scala/meta/internal/builds/ShellRunner.scala:156]: Let's remove these if not needed. I think it should be fine to run it synchronously since it should be quick. Just let's name the method explicitely.

File: metals/src/main/scala/scala/meta/internal/builds/ShellRunner.scala [hunk 4]
```diff
@@ -130,3 +133,80 @@ class ShellRunner(
...
+    //      .add(() => taskResponse.cancel(false))
+
+    //    processFuture.map { code =>
+    //      taskResponse.cancel(false)
+    //      if (logInfo)
+    //        scribe.info(s"time: ran '$commandRun' in $elapsed")
+    //     result.trySuccess(code match {
+    //       case ExitCodes.Success =>
+
+    val scanner = new Scanner(ps.inputStream).useDelimiter("\\A")
```
Comment (tgodzik) [inline metals/src/main/scala/scala/meta/internal/builds/ShellRunner.scala:204]: Could you maybe move the reading of the string to `JdkVersion` and test it with unit tests?

I don't think it will work with this sample output:
```
openjdk version "17.0.2" 2022-01-18
OpenJDK Runtime Environment Temurin-17.0.2+8 (build 17.0.2+8)
OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (build 17.0.2+8, mixed mode, sharing)
```
did you test it?

File: metals/src/main/scala/scala/meta/internal/metals/JavaInteractiveSemanticdb.scala [hunk 5]
```diff
@@ -227,38 +227,38 @@ case class JdkVersion(
 
 object JdkVersion {
 
-  def getJavaVersionFromJavaHome(
-      javaHome: AbsolutePath
+  def maybeJdkVersionFromJavaHome(
+      maybeJavaHome: Option[AbsolutePath]
   ): Option[JdkVersion] = {
-
-    def fromReleaseFile: Option[JdkVersion] = {
```
Comment (tgodzik) [inline metals/src/main/scala/scala/meta/internal/metals/JavaInteractiveSemanticdb.scala:234]: This should not be removed. We should only use `quickRunWithShortStringResult` as a last resort.

File: metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala [hunk 6]
```diff
@@ -389,13 +389,21 @@ class MetalsLanguageServer(
           workspace,
           fingerprints
         )
+
+        val optJavaHome =
+          (userConfig.javaHome orElse JdkSources.defaultJavaHome)
+            .map(AbsolutePath(_))
+        val maybeJdkVersion: Option[JdkVersion] =
+          JdkVersion.maybeJdkVersionFromJavaHome(optJavaHome)
```
Comment (tgodzik) [inline metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala:397]: If we already have javaHome thre is no need to run it.

**Review by tgodzik — CHANGES_REQUESTED** [review]

File: metals/src/main/scala/scala/meta/internal/metals/JavaInteractiveSemanticdb.scala (hunk 5 above)
Comment (zmerr) [reply metals/src/main/scala/scala/meta/internal/metals/JavaInteractiveSemanticdb.scala:234]: I remember on the linked issue, you concluded the matter in a different way. Could you please take a look [here](https://github.com/scalameta/metals/issues/3536#issuecomment-1110088096) to see what best can be done about it?

File: metals/src/main/scala/scala/meta/internal/builds/ShellRunner.scala (hunk 2 above)
Comment (tgodzik) [reply metals/src/main/scala/scala/meta/internal/builds/ShellRunner.scala:143]: Do you access it in the tests? I can't find it.

File: metals/src/main/scala/scala/meta/internal/metals/JavaInteractiveSemanticdb.scala (hunk 5 above)
Comment (zmerr) [reply metals/src/main/scala/scala/meta/internal/metals/JavaInteractiveSemanticdb.scala:234]: Ok, no problem.

File: metals/src/main/scala/scala/meta/internal/builds/ShellRunner.scala (hunk 2 above)
Comment (zmerr) [reply metals/src/main/scala/scala/meta/internal/builds/ShellRunner.scala:143]: tests/unit/src/test/scala/tests/troubleshoot/ProblemResolverSuite.scala is calling this static method:

`JdkVersion.maybeJdkVersionFromJavaHome(javaHome.map(AbsolutePath(_)))`

which in turn is calling `quickRunWithShortStringResult` as a static method.

File: metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala (hunk 6 above)
Comment (tgodzik) [reply metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala:397]: I just meant we should do `optJavaHome.getOrElse(JdkVersion.maybeJdkVersionFromJavaHome())`

File: metals/src/main/scala/scala/meta/internal/builds/ShellRunner.scala (hunk 2 above)
Comment (tgodzik) [reply metals/src/main/scala/scala/meta/internal/builds/ShellRunner.scala:143]: Ok, I guess we could leave it as is, but please try and cache the value maybe in an atomic inside the object?.

File: metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala (hunk 6 above)
Comment (tgodzik) [reply metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala:397]: It's javaHome :facepalm: It's fine then :+1:

File: metals/src/main/scala/scala/meta/internal/builds/ShellRunner.scala (hunk 4 above)
Comment (zmerr) [reply metals/src/main/scala/scala/meta/internal/builds/ShellRunner.scala:204]: You are right. from pprint:

> the shell runner obtained java version as OpenJDK 64-Bit Server VM Homebrew (build 18.0.1.1+0, mixed mode, sharing)

Comment (zmerr) [reply metals/src/main/scala/scala/meta/internal/builds/ShellRunner.scala:204]: Hey, instead of going the `ShellRunner` path, do you think it would have been a better idea to simply do `System.getProperty("java.version”)` according to [this](https://stackoverflow.com/questions/5103121/how-to-find-the-jvm-version-from-a-program) ?

In my case, it is produces just  `18.0.1.1`

which does not require any extraction :)

File: metals/src/main/scala/scala/meta/internal/metals/JavaInteractiveSemanticdb.scala [hunk 7]
```diff
@@ -227,38 +231,56 @@ case class JdkVersion(
...
+      val properties = ConfigFactory.parseFile(
+        releaseFile.toFile,
+        ConfigParseOptions.defaults().setSyntax(ConfigSyntax.PROPERTIES)
+      )
+      try {
+        val version = properties
+          .getString("JAVA_VERSION")
+          .stripPrefix("\"")
+          .stripSuffix("\"")
+        //   pprint.log("version from releaseFile is "+ version)
```
Comment (tgodzik) [inline metals/src/main/scala/scala/meta/internal/metals/JavaInteractiveSemanticdb.scala:267]:
```suggestion
```

File: metals/src/main/scala/scala/meta/internal/metals/JavaInteractiveSemanticdb.scala [hunk 8]
```diff
@@ -227,38 +231,56 @@ case class JdkVersion(
...
+          .runSync(
+            List("java", "-version"),
+            javaHome,
+            redirectErrorOutput = true,
+            maybeJavaHome = maybeJavaHome.map(_.toString())
+          )
+          .flatMap { javaVersionResponse =>
+            "\\d+\\.\\d+\\.\\d+".r
+              .findFirstIn(javaVersionResponse)
+              .flatMap(JdkVersion.parse)
```
Comment (tgodzik) [inline metals/src/main/scala/scala/meta/internal/metals/JavaInteractiveSemanticdb.scala:249]:
```suggestion
        val sbOut = new StringBuilder()
        val exit = ShellRunner
          .runSync(
            List("java", "-version"),
            javaHome,
            redirectErrorOutput = true,
            processOut = s => {
              sbOut.append(s)
              sbOut.append(Properties.lineSeparator)
           },
            maybeJavaHome = maybeJavaHome.map(_.toString())
          )
           if (exit == 0){
             val javaVersionResponse = sbOut.toString
             "\\d+\\.\\d+\\.\\d+".r
              .findFirstIn(javaVersionResponse)
              .flatMap(JdkVersion.parse)
           } else {
             None
           }
```

Also, if you move it to a separate function we could write proper unit tests for it, which would be safer.

File: metals/src/main/scala/scala/meta/internal/builds/ShellRunner.scala [hunk 9]
```diff
@@ -130,3 +133,34 @@ class ShellRunner(
...
+      env,
+      Some(processOut),
+      Some(processErr),
+      propagateError
+    )
+
+    val scanner = new Scanner(ps.inputStream).useDelimiter("\\A")
+    if (scanner.hasNext)
+      Some(scanner.next)
+    else None
```
Comment (tgodzik) [inline metals/src/main/scala/scala/meta/internal/builds/ShellRunner.scala:163]:
```suggestion
   Await.result(ps.complete, ...)
```
I don't think it's working yet, is it?

**Review by tgodzik — CHANGES_REQUESTED** [review]

File: metals/src/main/scala/scala/meta/internal/builds/ShellRunner.scala (hunk 9 above)
Comment (zmerr) [reply metals/src/main/scala/scala/meta/internal/builds/ShellRunner.scala:163]: it is.

File: metals/src/main/scala/scala/meta/internal/metals/JavaInteractiveSemanticdb.scala (hunk 8 above)
Comment (zmerr) [reply metals/src/main/scala/scala/meta/internal/metals/JavaInteractiveSemanticdb.scala]: `runSync` is returning an `Option[String]`
So it is reading the `inputStream` of the `SystemProcess`
So if there is anything to be read from it, it returns that, otherwise, it returns `None`.
Then if the version regex cannot be detected in the String read from that, the output would again be None in the `fromShellRunner`. So this is delivering the same logic. Just added `JdkVersionSuite` to test and make sure.

File: metals/src/main/scala/scala/meta/internal/builds/ShellRunner.scala (hunk 9 above)
Comment (zmerr) [reply metals/src/main/scala/scala/meta/internal/builds/ShellRunner.scala:163]: added automated test in JdkVersionSuite.

File: metals/src/main/scala/scala/meta/internal/metals/JavaInteractiveSemanticdb.scala (hunk 8 above)
Comment (zmerr) [reply metals/src/main/scala/scala/meta/internal/metals/JavaInteractiveSemanticdb.scala]: If using             

```scala
processOut = s => {
              sbOut.append(s)
              sbOut.append(Properties.lineSeparator)
           }, 

```
is the correct way of getting the process output, I can change the runSync to reflect that. But then, it would be side-effecting, wouldn’t it?
perhapse, I can move the `StringBuilder` in the runSync itself, then return a tuple of (exitCode, maybeOutputString) from it.

Comment (zmerr) [reply metals/src/main/scala/scala/meta/internal/metals/JavaInteractiveSemanticdb.scala]: It’s just that the test is pretty flaky. Sometimes it passes and sometimes it succeeds. Is it due to the incorrect way of getting the process output? If so, I can use the previous logic in runSync which was returning a future. Then the name also perhaps can change.

File: metals/src/main/scala/scala/meta/internal/builds/ShellRunner.scala (hunk 9 above)
Comment (zmerr) [reply metals/src/main/scala/scala/meta/internal/builds/ShellRunner.scala:163]: the test is flaky. So I would return to the previous logic when it was returning the Future and awaiting its result.

File: metals/src/main/scala/scala/meta/internal/metals/JavaInteractiveSemanticdb.scala (hunk 8 above)
Comment (tgodzik) [reply metals/src/main/scala/scala/meta/internal/metals/JavaInteractiveSemanticdb.scala]: > But then, it would be side-effecting, wouldn’t it?

We are running a process, so this is side effecting anyway and also in tooling I wouldn't worry too much about it. We should keep the function consistent with the other ones.

File: metals/src/main/scala/scala/meta/internal/builds/ShellRunner.scala (hunk 9 above)
Comment (tgodzik) [reply metals/src/main/scala/scala/meta/internal/builds/ShellRunner.scala:163]: I just wonder what invocation is blocking in the function

Comment (zmerr) [reply metals/src/main/scala/scala/meta/internal/builds/ShellRunner.scala:163]: perhaps it sometimes reads the inputStream before the process completes and hence, there is nothing to be read from it.

File: metals/src/main/scala/scala/meta/internal/metals/JavaInteractiveSemanticdb.scala [hunk 10]
```diff
@@ -180,7 +181,8 @@ object JavaInteractiveSemanticdb {
   def create(
       javaHome: AbsolutePath,
       workspace: AbsolutePath,
-      buildTargets: BuildTargets
+      buildTargets: BuildTargets,
+      maybeJDKVersion: Option[JdkVersion]
```
Comment (dos65) [inline metals/src/main/scala/scala/meta/internal/metals/JavaInteractiveSemanticdb.scala:185]:
```suggestion
      jdkVersion: JdkVersion
```
I think this shouldn't be an option.
In `MetalsLanguageServer` we infer a version - it's it's none then there is no point in having `JavaInteractiveSemanticdb`

I noticed that only here there is a call of `JdkVersion.getJavaVersionFromJDK8FallBack` but probably it should be included into a method that infers version in `MetalsLanguageServer`

Comment (zmerr) [reply metals/src/main/scala/scala/meta/internal/metals/JavaInteractiveSemanticdb.scala:185]: is the fallback to `JdkVersion.getJavaVersionFromJDK8FallBack` useful also in `ProblemSolver`? because that is the other place in MetalsLanguageServer in whicch `maybeJdkVersion` is used.

Comment (dos65) [reply metals/src/main/scala/scala/meta/internal/metals/JavaInteractiveSemanticdb.scala:185]: > is the fallback to JdkVersion.getJavaVersionFromJDK8FallBack useful also in ProblemSolver

I've just realized that the right thing would be to remove `getJavaVersionFromJDK8FallBack`.
Anyway it won't be called because the version should be obtained from shell.

File: tests/unit/src/test/scala/tests/troubleshoot/ProblemResolverSuite.scala [hunk 11]
```diff
@@ -221,7 +222,8 @@ class ProblemResolverSuite extends FunSuite {
         new TestMtagsResolver,
         () => None,
         () => javaHome,
-        () => isTestExplorerProvider
+        () => isTestExplorerProvider,
+        JdkVersion.maybeJdkVersionFromJavaHome(Some(AbsolutePath(".")))
```
Comment (tgodzik) [inline tests/unit/src/test/scala/tests/troubleshoot/ProblemResolverSuite.scala:226]:
```suggestion
        JdkVersion.maybeJdkVersionFromJavaHome(Some(AbsolutePath(System.getProperty("java.home"))))
```

**Review by tgodzik — CHANGES_REQUESTED** [review]
Some small comments from me, otherwise looks good!

File: metals/src/main/scala/scala/meta/internal/metals/JavaInteractiveSemanticdb.scala [hunk 12]
```diff
@@ -227,40 +228,61 @@ case class JdkVersion(
...
   }
 
+//  def getJavaVersionFromJDK8FallBack(
+//      javaHome: AbsolutePath
+//  ): Option[JdkVersion] = {
+//    val rtJar = javaHome.resolve("jre").resolve("lib").resolve("rt.jar")
+//    if (rtJar.exists) Some(JdkVersion(8))
+//    else None
+//  }
+
```
Comment (tgodzik) [inline metals/src/main/scala/scala/meta/internal/metals/JavaInteractiveSemanticdb.scala:285]:
```suggestion
```
If it's no longer needed

**Review by tgodzik — CHANGES_REQUESTED** [review]
One last change and we should be able to merge it.
