### PR TITLE
Hopefully fix flaky test failure

### LINKED ISSUE #1182: PantsLspSuite.basic is flaky in CI
I'm seeing several CI jobs fail with
```
                SUCCESSX tests.pants.PantsLspSuite.basic 172528ms 
  tests.TestFailedException: failed assertion at /home/runner/work/metals/metals/tests/slow/src/test/scala/tests/pants/PantsLspSuite.scala:121
failed assertion at /home/runner/work/metals/metals/tests/mtest/src/main/scala/tests/DiffAssertions.scala:24
===========
=> Obtained
===========
    """|pants build needs to be re-imported
       |pants bloopInstall
       |pants build needs to be re-imported
       |pants bloopInstall


=======
=> Diff
=======
---∙
+++∙
@@ -2,3 +2,1 @@
 pants bloopInstall
-pants build needs to be re-imported
-pants bloopInstall
```

I think I know what's going on, will try to make this test run more reliably.

### PR DESCRIPTION
**Pull request by olafurpg**
Fixes #1182 

Previously, a race condition could cause Metals to prompt the user twice to import build changes. The duplicate prompt could cause some test suites like `PantsLspSuite` to become flaky. Now, we synchronize on the method that prompts the user to ensure that we finish writing the digest notification status in the H2 database before sending the next prompt.

I'm not sure if this fixes the flaky test failure, but I struggle to see why the Pants build digest should be any more flaky than the other build tool digests.

### CODE REVIEW

File: metals/src/main/scala/scala/meta/internal/metals/BloopInstall.scala [hunk 1]
```diff
@@ -135,10 +135,14 @@ final class BloopInstall(
     }
   }
 
+  // NOTE(olafur) there's a chance that we get two build change notifications in
+  // a very short period due to duplicate `didSave` and file watching
+  // notificiations. This method is synchronized to prevent asking the user
```
Comment (gabro) [inline metals/src/main/scala/scala/meta/internal/metals/BloopInstall.scala]:
```suggestion
  // notifications. This method is synchronized to prevent asking the user
```

Comment (olafurpg) [reply metals/src/main/scala/scala/meta/internal/metals/BloopInstall.scala]: Fixed, good excuse to run the tests again 😄 l

**Comment by olafurpg** [comment]
Let's give this a try and see if the issue is fixed.
