### PR TITLE
Treat self types as parent types in go to implementation context

### LINKED ISSUE #3808: Go to implementation doesn't work with self types
### Describe the bug

Add this test to ImplementationSuite:
```scala
check(
    "self-type",
    """|/a/src/main/scala/a/Main.scala
       |trait A { def a@@a: Unit }
       |trait B{
       | this : A =>
       |  override def <<aa>>: Unit = ()
       |}
       |""".stripMargin
  )
```

### Expected behavior

The test should work

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

v0.11.2

### Extra context or search terms

Part of the solution would be to analyse self parameter together with normal parents, however another issue seems to be that the parent methods do not show in overridenSymbols collection. This is probably an issue with the compiler itself. Working around it would require comparing signatures as a fallback, which would take us back to the complex logic before.

### PR DESCRIPTION
**Pull request by KacperFKorban**
closes #3808 

This PR is a result of joint work during the `Tooling Spree` of:
- @zainab-ali 
- @kasiaMarek 
- @KacperFKorban

### CODE REVIEW

**Comment by tgodzik** [comment]
Looks like you might need to run `sbt scalafixAll` for the tests to pass

**Review by tgodzik — CHANGES_REQUESTED** [review]
Other than running scalafix, looks good! Great work :tada:

**Comment by kasiaMarek** [comment]
We still need to handle self types for definitions in dependencies. This only covers the case of workspace definition.

**Comment by tgodzik** [comment]
Might be worth merging this anyway, since it's a fix for at least a subset. We should not close the issue for sure though yet

File: mtags/src/main/scala/scala/meta/internal/mtags/ScalaToplevelMtags.scala [hunk 1]
```diff
@@ -604,6 +606,48 @@ class ScalaToplevelMtags(
...
+      ident: Int,
+      isAfterNewLine: Boolean = false
+  ): (Int, Boolean) = {
+    forSeq(
+      List(
+        () =>
+          (curr.token == IDENTIFIER || curr.token == THIS) && curr.strVal != "extension",
+        () => curr.token == COLON,
+        { () =>
+          curr.token match {
```
Comment (tgodzik) [inline mtags/src/main/scala/scala/meta/internal/mtags/ScalaToplevelMtags.scala:619]: Should we check if this is followed by `=>` ?

File: metals/src/main/scala/scala/meta/internal/implementation/ImplementationProvider.scala [hunk 2]
```diff
@@ -545,9 +550,17 @@ object ImplementationProvider {
     def fromClassSignature(
         classSig: ClassSignature
     ): Seq[(String, ClassLocation)] = {
-      classSig.parents.collect { case t: TypeRef =>
-        t.symbol -> ClassLocation(symbol, filePath.map(_.toNIO))
+      // support `&`-types here?
```
Comment (tgodzik) [inline metals/src/main/scala/scala/meta/internal/implementation/ImplementationProvider.scala:553]: Should we have a follow up issue here?

**Review by tgodzik — APPROVED** [review]
Great work! LGTM

File: metals/src/main/scala/scala/meta/internal/implementation/ImplementationProvider.scala (hunk 2 above)
Comment (kasiaMarek) [reply metals/src/main/scala/scala/meta/internal/implementation/ImplementationProvider.scala]: Added the support for intersection types in https://github.com/scalameta/metals/pull/7170/commits/1da9dd788df99dbdddf3775d794059e10bf76f2f, otherwise it's only rebase.

**Review by tgodzik — APPROVED** [review]
LGTM!
