### PR TITLE
Fix: Handle InvalidSymbolException in StacktraceAnalyzer (#7974)

### LINKED ISSUE #7974: Could not find a line from stack traces
### Describe the bug

Below from @tpolecat:

- I'm working on the branch associated with [this PR](https://github.com/gemini-hlsw/lucuma-odb/pull/2116). 
- Do a symbol search for `SqlMapping` (it's in a library) and place a breakpoint at line 963.
- Debug the test `createObservation_GmosImaging`
- The debugger will halt at the breakpoint and behave in a reasonable way for maybe 10 seconds, then will crash and dump a logfile similar to the following.

--- 

error id: B29D28AE9312A0C2A45B4CFF3B1DF06B
### scala.meta.internal.mtags.IndexingExceptions$InvalidSymbolException: _empty_/*>#

Symbol: _empty_/*>#

#### Error stacktrace:

```
scala.meta.internal.mtags.OnDemandSymbolIndex.definitions(OnDemandSymbolIndex.scala:61)
	scala.meta.internal.metals.DestinationProvider.definition(DefinitionProvider.scala:457)
	scala.meta.internal.metals.DestinationProvider.fromSymbol(DefinitionProvider.scala:495)
	scala.meta.internal.metals.DestinationProvider.fromSymbol(DefinitionProvider.scala:538)
	scala.meta.internal.metals.DefinitionProvider.fromSymbol(DefinitionProvider.scala:181)
	scala.meta.internal.metals.StacktraceAnalyzer.findLocationForSymbol$1(StacktraceAnalyzer.scala:74)
	scala.meta.internal.metals.StacktraceAnalyzer.$anonfun$fileLocationFromLine$2(StacktraceAnalyzer.scala:79)
	scala.PartialFunction$Unlifted.applyOrElse(PartialFunction.scala:347)
	scala.collection.IterableOnceOps.collectFirst(IterableOnce.scala:1256)
	scala.collection.IterableOnceOps.collectFirst$(IterableOnce.scala:1248)
	scala.collection.AbstractIterable.collectFirst(Iterable.scala:935)
	scala.meta.internal.metals.StacktraceAnalyzer.$anonfun$fileLocationFromLine$1(StacktraceAnalyzer.scala:79)
	scala.Option.flatMap(Option.scala:283)
	scala.meta.internal.metals.StacktraceAnalyzer.fileLocationFromLine(StacktraceAnalyzer.scala:77)
	scala.meta.internal.metals.StacktraceAnalyzer.workspaceFileLocationFromLine(StacktraceAnalyzer.scala:66)
	scala.meta.internal.metals.debug.DebugProxy.$anonfun$modifyLocationInTests$3(DebugProxy.scala:316)
	scala.collection.Iterator$$anon$10.nextCur(Iterator.scala:594)
	scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:608)
	scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:600)
	scala.meta.internal.mtags.MtagsEnrichments$XtensionIteratorCollection.headOption(MtagsEnrichments.scala:32)
	scala.meta.internal.metals.debug.DebugProxy.$anonfun$modifyLocationInTests$1(DebugProxy.scala:320)
	scala.collection.StrictOptimizedIterableOps.map(StrictOptimizedIterableOps.scala:100)
	scala.collection.StrictOptimizedIterableOps.map$(StrictOptimizedIterableOps.scala:87)
	scala.collection.convert.JavaCollectionWrappers$JListWrapper.map(JavaCollectionWrappers.scala:138)
	scala.meta.internal.metals.debug.DebugProxy.modifyLocationInTests(DebugProxy.scala:308)
	scala.meta.internal.metals.debug.DebugProxy.$anonfun$handleServerMessage$1(DebugProxy.scala:284)
	scala.meta.internal.metals.debug.DebugProxy.$anonfun$handleServerMessage$1$adapted(DebugProxy.scala:241)
	scala.meta.internal.metals.debug.ServerAdapter.$anonfun$onReceived$1(ServerAdapter.scala:25)
	scala.meta.internal.metals.debug.MessageIdAdapter.$anonfun$listen$1(MessageIdAdapter.scala:57)
	org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:185)
	org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:97)
	scala.meta.internal.metals.debug.SocketEndpoint.listen(SocketEndpoint.scala:38)
	scala.meta.internal.metals.debug.MessageIdAdapter.listen(MessageIdAdapter.scala:47)
	scala.meta.internal.metals.debug.ServerAdapter.onReceived(ServerAdapter.scala:18)
	scala.meta.internal.metals.debug.DebugProxy.$anonfun$listenToServer$1(DebugProxy.scala:92)
	scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	scala.concurrent.Future$.$anonfun$apply$1(Future.scala:687)
	scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
	java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	java.base/java.lang.Thread.run(Thread.java:833)
```
#### Short summary: 

scala.meta.internal.mtags.IndexingExceptions$InvalidSymbolException: _empty_/*>#

### Expected behavior

_No response_

### Operating system

None

### Editor/Extension

None

### Version of Metals

v1.6.3

### Scala version/s

not-relevant

### Extra context or search terms

stavk trace error

### PR DESCRIPTION
**Pull request by krrish175-byte**
## Closing issue

closes #7974

### CODE REVIEW

File: metals/src/main/scala/scala/meta/internal/metals/StacktraceAnalyzer.scala [hunk 1]
```diff
@@ -80,6 +81,7 @@ class StacktraceAnalyzer(
     def findLocationForSymbol(s: String): Option[Location] = try {
       definitionProvider.fromSymbol(s, None).asScala.headOption
     } catch {
+      case _: IndexingExceptions.InvalidSymbolException => None
```
Comment (tgodzik) [inline metals/src/main/scala/scala/meta/internal/metals/StacktraceAnalyzer.scala]: This is already handled by the below

File: metals/src/main/scala/scala/meta/internal/metals/StacktraceAnalyzer.scala [hunk 2]
```diff
@@ -224,6 +224,12 @@ object StacktraceAnalyzer {
     val symbolPart =
       if (modulePos > -1) symbolIn.substring(modulePos + 1) else symbolIn
     val symbol = symbolPart.split('.').init.mkString("/")
+    
+    // Filter out invalid symbols that contain invalid characters or are empty
+    if (symbol.isEmpty || symbol.contains("/*") || symbol.contains("*/")) {
```
Comment (tgodzik) [inline metals/src/main/scala/scala/meta/internal/metals/StacktraceAnalyzer.scala]: This will help with not sending an invalid symbol, but we still don't know which line causes it. Ideally, we would check the reproduction, find the input that is producing the wrong symbol. Add unit tests in AnalyzeStacktraceLspSuite for it and fix the issue

Comment (tgodzik) [reply metals/src/main/scala/scala/meta/internal/metals/StacktraceAnalyzer.scala]: Also, I think we can reproduce it with naming something like 'def *> = ...' and put the breakpoint inside the method. 
`*>` should be escaped with backticks like:

image

Comment (tgodzik) [reply metals/src/main/scala/scala/meta/internal/metals/StacktraceAnalyzer.scala]: The logic for that seem to be in https://github.com/scalameta/scalameta/blob/88ce4e4b7be45a4019b12da9d9376092e23d0f87/scalameta/tokens/shared/src/main/scala/scala/meta/tokens/package.scala#L11 we can copy it or I think we can use the dependency's method from scala.meta.tokens.isIdentSymbolicNonBackquotedInfixOperator

**Review by tgodzik — APPROVED** [review]
LGTM!
