### PR TITLE
[Scala3] DocumentSymbols - use proper dialect for tree rendering

### LINKED ISSUE #2551: [Scala 3] Document outline not working for union types
**Describe the bug**

It seems that for example in `t.body.syntax` `.syntax` is using wrong dialect and throwing an exception in some case like union types

```
java.util.concurrent.CompletionException: java.lang.UnsupportedOperationException: Scala212 doesn't support and types
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:704)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1(CancelTokens.scala:40)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1$adapted(CancelTokens.scala:38)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.UnsupportedOperationException: Scala212 doesn't support and types
	at scala.meta.internal.prettyprinters.TreeSyntax$SyntaxInstances.$anonfun$syntaxTree$1(TreeSyntax.scala:692)
	at scala.meta.prettyprinters.Syntax$$anon$1.apply(Syntax.scala:9)
	at scala.meta.internal.prettyprinters.TreeSyntax$.$anonfun$apply$1(TreeSyntax.scala:1281)
	at scala.meta.prettyprinters.Syntax$$anon$1.apply(Syntax.scala:9)
	at scala.meta.prettyprinters.Api$XtensionSyntax.syntax(Api.scala:11)
	at scala.meta.internal.parsing.DocumentSymbolProvider$SymbolTraverser.apply(DocumentSymbolProvider.scala:243)
	at scala.meta.transversers.SimpleTraverser.$anonfun$apply$1(SimpleTraverser.scala:5)
	at scala.meta.transversers.SimpleTraverser.$anonfun$apply$1$adapted(SimpleTraverser.scala:5)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at scala.meta.transversers.SimpleTraverser.apply(SimpleTraverser.scala:5)
	at scala.meta.internal.parsing.DocumentSymbolProvider$SymbolTraverser.continue$1(DocumentSymbolProvider.scala:101)
	at scala.meta.internal.parsing.DocumentSymbolProvider$SymbolTraverser.apply(DocumentSymbolProvider.scala:122)
	at scala.meta.transversers.SimpleTraverser.$anonfun$apply$1(SimpleTraverser.scala:5)
	at scala.meta.transversers.SimpleTraverser.$anonfun$apply$1$adapted(SimpleTraverser.scala:5)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at scala.meta.transversers.SimpleTraverser.apply(SimpleTraverser.scala:5)
	at scala.meta.internal.parsing.DocumentSymbolProvider$SymbolTraverser.continue$1(DocumentSymbolProvider.scala:101)
	at scala.meta.internal.parsing.DocumentSymbolProvider$SymbolTraverser.newOwner$1(DocumentSymbolProvider.scala:105)
	at scala.meta.internal.parsing.DocumentSymbolProvider$SymbolTraverser.apply(DocumentSymbolProvider.scala:177)
	at scala.meta.transversers.SimpleTraverser.$anonfun$apply$1(SimpleTraverser.scala:5)
	at scala.meta.transversers.SimpleTraverser.$anonfun$apply$1$adapted(SimpleTraverser.scala:5)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at scala.meta.transversers.SimpleTraverser.apply(SimpleTraverser.scala:5)
	at scala.meta.internal.parsing.DocumentSymbolProvider$SymbolTraverser.continue$1(DocumentSymbolProvider.scala:101)
	at scala.meta.internal.parsing.DocumentSymbolProvider$SymbolTraverser.apply(DocumentSymbolProvider.scala:122)
	at scala.meta.internal.parsing.DocumentSymbolProvider$SymbolTraverser.symbols(DocumentSymbolProvider.scala:54)
	at scala.meta.internal.parsing.DocumentSymbolProvider.$anonfun$documentSymbols$1(DocumentSymbolProvider.scala:33)
	at scala.Option.map(Option.scala:230)
	at scala.meta.internal.parsing.DocumentSymbolProvider.documentSymbols(DocumentSymbolProvider.scala:32)
	at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$documentSymbol$1(MetalsLanguageServer.scala:1306)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$apply$2(CancelTokens.scala:26)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	... 4 more
```

**To Reproduce**

Steps to reproduce the behavior, try to checkout the project and open:

https://github.com/scala/scala3-example-project/blob/master/src/main/scala/UnionTypes.scala

**Expected behavior**

Document outline is shown.

**Search terms**

document outline scala3

### PR DESCRIPTION
**Pull request by dos65**
Fixes #2551

### CODE REVIEW

File: tests/slow/src/test/scala/tests/feature/DocumentSymbolCrossLspSuite.scala [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+            |}
+            |/a/src/main/scala/a/Main.scala
+            |type X = String | Int
+            |""".stripMargin
+      )
+      _ <- server.didOpen("a/src/main/scala/a/Main.scala")
+      symbols <- server.documentSymbols("a/src/main/scala/a/Main.scala")
+      _ = assertDiffEqual(
+        symbols.trim,
+        "/*X(TypeParameter):1*/type X = String | Int"
```
Comment (tgodzik) [inline tests/slow/src/test/scala/tests/feature/DocumentSymbolCrossLspSuite.scala:26]: We could add it to `input3` and just have it tested there. I don't think there is a need for slow test here.

**Review by tgodzik — CHANGES_REQUESTED** [review]

**Review by tgodzik — APPROVED** [review]
LGTM!
