### PR TITLE
[Scala3] Fix autoimport with prefixes

### LINKED ISSUE #3478: SymbolPrefixes are messing up other util packages
### Describe the bug

When you have code that is in another util package and there is a conflicting import, the symbol prefix for `java/util` screws up your import.

You can reproduce this with the following snippet:
```scala
// using scala 3.1.0
// using lib org.scala-lang::scala3-compiler:3.1.0

import dotty.tools.dotc.interfaces.SourceFile

@main def Main: Unit =
// <-- try to complete `SourceFile` here from the util package
```

You'll end up with the following:

```scala
// using scala 3.1.0
// using lib org.scala-lang::scala3-compiler:3.1.0

import dotty.tools.dotc.interfaces.SourceFile
import dotty.tools.dotc.{util => ju}

@main def Main: Unit =
  ju.SourceFile
```

### Expected behavior

I'd expect the fully qualified name just be inserted in place or something like `util.SourceFile`

```scala
// using scala 3.1.0
// using lib org.scala-lang::scala3-compiler:3.1.0

import dotty.tools.dotc.interfaces.SourceFile
import dotty.tools.dotc.{util => ju}

@main def Main: Unit =
  dotty.tools.dotc.util.SourceFile
```

### Operating system

_No response_

### Editor/Extension

_No response_

### Version of Metals

0.10.9+295-ad8c7778-SNAPSHOT

### Extra context or search terms

My guess is the issue is right here:

https://github.com/scalameta/metals/blob/ad8c7778e75a48267d3723efe36ef0eccf4c6a6b/mtags/src/main/scala-3/scala/meta/internal/pc/AutoImports.scala#L61-L66

I think in this case `util` is the simple name and the keys here are simple names so it incorrectly thinks the `util -> ju` entry matching when it shouldn't.

### PR DESCRIPTION
**Pull request by dos65**
Fixes #3478

### CODE REVIEW

File: mtags/src/main/scala-3/scala/meta/internal/pc/AutoImports.scala [hunk 1]
```diff
@@ -135,7 +138,7 @@ object AutoImports:
         case IndexedContext.Result.Conflict =>
           val owner = symbol.owner
           val simpleName = owner.name.toSimpleName
```
Comment (tgodzik) [inline mtags/src/main/scala-3/scala/meta/internal/pc/AutoImports.scala:140]:
```suggestion
```
seems to be unsued now

**Review by tgodzik — APPROVED** [review]
Great work! Just a small comment, but it is already mergable as is.

**Review by ckipp01 — APPROVED** [review]
Nice! Thanks for fixing this @dos65! LGTM!
