### PR TITLE
Correct dialect for standalone scripts.

### LINKED ISSUE #2430: Metals throws erorrs when Mill `build.sc` file has top level definitions.
**Describe the bug**

When you open a `build.sc` in a valid Mill workspace that has top level definitions and look at the logs, you'll find this:

```
SEVERE: file%3A%2F%2F%2FUsers%2Fckipp%2FDocuments%2Fscala-workspace%2Fbsp-test%2Fbuild.sc:3: error: expected class or object definition val
val test = 3
^
file%3A%2F%2F%2FUsers%2Fckipp%2FDocuments%2Fscala-workspace%2Fbsp-test%2Fbuild.sc:3: error: expected class or object definition val
val test = 3
^
        at scala.meta.internal.parsers.Reporter.syntaxError(Reporter.scala:16)
        at scala.meta.internal.parsers.Reporter.syntaxError$(Reporter.scala:16)
        at scala.meta.internal.parsers.Reporter$$anon$1.syntaxError(Reporter.scala:22)
        at scala.meta.internal.parsers.Reporter.syntaxError(Reporter.scala:17)
        at scala.meta.internal.parsers.Reporter.syntaxError$(Reporter.scala:17)
        at scala.meta.internal.parsers.Reporter$$anon$1.syntaxError(Reporter.scala:22)
        at scala.meta.internal.parsers.ScalametaParser.statSeq(ScalametaParser.scala:4655)
        at scala.meta.internal.parsers.ScalametaParser.topStatSeq(ScalametaParser.scala:4662)
        at scala.meta.internal.parsers.ScalametaParser.$anonfun$batchSource$1(ScalametaParser.scala:4876)
        at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:704)
        at scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:720)
        at scala.meta.internal.parsers.ScalametaParser.batchSource(ScalametaParser.scala:4842)
        at scala.meta.internal.parsers.ScalametaParser.$anonfun$source$1(ScalametaParser.scala:4825)
        at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:704)
        at scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:720)
        at scala.meta.internal.parsers.ScalametaParser.source(ScalametaParser.scala:4824)
        at scala.meta.internal.parsers.ScalametaParser.entrypointSource(ScalametaParser.scala:4830)
        at scala.meta.internal.parsers.ScalametaParser.$anonfun$parseSource$2(ScalametaParser.scala:142)
        at scala.meta.internal.parsers.ScalametaParser.parseRule(ScalametaParser.scala:52)
        at scala.meta.internal.parsers.ScalametaParser.parseSource(ScalametaParser.scala:142)
        at scala.meta.parsers.Parse$.$anonfun$parseSource$1(Parse.scala:29)
        at scala.meta.internal.parsers.ScalametaParser$$anon$259.apply(ScalametaParser.scala:4887)
        at scala.meta.parsers.Api$XtensionParseDialectInput.parse(Api.scala:25)
        at scala.meta.internal.semanticdb.scalac.ParseOps$XtensionCompilationUnitSource.toSource(ParseOps.scala:11)
        at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument.toTextDocument(TextDocumentOps.scala:196)
        at scala.meta.internal.pc.SemanticdbTextDocumentProvider.textDocument(SemanticdbTextDocumentProvider.scala:34)
```

**To Reproduce**

1. Open any Mill build with top level definitions in the `build.sc` file. (You can use [Ammonite](https://github.com/lihaoyi/Ammonite) as an example.
2. See error in the logs

**Expected behavior**

I'd expect not to see errors in this situation.

- Metals version: 0.9.10

**Search terms**

Mill top level definitions

### PR DESCRIPTION
**Pull request by ckipp01**
Ensure that we have the correct dialect when creating semanticdb for
standalone .sc files. This was causing exceptions to be thrown for .sc
files since it wasn't recognizing the top level definitions.

Fixes #2430

### CODE REVIEW

File: metals/src/main/scala/scala/meta/internal/metals/InteractiveSemanticdbs.scala [hunk 1]
```diff
@@ -55,7 +55,7 @@ final class InteractiveSemanticdbs(
   override def textDocument(source: AbsolutePath): TextDocumentLookup = {
 
     def shouldTryCalculateInteractiveSemanticdb = {
-      source.isDependencySource(workspace) || source.isSbt || buildTargets
```
Comment (ckipp01) [inline metals/src/main/scala/scala/meta/internal/metals/InteractiveSemanticdbs.scala:58]: Right underneath this check we have `!source.isScalaFilename` and part of the `isScalaFilename` is the `isSbt` check. So this is redundant.

**Review by tgodzik — APPROVED** [review]
LGTM!

File: metals/src/main/scala/scala/meta/internal/metals/InteractiveSemanticdbs.scala (hunk 1 above)
Comment (ckipp01) [reply metals/src/main/scala/scala/meta/internal/metals/InteractiveSemanticdbs.scala:58]: I don't get this. It's failed twice in a row now in the sbt test... so it makes me think it's related to this, but I don't get why this would be needed as well here.

Comment (tgodzik) [reply metals/src/main/scala/scala/meta/internal/metals/InteractiveSemanticdbs.scala]: It might be do to the fact that SBT files are in a build target and we don't calculate semanticdb for those. 🤔

Comment (ckipp01) [reply metals/src/main/scala/scala/meta/internal/metals/InteractiveSemanticdbs.scala]: I'm not sure. I added the `source.isSbt` back in and now everything is happy again.
