### PR TITLE
Handle sbt pluginsDirectory as symbolic link

### LINKED ISSUE #416: Build import fails when sbt global plugins directory is a symbolic link
I'm attempting to use Metals with the latest version of Atom (1.33) however when I attempt to import a project I get the following error in the log:

```
warn  Unable to automatically connect to build server.
error Unexpected error initializing server
java.nio.file.FileAlreadyExistsException: /home/keir/.sbt/1.0/plugins
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:88)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
	at java.nio.file.Files.createDirectory(Files.java:674)
	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
	at java.nio.file.Files.createDirectories(Files.java:727)
	at scala.meta.internal.metals.BloopInstall$.scala$meta$internal$metals$BloopInstall$$writeGlobalPluginFile(BloopInstall.scala:191)
	at scala.meta.internal.metals.BloopInstall.runUnconditionally(BloopInstall.scala:53)
	at scala.meta.internal.metals.BloopInstall.$anonfun$runIfApproved$2(BloopInstall.scala:130)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

### PR DESCRIPTION
**Pull request by gabro**
Fixes #416 

@olafurpg do you have an idea on how to test this automatically?

### CODE REVIEW

File: metals/src/main/scala/scala/meta/internal/metals/BloopInstall.scala [hunk 1]
```diff
@@ -215,7 +215,12 @@ object BloopInstall {
     val plugins =
       if (sbt.version.startsWith("0.13")) pluginsDirectory("0.13")
       else pluginsDirectory("1.0")
-    Files.createDirectories(plugins.toNIO)
+    val isSymlink = Files.isSymbolicLink(plugins.toNIO) &&
+      Files.isDirectory(Files.readSymbolicLink(plugins.toNIO))
+    // createDirectories checks whether the directory exists, but it doesn't follow symlinks
+    if (!isSymlink) {
+      Files.createDirectories(plugins.toNIO)
```
Comment (olafurpg) [inline metals/src/main/scala/scala/meta/internal/metals/BloopInstall.scala]: Can we create an extension method `AbsolutePath.createDirectories()` in `MetalsEnrichments` that performs this check? It would make it easier to reuse in the future.

**Comment by olafurpg** [comment]
I don't think it's necessary to test the case when `~/.sbt/1.0/plugins` is a symlink.

**Comment by gabro** [comment]
@olafurpg ok I've reimplemented a symlink-aware version of `createDirectories`

File: metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala [hunk 2]
```diff
@@ -224,40 +224,12 @@ object MetalsEnrichments extends DecorateAsJava with DecorateAsScala {
...
-              // isDirectory follows symlinks but the check inside `createDirectory` doesn't
-              if (!Files.isDirectory(dirPath)) {
-                Files.createDirectory(dirPath)
-              }
-              dirPath
-          }
-        // we couldn't find a parent
-        case None => throw new FileSystemException(path.toString)
+    def createDirectories(): Unit = {
+      if (!Files.isSymbolicLink(path.toNIO)) {
```
Comment (gabro) [inline metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala]: If `path` is a symlink to a regular file, this will silently fail and do nothing.

I would use

```scala
if (!Files.isDirectory(path.toNIO)) {
  Files.createDirectories(path.toNIO)
}
```

instead

File: metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala [hunk 3]
```diff
@@ -224,40 +224,12 @@ object MetalsEnrichments extends DecorateAsJava with DecorateAsScala {
...
-              // This check guards against symlinks
-              // isDirectory follows symlinks but the check inside `createDirectory` doesn't
-              if (!Files.isDirectory(dirPath)) {
-                Files.createDirectory(dirPath)
-              }
-              dirPath
-          }
-        // we couldn't find a parent
-        case None => throw new FileSystemException(path.toString)
+    def createDirectories(): Unit = {
```
Comment (gabro) [inline metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala]: I would return the `AbsolutePath` for consistency with the Java API.

File: metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala (hunk 2 above)
Comment (gabro) [reply metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala]: To elaborate, using `isDirectory` in that scenario will allow `createDirectories` to fail with a meaningful error, instead of silently ignoring the issue.

File: metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala (hunk 3 above)
Comment (olafurpg) [reply metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala]: Done

File: metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala (hunk 2 above)
Comment (olafurpg) [reply metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala]: Good catch! I updated the logic to run `createDirectories` on the dealiased path. If the symlink points to a file it should fail with the correct message in that case.

**Comment by olafurpg** [comment]
Ignoring Window flaky tests again.
