### PR TITLE
Compute 'Import missing symbol' code actions for all diagnostics in range

### LINKED ISSUE #1283: Import-missing-symbol doesn't seem to work with coc.nvim
**Describe the bug**

Using coc.nvim + coc-metals with metals `0.7.6+727-60d73c7e-SNAPSHOT`.

The import missing symbol action works as expected in VS Code, but doesn't show up in the code actions list in vim. When I request code actions for the line containing the error, I get an empty list.

**To Reproduce**
1. Write `val x = Future(1)` in a Scala file, without adding an import for `scala.concurrent.Future`.
2. The line is marked with a compilation error. `Future` is underlined. Hovering shows `[bloop] [E] not found: value Future`
3. Type `:CocAction<Enter>`
4. An empty list of code actions is shown.

**Expected behavior**

Two items in the code actions list:
* `Import 'Future' from package 'scala.concurrent'
* `Import 'Future' from package 'java.util.concurrent'

**Screenshots**

The code containing a missing symbol:

Screenshot 2020-01-10 at 16 57 18

The empty actions list:

Screenshot 2020-01-10 at 17 00 57

**Installation:**
- Operating system: macOS
- Editor: neovim + coc.nvim + coc-metals
- Metals version: v0.7.6+727-60d73c7e-SNAPSHOT

**Additional context**
I rebuilt metals locally so I could log the code actions request that coc.nvim is sending. It looks like this:

<details>
<summary>Code actions request from coc.nvim</summary>
<pre>
<code>
CodeActionParams [
  textDocument = TextDocumentIdentifier [
    uri = "file:///Users/chris/code/pbdirect/src/main/scala/pbdirect/PBScalarValueWriter.scala"
  ]
  range = Range [
    start = Position [
      line = 13
      character = 0
    ]
    end = Position [
      line = 14
      character = 0
    ]
  ]
  context = CodeActionContext [
    diagnostics = ArrayList (
      Diagnostic [
        range = Range [
          start = Position [
            line = 13
            character = 10
          ]
          end = Position [
            line = 13
            character = 16
          ]
        ]
        severity = Error
        code = null
        source = "bloop"
        message = "not found: value Future"
        relatedInformation = null
      ]
    )
    only = null
  ]
]
</code>
</pre>
</details>

Note that the missing symbol is on line 13 (zero-indexed) of the file.

**Search terms**
vim coc.nvim import missing symbol

### PR DESCRIPTION
**Pull request by gabro**
Fixes #1283 

Previously we computed the 'Import missing symbol' code action for a single diagnostic under the cursor. Now we compute all diagnostics whose range overlap with the code action range sent by the client. This allows computing auto-imports for all diagnostics in a range at once.

This is especially relevant for clients like Vim, which - by default - sends a code action request for the entire line.

Here's how it looks like in VS Code:

### CODE REVIEW

File: metals/src/main/scala/scala/meta/internal/metals/codeactions/ImportMissingSymbol.scala [hunk 1]
```diff
@@ -46,7 +46,7 @@ class ImportMissingSymbol(compilers: Compilers) extends CodeAction {
     Future
       .sequence(params.getContext().getDiagnostics().asScala.collect {
         case d @ ScalacDiagnostic.SymbolNotFound(name)
-            if d.getRange().encloses(params.getRange().getEnd()) =>
+            if params.getRange().overlapsWith(d.getRange()) =>
```
Comment (gabro) [inline metals/src/main/scala/scala/meta/internal/metals/codeactions/ImportMissingSymbol.scala]: we cannot use `encloses` because sometimes the code action range is smaller than the diagnostic range, for example:

```scala
val x = Future.successful(2)
//      ^^^^^^  diagnostic range
//       <-->   code action range
```

or even partially overlapping

```scala
val x = Future.successful(2)
//      ^^^^^^  diagnostic range
//         <------->   code action range
```

File: tests/unit/src/main/scala/tests/TestingServer.scala [hunk 2]
```diff
@@ -584,6 +584,39 @@ final class TestingServer(
...
+    if (startOffset > endOffset)
+      sys.error(s"invalid range, >> must come after <<\n$original")
+    val text =
+      original
+        .replaceAllLiterally("<<", replaceWith)
+        .replaceAllLiterally(">>", replaceWith)
+    val input = m.Input.String(text)
+    val path = root.resolve(filename)
+    path.touch()
+    val pos = m.Position.Range(input, startOffset, endOffset - "<<>>".length())
```
Comment (gabro) [inline tests/unit/src/main/scala/tests/TestingServer.scala]: the `endOffset` is adjusted to account for the removal of the range markers

**Comment by cb372** [comment]
Nice! Thanks for the, ahem, quick fix.

**Comment by cb372** [comment]
@ckipp01 I just tried it in vim and it works like a charm for me.

Screenshot 2020-01-11 at 16 36 14

**Comment by ckipp01** [comment]
Hmmm, ignore my comment I guess. Something is all screwed up with my local build. I can't even get it to work with VS Code either, and I'm getting a bunch of excpetions.

**Comment by gabro** [comment]
FWIW I can't get it work in nvim either (I haven't tried vim yet), but it works in VSCode...

**Comment by gabro** [comment]
Scratch that, I was using an old version.

I can confirm I got this working on nvim with coc-metals too.

File: metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala [hunk 3]
```diff
@@ -507,13 +507,13 @@ class MetalsLanguageServer(
...
-        capabilities.setCodeActionProvider(true)
-      } else {
         capabilities.setCodeActionProvider(
           new CodeActionOptions(
             List(CodeActionKind.QuickFix, CodeActionKind.Refactor).asJava
           )
         )
+      } else {
+        capabilities.setCodeActionProvider(true)
       }
```
Comment (gabro) [inline metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala]: I got this wrong in #1251. When the client supports code action literals we can send the `CodeActionOptions` version, otherwise we just send `true`

File: tests/unit/src/main/scala/tests/TestingServer.scala (hunk 2 above)
Comment (tgodzik) [reply tests/unit/src/main/scala/tests/TestingServer.scala]: A lot of this code seem duplicate to what we already have. Would it be possible to reuse the methods that we use for changing to the position in params?

Comment (gabro) [reply tests/unit/src/main/scala/tests/TestingServer.scala]: @tgodzik which method? Anyway, sure, I'll open a tech debt issue.
