### PR TITLE
Fix #4772: stop watching generated files to avoid compilation loop

### LINKED ISSUE #4772: [sbt server] Infinite compilation loop
### Describe the bug

Reproduction steps:
1. Create an sbt project
2. Add a source generator in the `build.sbt`:
```scala
Compile / sourceGenerators += Def.task {
  val content = 
    s"""|object Foo
        |""".stripMargin
  val file = target.value / "generated" / "src" / "main" / "scala" / "Foo.scala"
  IO.write(file, content)
  List(file)
}
```
3. Import the project in Metals using sbt as the build server using `Metals: switch build server`

The problem here is that the `buildTarget/scalaMainClasses` request triggers the source generation (and a compilation). Metals realize that the generated source changed and so it send a new `buildTarget/compile` request and a new `buildTarget/scalaMainClasses` request. The loop never ends.

### Expected behavior

Metals should not loop. It should run `buildTarget/compile` and `buildTarget/scalaMainClasses` only once.

To fix this issue, I think we can stop watching the generated sources.

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

v0.11.9

### Extra context or search terms

_No response_

### PR DESCRIPTION
**Pull request by adpi2**

### CODE REVIEW

**Review by ckipp01 — APPROVED** [review]
Awesome, makes sense. Thanks a lot for the quick fix @adpi2!

File: tests/slow/src/test/scala/tests/sbt/SbtServerSuite.scala [hunk 1]
```diff
@@ -240,4 +247,30 @@ class SbtServerSuite
...
+          |  IO.write(file, content)
+          |  Seq(file)
+          |}
+          |""".stripMargin
+    for {
+      _ <- initialize(layout)
+    } yield {
+      // Sleep 5s: that should be enough to see the compilation looping
+      // more than once
+      Thread.sleep(5000)
```
Comment (tgodzik) [inline tests/slow/src/test/scala/tests/sbt/SbtServerSuite.scala:270]: It would be awesome if we could work around having to wait 5 seconds, but not sure how to do it currently. We could potenatially run `didSave` on an additional file manually and see how many files are recompiled.

But if there is no better way that's fine as it is.

**Review by tgodzik — APPROVED** [review]
Looks good, just one comment, but feel free to ignore if it's not possible to change.

File: tests/slow/src/test/scala/tests/sbt/SbtServerSuite.scala (hunk 1 above)
Comment (adpi2) [reply tests/slow/src/test/scala/tests/sbt/SbtServerSuite.scala]: If I force the first compilation, then I think I can safely reduce the sleep to 100ms.
