### PR TITLE
fix(hover): allow hover on whitespace inside backtick identifiers

### LINKED ISSUE #7581: Hover over space inside backticked identifier doesn't work
### Describe the bug

I'm not sure whether this is something that matters in practice. Even in DSL contexts, I'm struggling to think of a case where multiple consecutive spaces would occur in a single identifier. I came up with this while trying to reverse engineer some failure that was reported to me, but it later transpired this was not the root cause.

Nonetheless, here's a sample failing test:

```diff
diff --git a/tests/cross/src/test/scala/tests/hover/HoverDefnSuite.scala b/tests/cross/src/test/scala/tests/hover/HoverDefnSuite.scala
index cc78de43532..085e0737e2c 100644
--- a/tests/cross/src/test/scala/tests/hover/HoverDefnSuite.scala
+++ b/tests/cross/src/test/scala/tests/hover/HoverDefnSuite.scala
@@ -277,4 +277,14 @@ class HoverDefnSuite extends BaseHoverSuite {
        |""".stripMargin,
     "val foo: Int".hover
   )
+
+  check(
+    "backticked",
+    """|object A {
+       |
+       |  <<val `foo @@ bar`: Int = 123>>
+       |}
+       |""".stripMargin,
+    "val `foo  bar` = 123".hover
+  )
 }
```

Instead of showing the definition of `foo  bar`, metals shows nothing. If there's one less space (so `foo bar`), the problem doesn't occur because either one of `foo@@ bar` or `foo @@bar` registers as non-whitespace hover.

Fix is probably similar to https://github.com/scalameta/metals/pull/7119

### Expected behavior

Show the definition as in the test case.

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

1.6.0

### Scala version/s

2.13.16

### Extra context or search terms

_No response_

### PR DESCRIPTION
**Pull request by warcholjakub**
# Fixes #7581
## Problem
Previously, Metals did not provide hover information when the cursor was placed on whitespace inside a backtick identifier, such as `foo  bar`. This was due to an early return in the hover logic that checked whether the character was whitespace and whether it was preceded by whitespace or a delimiter.
```scala
def hover(): Option[HoverSignature] = params match {
    case range: RangeParams =>
      range.trimWhitespaceInRange.flatMap(hoverOffset)
    case _ if params.isWhitespace && params.prevIsWhitespaceOrDelimeter => // `foo @@ bar` met both conditions
      None
    case _ => hoverOffset(params)
  }
```
## Solution
This PR introduces a new method, `isWithinBackticks`. This method efficiently checks whether the cursor is currently on whitespace that is inside a backtick identifier, by searching for backtick characters within the current line and ensuring the cursor is between them. The hover logic is updated to allow hover requests on whitespace only if isWithinBackticks returns true, thus enabling hover for backtick identifiers with spaces while still skipping hover on regular whitespace between tokens.
## Performance Considerations
I am aware that any additional string scanning could introduce performance overhead, especially with very long lines. I have benchmarked this implementation and did not observe any significant overhead in practical scenarios, even with long lines. However, I am open to suggestions for further optimization or alternative approaches.

### CODE REVIEW

File: mtags/src/main/scala-2/scala/meta/internal/mtags/MtagsEnrichments.scala [hunk 1]
```diff
@@ -64,6 +64,25 @@ trait MtagsEnrichments extends ScalametaCommonEnrichments {
...
+      if (offset < 0 || offset >= text.length) return false
+      if (!text.charAt(offset).isWhitespace) return false
+
+      val lineStart = text.lastIndexOf('\n', offset) + 1
+      val lineEnd = text.indexOf('\n', offset) match {
+        case -1 => text.length
+        case end => end
+      }
+
+      val beforeBacktick = text.lastIndexBetween('`', lineStart, offset - 1)
```
Comment (tgodzik) [inline mtags/src/main/scala-2/scala/meta/internal/mtags/MtagsEnrichments.scala:81]: Does this handle the case where you have two backticked values such as:
```
val a = `my backticked value` + @@`my backticked value`
```
?

Comment (warcholjakub) [reply mtags/src/main/scala-2/scala/meta/internal/mtags/MtagsEnrichments.scala:81]: No, it doesn't. It was intentional, because I was worried about performance. False positives are I think harmless in this situation, so I decided to settle for this compromise. However, if performance turns out not to be an issue, I can update the implementation to handle this edge case more precisely.

Comment (tgodzik) [reply mtags/src/main/scala-2/scala/meta/internal/mtags/MtagsEnrichments.scala:81]: Maybe this should be fine yeah. Let's merge it and see if anyone reports problems.
