### PR TITLE
Fix error for remote debugging when missing build target

### LINKED ISSUE #2724: 2021.04.15 10:36:06 WARN  Could not find java sources in None. Java symbols will not be available.
**Describe the bug**

I cant go to java sources

**To Reproduce**

**Expected behavior**

**Screenshots**

**Installation:**

- Operating system: macOS/Windows/Linux
- Editor: Visual Studio Code/Atom/Vim/Sublime/Emacs
- Metals version: v0.10.1

**Additional context**

**Search terms**

### LINKED ISSUE #2766: Remote debugging requires buildTarget/misleading error
This took me a while to figure out by myself, so making a note to help others.
scala 2.12.13
vscode metals extension: v1.10.4

**Repro:**
I have imported a large gradle project with subprojects and attempted remote debugging session after launching my app with `-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=9998` 

launch.json:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "scala",
            "request": "attach",
            "name": "attach 127.0.0.1:9998",
            "hostName": "127.0.0.1",
            "port": 9998
        }
    ]
}
```
And launching the debugger gets me:

[Error - 9:11:16 AM] Request workspace/executeCommand failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.util.NoSuchElementException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:661)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646)
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:686)
	at java.util.concurrent.CompletableFuture.thenAcceptAsync(CompletableFuture.java:2014)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.thenAccept(FutureConvertersImpl.scala:37)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:279)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.NoSuchElementException
	at scala.meta.internal.metals.debug.DebugProvider.resolveAttachRemoteParams(DebugProvider.scala:407)
	at scala.meta.internal.metals.MetalsLanguageServer.executeCommand(MetalsLanguageServer.scala:1627)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	... 9 more

It turns out, that the problem for me is the launch.json does not contain a buildTarget, i.e.
`            "buildTarget": "my_subproject",`

but the error message doesn't say much about it. Either the error message should be more explanatory or possibly the requirement for 'buildTarget' may be removed if feasible.

### PR DESCRIPTION
**Pull request by Giggiux**
This PR should close #2766  .
It was added a simple message when trying to attach a debugging session without a buildTarget.
Previously it just threw a `NoSuchElementException` error visible in the metals.log, without any other information.

The draft of the new error message is 
> "Debugger configuration is missing 'buildTarget' param."

### CODE REVIEW

File: metals/src/main/scala/scala/meta/internal/metals/debug/DebugProvider.scala [hunk 1]
```diff
@@ -440,6 +443,10 @@ class DebugProvider(
       languageClient.showMessage(
         Messages.errorMessageParams(e.getMessage())
       )
+    case _: ju.NoSuchElementException =>
```
Comment (tgodzik) [inline metals/src/main/scala/scala/meta/internal/metals/debug/DebugProvider.scala:446]: Could we add ` BuildTargetUndefined` exception just in case? and throw that in 407?

**Review by tgodzik — CHANGES_REQUESTED** [review]
Thanks for the contribution! One small nitpick from me. Also, I think the actual issue is https://github.com/scalameta/metals/issues/2766

File: metals/src/main/scala/scala/meta/internal/metals/debug/DebugProvider.scala (hunk 1 above)
Comment (Giggiux) [reply metals/src/main/scala/scala/meta/internal/metals/debug/DebugProvider.scala:446]: Sure! I'll commit this right away, and you're right about the issue, I fixed it! :D

**Review by tgodzik — APPROVED** [review]
