### PR TITLE
correct handling of end marker relocation on extract member

### LINKED ISSUE #3762: "Extract class to file" refactoring leaves behind end marker
### Describe the bug

Scala 3.1.1, Metals 0.11.2+86-4d583c7c-SNAPSHOT

_I'm having a de ja vu, I think I've reported this before..._

1. Be me
2. Have a file like this:
```scala 
class Test:
  def hello = ???
end Test

class Bla:
  def hello = ???
end Bla
```

3. Run "Extract class Bla to file Bla.scala"
4. Class is extracted okay, but the `end Bla` line remains in the main file

### Expected behavior

Class is extracted cleanly, along with its end marker

### Operating system

macOS

### Editor/Extension

Nvim (nvim-metals)

### Version of Metals

0.11.2+86-4d583c7c-SNAPSHOT

### Extra context or search terms

code action, scala 3, end marker, extract, class, file

### PR DESCRIPTION
**Pull request by zmerr**
resolves #3762 

https://user-images.githubusercontent.com/93259201/163993958-7f28c45d-5054-4869-bf68-7d31b1ab3267.mov

### CODE REVIEW

File: metals/src/main/scala/scala/meta/internal/metals/codeactions/ExtractRenameMember.scala [hunk 1]
```diff
@@ -378,20 +424,29 @@ class ExtractRenameMember(
...
-      removeTreeEdits(member) ++ companion.map(removeTreeEdits).getOrElse(Nil)
+      removeTreeEdits(endableMember.member) ++ maybeEndableMemberCompanion
+        .map(_.member)
+        .map(removeTreeEdits)
+        .getOrElse(Nil) ++ endableMember.maybeEndMarker
+        .map(removeTreeEdits)
+        .getOrElse(Nil) ++ maybeEndableMemberCompanion
+        .flatMap(_.maybeEndMarker)
+        .map(removeTreeEdits)
+        .getOrElse(Nil)
```
Comment (tgodzik) [inline metals/src/main/scala/scala/meta/internal/metals/codeactions/ExtractRenameMember.scala:449]:
```suggestion
      removeTreeEdits(endableMember.member) ++ { 
        maybeEndableMemberCompanion
        .map(_.member) ++ endableMember.maybeEndMarker
        ++ maybeEndableMemberCompanion
        .flatMap(_.maybeEndMarker)
        }.map(removeTreeEdits)
```
maybe something along these lines?

File: metals/src/main/scala/scala/meta/internal/metals/codeactions/ExtractRenameMember.scala [hunk 2]
```diff
@@ -92,17 +84,55 @@ class ExtractRenameMember(
...
-        case o: Defn.Object => nodes += o
-        case e: Defn.Enum => nodes += e
+        case c: Defn.Class => nodes += EndableMember(c, None)
+        case t: Defn.Trait => nodes += EndableMember(t, None)
+        case o: Defn.Object => nodes += EndableMember(o, None)
+        case e: Defn.Enum => nodes += EndableMember(e, None)
+        case endMarker: Term.EndMarker =>
+          val last = nodes.last
+          nodes.remove(nodes.size - 1)
+          nodes += EndableMember(last.member, Some(endMarker))
```
[the remark this answers is not in the document]
Comment (zmerr) [reply metals/src/main/scala/scala/meta/internal/metals/codeactions/ExtractRenameMember.scala:135]: `dropRight` returns the rest of the list, not the last element! since `.last` could through exception, I replaced it with `findLast(_ => true)` which is safe!

[the remark this answers is not in the document]
Comment (zmerr) [reply metals/src/main/scala/scala/meta/internal/metals/codeactions/ExtractRenameMember.scala]: I tried that as well as `lastOption`! Anything but the existing code does not work for some reason!

File: metals/src/main/scala/scala/meta/internal/metals/codeactions/ExtractRenameMember.scala (hunk 1 above)
Comment (zmerr) [reply metals/src/main/scala/scala/meta/internal/metals/codeactions/ExtractRenameMember.scala:453]: I mean I can define a separate `List[Tree]` to make it work! but would it look prettier?

Comment (tgodzik) [reply metals/src/main/scala/scala/meta/internal/metals/codeactions/ExtractRenameMember.scala:453]: I think it would be good in general to make it a bit more readable.

File: metals/src/main/scala/scala/meta/internal/metals/codeactions/ExtractRenameMember.scala [hunk 3]
```diff
@@ -45,11 +45,16 @@ class ExtractRenameMember(
...
-
-        def canRenameDefn(defn: Member): Boolean = {
+          definitions.find(_.member.name.pos.toLSP.overlapsWith(range))
+
+        def canRenameDefn(
+            defn: Member,
+            fileName: String,
+            defnAtCursor: Option[Member],
+            uri: String
+        ): Boolean = {
```
Comment (tgodzik) [inline metals/src/main/scala/scala/meta/internal/metals/codeactions/ExtractRenameMember.scala:57]:
```suggestion
        def canRenameDefn(defn: Member): Boolean = {
```

The rest is defined.

File: metals/src/main/scala/scala/meta/internal/metals/codeactions/ExtractRenameMember.scala [hunk 4]
```diff
@@ -58,14 +63,20 @@ class ExtractRenameMember(
...
         }
 
-        def canExtractDefn(defn: Member): Boolean = {
+        def canExtractDefn(
+            defn: Member,
+            fileName: String,
+            sealedNames: List[String],
+            definitions: List[Member],
+            uri: String
+        ): Boolean = {
```
Comment (tgodzik) [inline metals/src/main/scala/scala/meta/internal/metals/codeactions/ExtractRenameMember.scala:72]:
```suggestion
        def canExtractDefn(defn: Member): Boolean = {
```
same as above

**Review by tgodzik — CHANGES_REQUESTED** [review]

File: metals/src/main/scala/scala/meta/internal/metals/codeactions/ExtractRenameMember.scala (hunk 1 above)
Comment (zmerr) [reply metals/src/main/scala/scala/meta/internal/metals/codeactions/ExtractRenameMember.scala]: Done

**Review by tgodzik — APPROVED** [review]
LGTM!
