### PR TITLE
bugfix: Show implicit chained calls in inlay hints

### LINKED ISSUE #6890: Implicit inlay hints only show the first implicit call of a chain
### Describe the bug

```scala
//> using scala 2.13.15

implicit def aString: String = "a"
implicit def lengthOfString(implicit s: String): Int = s.length
implicit def toLong(implicit i: Int): Long = i.toLong

def toDouble(implicit l: Long): Double = l.toDouble

toDouble // the inlay hint only shows (toLong) but I expected it to show (toLong(lengthOfString(aString)))
```

### Expected behavior

Implicit inlay hint should show `(toLong(lengthOfString(aString)))` for the `toDouble` call but only shows `toLong`

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

v1.4.0

### Extra context or search terms

inlay-hints, implicits

### PR DESCRIPTION
**Pull request by francesconero**
Fixes #6890

### CODE REVIEW

File: mtags/src/main/scala-2/scala/meta/internal/pc/PcInlayHintsProvider.scala [hunk 1]
```diff
@@ -57,14 +59,10 @@ final class PcInlayHintsProvider(
             LabelPart(")") :: Nil,
             InlayHintKind.Parameter
           )
-      case ImplicitParameters(symbols, pos, allImplicit) =>
-        val labelParts = symbols.map(s => List(labelPart(s, s.decodedName)))
-        val label =
-          if (allImplicit) labelParts.separated("(", ", ", ")")
-          else labelParts.separated(", ")
```
Comment (francesconero) [inline mtags/src/main/scala-2/scala/meta/internal/pc/PcInlayHintsProvider.scala:64]: I can't think of a case where we wouldn't need parentheses around our inlay.

File: mtags/src/main/scala-2/scala/meta/internal/pc/PcInlayHintsProvider.scala [hunk 2]
```diff
@@ -160,25 +158,97 @@ final class PcInlayHintsProvider(
...
+              implicitArgs,
+              pos
             )
           case _ => None
         }
       else None
 
     private def isSyntheticArg(arg: Tree): Boolean =
-      arg.pos.isOffset && arg.symbol != null && arg.symbol.isImplicit
+      arg.pos.isOffset && arg.symbol != null && (arg.symbol.isImplicit || arg.symbol.isAnonymousFunction)
```
Comment (francesconero) [inline mtags/src/main/scala-2/scala/meta/internal/pc/PcInlayHintsProvider.scala:177]: Added isAnonymousFunction to show implicit lambdas generated from implicit defs

**Comment by tgodzik** [comment]
Looks like `tests.inlayHints.InlayHintsExpectSuite.ForComprehensions` is failing due to a symbol being null somewhere.

You can run it using `unit/testOnly tests.inlayHints.InlayHintsExpectSuite -- *ForComprehensions`

Also `tests.pc.InlayHintsSuite` fails for Scala 2.12.17 and also 2.11.12, could you take look? Or do you maybe need some help with it?

**Comment by francesconero** [comment]
> Looks like `tests.inlayHints.InlayHintsExpectSuite.ForComprehensions` is failing due to a symbol being null somewhere.
> 
> 
> 
> You can run it using `unit/testOnly tests.inlayHints.InlayHintsExpectSuite -- *ForComprehensions`
> 
> 
> 
> Also `tests.pc.InlayHintsSuite` fails for Scala 2.12.17 and also 2.11.12, could you take look? Or do you maybe need some help with it?

Yeah, the new check I added in `isSyntheticArg`, wrongly begins descending into the tree believing it to be an implicit parameter list.

What if instead of checking every parameter of an Apply to see if it's implicit, we simply match on the `Apply` subtype `ApplyToImplicitArgs` and then just recurse down the Tree from there? Is it too unstable?

File: mtags/src/main/scala-3/scala/meta/internal/pc/PcInlayHintsProvider.scala [hunk 3]
```diff
@@ -243,6 +239,67 @@ object ImplicitParameters:
...
+            }
+          case (arg :: remainingArgs, remainingArgsLists) =>
+            arg match {
+              case Apply(fun, args) =>
+                val applyLabel = (fun.symbol.decodedName, Some(fun.symbol))
+                recurseImplicitArgs(
+                  args,
+                  remainingArgs :: remainingArgsLists,
+                  ("(", None) :: applyLabel :: parts
+                )
```
[the remark this answers is not in the document]
Comment (tgodzik) [reply mtags/src/main/scala-3/scala/meta/internal/pc/PcInlayHintsProvider.scala:273]: Yeah, looks like we would have to have a separate branch altogether in the unapply and also to print it:
` case df @ DefDef(_, params, _, rhs) if df.symbol.isAnonymousFunction=> //`

Could be an improvement later on.

File: tests/cross/src/test/scala/tests/pc/InlayHintsSuite.scala [hunk 4]
```diff
@@ -870,7 +870,172 @@ class InlayHintsSuite extends BaseInlayHintsSuite {
...
+  check(
+    "implicit-fn2",
+    """|object Main{
+       |  implicit def stringLength(s: String, i: Int): Int = s.length
+       |  implicitly[(String, Int) => Int]
+       |}
+       |""".stripMargin,
+    """|object Main{
+       |  implicit def stringLength(s: String, i: Int): Int = s.length
+       |  implicitly[(String, Int) => Int]/*((s : String<<java/lang/String#>>, i : Int<<scala/Int#>>) => stringLength<<(2:15)>>(s<<(3:12)>>, i<<(3:12)>>)))*/
```
Comment (tgodzik) [inline tests/cross/src/test/scala/tests/pc/InlayHintsSuite.scala:1016]: I fixed it to also attach information for go to definition to types here.

**Review by tgodzik — APPROVED** [review]
LGTM!

Great work! I looked whether it would be simple enough to add showing lambdas in Scala 3, but that's a bit more involved, so let's leave it for later.

File: tests/cross/src/test/scala/tests/pc/InlayHintsSuite.scala (hunk 4 above)
Comment (francesconero) [reply tests/cross/src/test/scala/tests/pc/InlayHintsSuite.scala]: I avoided this explicitly since I think the positions of the synthetic symbols are all offsets and just point to the initial implicit method application. It would be cool to be able to calculate positions inside of inlays somehow.

Comment (tgodzik) [reply tests/cross/src/test/scala/tests/pc/InlayHintsSuite.scala]: Right, but the positions of those symbols were actually present, I added the `<<scala/Int#>>` part, which will correctly resolve to the type.

We can remove the positions from the synthetic symbols, shouldn't be an issue

Comment (francesconero) [reply tests/cross/src/test/scala/tests/pc/InlayHintsSuite.scala]: Sorry! I see now what you meant, actually I Had some code to remove positions from synthetic symbols, but it broke other tests, so I removed it.

Comment (tgodzik) [reply tests/cross/src/test/scala/tests/pc/InlayHintsSuite.scala]: Ok, I fixed that to not show those positions of synthetic params

**Comment by francesconero** [comment]
Thanks! Happy to contribute!

I'm wondering if we should probably avoid trying to render lambdas in Scala 2 as well and leave that for another time since it's also probably full of edge cases.

**Comment by tgodzik** [comment]
> Thanks! Happy to contribute!
> 
> I'm wondering if we should probably avoid trying to render lambdas in Scala 2 as well and leave that for another time since it's also probably full of edge cases.

It's not a big deal if it shows a bit wrong, it's only additional information that can be turned off.
