### PR TITLE
Don't attempt build import if sbt version is < 0.13.7

### LINKED ISSUE #401: Don't import builds older than sbt 0.13.17
Submitting as requested on Gitter.
I got the error below while importing an sbt file in VS Code after installing Metals:
Turns out the project I opened did have `sbt.version=0.13.8` in `build.properties` After changing that to `1.1.6` I can  import.
>>>
/Users/rrodseth/.sbt/0.13/plugins/metals.sbt:12: error: not found: value pluginCrossBuild
    val sbtVersion = Keys.sbtBinaryVersion.in(pluginCrossBuild).value
<<<

### PR DESCRIPTION
**Pull request by gabro**
Fixes #401

### CODE REVIEW

File: metals/src/main/scala/scala/meta/internal/metals/Messages.scala [hunk 1]
```diff
@@ -116,7 +116,7 @@ class Messages(icons: Icons) {
       command = ServerCommands.OpenBrowser(learnMoreUrl)
     )
     def toFixMessage =
-      "To fix this problem, upgrade to sbt v1.2.1+ or manually import the build."
+      "To fix this problem, upgrade to sbt v0.13.17+ or v1.2.1+ or manually import the build."
```
Comment (gabro) [inline metals/src/main/scala/scala/meta/internal/metals/Messages.scala]: @olafurpg do we really need 1.2.1+ or was this a legacy message? I would either update this or detect it and skip importing.

File: metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala [hunk 2]
```diff
@@ -634,10 +635,16 @@ class MetalsLanguageServer(
       case None =>
         if (!buildTools.isAutoConnectable) {
           scribe.warn(
-            s"Skipping build import for unsupport build tool $buildTools"
+            s"Skipping build import for unsupported build tool $buildTools"
           )
         }
         Future.successful(BuildChange.None)
+      case Some(sbt) if !isCompatibleSbtVersion(sbt.version) =>
```
[the remark this answers is not in the document]
Comment (gabro) [reply metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala]: This was without a `_` fallback even before and it's still exhaustive, but I see your point.

I've moved the logic inside the `Some(sbt)` case

File: metals/src/main/scala/scala/meta/internal/metals/Messages.scala [hunk 3]
```diff
@@ -110,13 +110,8 @@ class Messages(icons: Icons) {
   }
 
   object IncompatibleSbtVersion {
-    def statusBar(sbt: Sbt) = MetalsStatusParams(
```
Comment (gabro) [inline metals/src/main/scala/scala/meta/internal/metals/Messages.scala]: this was unused, so I took the liberty of removing it
