### PR TITLE
[Scala3] Fix completions after newline + dot

### LINKED ISSUE #2919: [Scala3] No completions after newline + dot in VScode
~~It seems that there is an issues in `CompletionPos` calculation~~

```scala
val a = List(1, 2)
  .m@@  // <- no completion
```

According to traces, metals actually returns completions but they are filtered out by VScode by some reason.
It's needed to check what wrongs with their data.

### PR DESCRIPTION
**Pull request by dos65**
Fixes #2919

### CODE REVIEW

**Review by tgodzik — COMMENTED** [review]
LGTM!

File: tests/cross/src/test/scala/tests/pc/CompletionSuite.scala [hunk 1]
```diff
@@ -1297,4 +1297,19 @@ class CompletionSuite extends BaseCompletionSuite {
     _.nonEmpty
   )
 
+  checkEdit(
+    "newline-dot",
```
Comment (tgodzik) [inline tests/cross/src/test/scala/tests/pc/CompletionSuite.scala:1301]: It seems  tests.pc.CompletionSuite.newline-dot_2.12.10 is breaking though due to having two items.

**Review by tgodzik — APPROVED** [review]
LGTM!
