### PR TITLE
fix: handle backticked names in inffered-type

### LINKED ISSUE #3785: Misplaced type annotation on backticked definitions
### Describe the bug

Invoking `Insert type annotation` code action on a backticked definition adds the annotation in a wrong position.
For a `def`:
```scala
object Foo {
  def `bar` = 1
}
```
becomes
```scala
object Foo {
  def `ba: Intr` = 1
}
```
in scala 2.13.8 but works correctly in scala 3.1.1

For a `val`:
```scala
object Foo {
  val `bar` = 1
}
```
gives
```scala
object Foo {
  val `ba: Intr` = 1
}
```
in scala 2.13.8 and
```scala
object Foo {
  val `bar: Int` = 1
}
```
in scala 3.1.1

### Expected behavior

```scala
object Foo {
  def `bar`: Int = 1
}
```

```scala
object Foo {
  val `bar`: Int = 1
}
```

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

0.11.2+123-b44dc8c0-SNAPSHOT

### Extra context or search terms

_No response_

### PR DESCRIPTION
**Pull request by dos65**
Fixes #3785

### CODE REVIEW

File: mtags/src/main/scala-3/scala/meta/internal/pc/InferredTypeProvider.scala [hunk 1]
```diff
@@ -251,4 +255,32 @@ final class InferredTypeProvider(
...
+        case Some((start, nextMatch :: left)) =>
+          if text.charAt(idx) == nextMatch then
+            lookup(idx + 1, Some((start, left)), withBacktick)
+          else lookup(idx + 1, None, withBacktick = false)
+        case Some((start, Nil)) =>
+          val end = if withBacktick then idx + 1 else idx
+          tree.source.atSpan(Span(start, end, start))
+        case None =>
+          val ch = text.charAt(idx)
+          if ch == realName.head then
```
Comment (tanishiking) [inline mtags/src/main/scala-3/scala/meta/internal/pc/InferredTypeProvider.scala:278]: Maybe it's too cautious, but can we use `headOption` to avoid `NoSuchElementException` here?

File: mtags/src/main/scala-3/scala/meta/internal/pc/InferredTypeProvider.scala [hunk 2]
```diff
@@ -251,4 +255,32 @@ final class InferredTypeProvider(
...
   end inferredTypeEdits
 
+  private def namePos(text: String, tree: untpd.NameTree)(using
+      Context
+  ): SourcePosition =
+    val realName = tree.name.stripModuleClassSuffix.lastPart.toString.toList
+
+    def lookup(
+        idx: Int,
+        start: Option[(Int, List[Char])],
```
Comment (tanishiking) [inline mtags/src/main/scala-3/scala/meta/internal/pc/InferredTypeProvider.scala:265]: [note]
A pair of next position and trailing realName

**Review by tanishiking — APPROVED** [review]
LGTM!
Maybe we can backport this `namePos` strategy (in Scala3) to `Interactive#namePos` https://github.com/lampepfl/dotty/blob/73cda0c9ad9a23132dabc8f8a7a47663da3ee3fa/compiler/src/dotty/tools/dotc/interactive/SourceTree.scala#L34-L36 ?

File: mtags/src/main/scala-3/scala/meta/internal/pc/InferredTypeProvider.scala (hunk 1 above)
Comment (kpodsiad) [reply mtags/src/main/scala-3/scala/meta/internal/pc/InferredTypeProvider.scala:278]: Is it possible to get zero length name?

File: mtags/src/main/scala-3/scala/meta/internal/pc/InferredTypeProvider.scala (hunk 2 above)
Comment (kpodsiad) [reply mtags/src/main/scala-3/scala/meta/internal/pc/InferredTypeProvider.scala:265]: Maybe forge this note into code?
```scala
case class Lookup(position: Int, tralingName: List[Char])
```

File: mtags/src/main/scala-3/scala/meta/internal/pc/InferredTypeProvider.scala [hunk 3]
```diff
@@ -251,4 +255,32 @@ final class InferredTypeProvider(
     end match
   end inferredTypeEdits
 
+  private def namePos(text: String, tree: untpd.NameTree)(using
+      Context
+  ): SourcePosition =
+    val realName = tree.name.stripModuleClassSuffix.lastPart.toString.toList
```
Comment (kpodsiad) [inline mtags/src/main/scala-3/scala/meta/internal/pc/InferredTypeProvider.scala:261]: Could you provide some example how `tree.name.stripModuleClassSuffix` and `tree.name.stripModuleClassSuffix.lastPart` differs from each other?

File: mtags/src/main/scala-3/scala/meta/internal/pc/InferredTypeProvider.scala [hunk 4]
```diff
@@ -251,4 +255,32 @@ final class InferredTypeProvider(
...
+      start match
+        case Some((start, nextMatch :: left)) =>
+          if text.charAt(idx) == nextMatch then
+            lookup(idx + 1, Some((start, left)), withBacktick)
+          else lookup(idx + 1, None, withBacktick = false)
+        case Some((start, Nil)) =>
+          val end = if withBacktick then idx + 1 else idx
+          tree.source.atSpan(Span(start, end, start))
+        case None =>
+          val ch = text.charAt(idx)
```
Comment (kpodsiad) [inline mtags/src/main/scala-3/scala/meta/internal/pc/InferredTypeProvider.scala:277]: Should we guard `idx` with, for example, `tree.sourcePos.end`?

**Review by kpodsiad — APPROVED** [review]
Looks good.

**Comment by dos65** [comment]
@tanishiking 
> Maybe we can backport this namePos strategy (in Scala3) to Interactive#namePos https://github.com/lampepfl/dotty/blob/73cda0c9ad9a23132dabc8f8a7a47663da3ee3fa/compiler/src/dotty/tools/dotc/interactive/SourceTree.scala#L34-L36 

I thought about that. Honestly, I don't like the approach in this pr but there is no other ways to fix it. 
On compiler side it should be handled in a more elegant way.

File: mtags/src/main/scala-3/scala/meta/internal/pc/InferredTypeProvider.scala (hunk 3 above)
Comment (dos65) [reply mtags/src/main/scala-3/scala/meta/internal/pc/InferredTypeProvider.scala:261]: @kpodsiad  I don't know. I just copied this line from from compiler impl for `namePos`

Comment (kpodsiad) [reply mtags/src/main/scala-3/scala/meta/internal/pc/InferredTypeProvider.scala:261]: Ok, adding info that `this line from from compiler impl for namePos` will also be helpful for future us.

File: mtags/src/main/scala-3/scala/meta/internal/pc/InferredTypeProvider.scala (hunk 1 above)
Comment (tgodzik) [reply mtags/src/main/scala-3/scala/meta/internal/pc/InferredTypeProvider.scala:278]: I don't think it's possible, we could add a require with a proper message just in case

File: mtags/src/main/scala-3/scala/meta/internal/pc/InferredTypeProvider.scala (hunk 4 above)
Comment (tgodzik) [reply mtags/src/main/scala-3/scala/meta/internal/pc/InferredTypeProvider.scala:277]: `case None if  idx < text.length` should probably suffice

File: mtags/src/main/scala-3/scala/meta/internal/pc/InferredTypeProvider.scala (hunk 3 above)
Comment (dos65) [reply mtags/src/main/scala-3/scala/meta/internal/pc/InferredTypeProvider.scala]: ok, just removed `lastPart` call. Tests pass without it.

File: mtags/src/main/scala-3/scala/meta/internal/pc/InferredTypeProvider.scala (hunk 1 above)
Comment (dos65) [reply mtags/src/main/scala-3/scala/meta/internal/pc/InferredTypeProvider.scala:281]: added a check for that
