### PR TITLE
SymbolIndex: multiply symbol locations

### LINKED ISSUE #2265: Found references for symbols in unrelated build targets.
**Describe the bug**

In case we have two unrelated build targets with the same symbol name, references will find symbols from both despite those being essentially separate symbols. It will also rename those symbols.

**To Reproduce**

1. Create two modules A and B
2. Create class `example.First` in A and B.
3. Find references to A.
4. See references from both modules

**Expected behavior**

Only references to A or B are shown.

**Installation:**

- Operating system: macOS/Windows/Linux
- Editor: Visual Studio Code/Atom/Vim/Sublime/Emacs
- Metals version: v0.9.6

**Additional context**

We might filter out files based on the build target. If we are in A we should go over all related build targets (upstream and downstream) and with that least filter out any source belonging to a target not in set.

**Search terms**

rename references multi module

### PR DESCRIPTION
**Pull request by dos65**
Previously, the index has been storing only one Path per symbol.
It didn't work correctly in cases if there were more than one symbol definition across the project that affected all features that are based on querying index like `go-to-definition` and  `references`.

In this PR this thing was reworked - now index stores all locations for symbol and in most places correct location is selected by filtering them by build targets. In particular, it fixes #2265.

Also, the way how dependency sources are extracted into `.readonly` was changed. This fixes navigation when there are several versions of the same library across build targets.
Now, if the source comes from source-jar it will be saved in: `.metals/readonly/dependencies/${source-jar-name}`.
For example for symbol `scala.Predef`:
- old: `.metals/readonly/scala/Predef.scala`
- now: `.metals/readonly/dependencies/scala-library_2.13.3-sources.jar/scala/Predef.scala`

Notes: the only features where wrong navigation is still possible are `StackTraceAnalyser` and `debugging`. 
They using LSP json parameters and they are slightly different from other places where `definitionProvider` is used. I think it would be ok to create issues and fix them later.

### CODE REVIEW

File: metals/src/main/scala/scala/meta/internal/metals/JarTopLevels.scala [hunk 1]
```diff
@@ -29,10 +27,10 @@ final class JarTopLevels(conn: () => Connection) {
    */
   def getTopLevels(
       path: AbsolutePath
-  ): Option[TrieMap[String, AbsolutePath]] =
+  ): Option[List[(String, AbsolutePath)]] =
     try {
       val fs = PlatformFileIO.newJarFileSystem(path, create = false)
-      val toplevels = TrieMap[String, AbsolutePath]()
+      val toplevels = List.newBuilder[(String, AbsolutePath)]
```
Comment (ckipp01) [inline metals/src/main/scala/scala/meta/internal/metals/JarTopLevels.scala:33]: Out of curiosity, why the change from the `TrieMap` to `List`? Normally I prefer to have a Map for this over a list of tuples unless there is a good reason not to.

File: metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala [hunk 2]
```diff
@@ -275,15 +275,40 @@ object MetalsEnrichments
...
+        )
+      } else {
+        None
+      }
+    }
+
     /**
      * Writes zip file contents to disk under $workspace/.metals/readonly.
+     *
+     * In case if path is jar then target directory is $workspace/.metals/readonly/$jarName
```
Comment (ckipp01) [inline metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala:299]: So I'm a bit confused by this. So what is the difference between:

```
metals/readonly/dependencies/scala-library_2.13.3-sources.jar/scala/Predef.scala
```
and
```
metals/readonly/scala-library_2.13.3-sources.jar/scala/Predef.scala
```

File: metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala [hunk 3]
```diff
@@ -2300,12 +2305,15 @@ class MetalsLanguageServer(
       item <- dependencySources.getItems.asScala
       scalaTarget <- buildTargets.scalaTarget(item.getTarget)
       sourceUri <- Option(item.getSources).toList.flatMap(_.asScala)
+      path = sourceUri.toAbsolutePath
+      _ = buildTargets.addDependencySource(path, item.getTarget)
+      _ = jdkSources.foreach(jdk =>
+        buildTargets.addDependencySource(jdk, item.getTarget)
```
Comment (ckipp01) [inline metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala:2311]: nit
```suggestion
      _ = jdkSources.foreach(source =>
        buildTargets.addDependencySource(source, item.getTarget)
```
Calling that `jdk` may be a bit confusing.

File: metals/src/main/scala/scala/meta/internal/metals/BuildTargets.scala [hunk 4]
```diff
@@ -319,20 +322,37 @@ final class BuildTargets(
...
+          .toRelative(workspace.resolve(Directories.dependencies))
+          .toNIO
+          .getName(0)
+          .filename
+
+      inverseDependencySources
+        .find { case (path, _) =>
+          path.filename == jarName
+        }
+        .flatMap { case (_, ids) => ids.headOption }
```
Comment (ckipp01) [inline metals/src/main/scala/scala/meta/internal/metals/BuildTargets.scala:343]: I must be losing my mind or something but I swear I already commented this, but now it's gone 🤔 anways, probably just style choice, but you could also do

```scala
        .collectFirst {
          case (path, ids) if path.filename == jarName && ids.nonEmpty =>
            ids.head
        }
```
To avoid iterating twice.

I wish we had a `nonEmptySet` we could use here since realistically `ids` will never be empty.

File: metals/src/main/scala/scala/meta/internal/metals/DefinitionProvider.scala [hunk 5]
```diff
@@ -254,22 +265,66 @@ class DestinationProvider(
...
+
+    val definitions = index.definitions(Symbol(symbol)).filter(_.path.exists)
+    allowedBuildTargets match {
+      case None => definitions.headOption
+      case Some(targets) =>
+        val asSet = targets.toSet
+        val matched = definitions.find { defn =>
+          sourceBuildTargets(defn.path).exists(id => asSet.contains(id))
+        }
+        // Fallback on any definition - it needs for worksheets
```
Comment (ckipp01) [inline metals/src/main/scala/scala/meta/internal/metals/DefinitionProvider.scala:286]:
```suggestion
        // Fallback to any definition - it's needed for worksheets
```
?

File: metals/src/main/scala/scala/meta/internal/metals/DefinitionProvider.scala [hunk 6]
```diff
@@ -254,22 +265,66 @@ class DestinationProvider(
...
+  ): Option[SymbolDefinition] = {
+    val allowedBuildTargets =
+      for {
+        src <- source
+        id <- buildTargets.inverseSources(src)
+      } yield buildTargets.buildTargetTransitiveDependencies(id)
+
+    val definitions = index.definitions(Symbol(symbol)).filter(_.path.exists)
+    allowedBuildTargets match {
+      case None => definitions.headOption
```
Comment (ckipp01) [inline metals/src/main/scala/scala/meta/internal/metals/DefinitionProvider.scala:280]: I see this `headOption` in a lot of places. How do we ensure that the `headOption` is actually the desired one?

File: metals/src/main/scala/scala/meta/internal/metals/DefinitionProvider.scala [hunk 7]
```diff
@@ -254,22 +265,66 @@ class DestinationProvider(
...
+  private def sourceBuildTargets(
+      source: AbsolutePath
+  ): List[BuildTargetIdentifier] = {
+    def trivialSource: Option[List[BuildTargetIdentifier]] =
+      Option(buildTargets.sourceBuildTargets(source).toList).filter(_.nonEmpty)
+
+    def dependencySource: Option[List[BuildTargetIdentifier]] = {
+      source.jarPath
+        .map(buildTargets.inverseDependencySource)
+        .filter(_.nonEmpty)
```
Comment (ckipp01) [inline metals/src/main/scala/scala/meta/internal/metals/DefinitionProvider.scala:302]: Nit, Map + Filter = Collect

File: metals/src/main/scala/scala/meta/internal/metals/JarTopLevels.scala (hunk 1 above)
Comment (ckipp01) [inline metals/src/main/scala/scala/meta/internal/metals/JarTopLevels.scala:33]: Any reason to change from using a Map to a list? Typically I prefer Maps over List of tuples for this type of thing.

File: tests/slow/src/test/scala/tests/sbt/SbtBloopLspSuite.scala [hunk 8]
```diff
@@ -453,7 +453,7 @@ class SbtBloopLspSuite
       _ <- assertDefinitionAtLocation(
         "build.sbt",
         "sc@@alaVersion := \"2.12.11\"",
-        ".metals/readonly/sbt/Keys.scala",
+        "sbt/Keys.scala",
```
Comment (ckipp01) [inline tests/slow/src/test/scala/tests/sbt/SbtBloopLspSuite.scala:456]: Shouldn't this still be in `.metals/readonly`?

File: tests/unit/src/main/scala/tests/BaseAmmoniteSuite.scala [hunk 9]
```diff
@@ -69,21 +62,21 @@ abstract class BaseAmmoniteSuite(scalaVersion: String)
       _ <- assertDefinitionAtLocation(
         "main.sc",
         "foo.as@@Json.noSpaces",
-        ".metals/readonly/io/circe/syntax/package.scala"
+        "io/circe/syntax/package.scala"
```
Comment (ckipp01) [inline tests/unit/src/main/scala/tests/BaseAmmoniteSuite.scala:65]: Again are all these right no longer being in `.metals/readonly`? Or are they all now relative? If it's easy to switch, having the full path here might be clearer.

**Review by ckipp01 — CHANGES_REQUESTED** [review]
Great job on this @dos65! I have a couple questions and a couple nits.

File: metals/src/main/scala/scala/meta/internal/metals/BuildTargets.scala [hunk 10]
```diff
@@ -319,20 +322,37 @@ final class BuildTargets(
     }
   }
 
+  /**
+   *  Match build target by source jar name if source was saved in `.metals/readonly/dependecies/${source-jar-name}`
+   */
+  private def inferByJarDirectoryName(
+      source: AbsolutePath
+  ): Option[BuildTargetIdentifier] = {
+    if (source.isInDependenciesDirectory(workspace)) {
```
[the remark this answers is not in the document]
Comment (dos65) [reply metals/src/main/scala/scala/meta/internal/metals/BuildTargets.scala]: I reworked this a little bit to avoid double-checking the similar clause.

**Comment by ckipp01** [comment]
If I'm not mistaken, this should also fix https://github.com/scalameta/metals/issues/1196 right?

File: metals/src/main/scala/scala/meta/internal/metals/BuildTargets.scala [hunk 11]
```diff
@@ -50,7 +49,7 @@ final class BuildTargets(
   private val buildTargetSources =
     TrieMap.empty[BuildTargetIdentifier, util.Set[AbsolutePath]]
   private val inverseDependencySources =
-    TrieMap.empty[AbsolutePath, BuildTargetIdentifier]
+    TrieMap.empty[AbsolutePath, Set[BuildTargetIdentifier]]
```
[the remark this answers is not in the document]
Comment (dos65) [reply metals/src/main/scala/scala/meta/internal/metals/BuildTargets.scala:52]: I wish the same but as it used in the index too it's required to implement it without additional mem-overhead.
I've seen such implementation in [cats](https://github.com/typelevel/cats/blob/main/core/src/main/scala/cats/data/NonEmptySet.scala) but I don't know if it worths to copy-paste it for these two cases.

**Comment by dos65** [comment]
> If I'm not mistaken, this should also fix #1196 right?
Yep!

File: metals/src/main/scala/scala/meta/internal/metals/JarTopLevels.scala (hunk 1 above)
Comment (dos65) [reply metals/src/main/scala/scala/meta/internal/metals/JarTopLevels.scala:33]: `scala.collection.concurrent.TrieMap` is too complex type for this method. It was used because `OnDemandSymbolIndex.toplevels` had this signature and there was this tricky method: https://github.com/scalameta/metals/blob/03704c17b5397bd8feb4771d0bedf9a6dfe0a660/mtags/src/main/scala-2/scala/meta/internal/mtags/OnDemandSymbolIndex.scala#L96-L104

But as `toplevels` signature was changed to `TrieMap[String, Set[AbsolutePath]]` it became inconvenient to use `addSourceJarTopLevels`  as they were so I changed this part and replaced `TrieMap` here on smth more suitable.

It might be `Map` but it anyway used only as a `List`.

File: metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala (hunk 2 above)
Comment (dos65) [reply metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala]: I forgot to add `/dependencies` in the comment. Thx!

File: metals/src/main/scala/scala/meta/internal/metals/BuildTargets.scala (hunk 4 above)
Comment (dos65) [reply metals/src/main/scala/scala/meta/internal/metals/BuildTargets.scala]: Thx! Replaced by `collectFirst`

File: metals/src/main/scala/scala/meta/internal/metals/DefinitionProvider.scala (hunk 6 above)
Comment (dos65) [reply metals/src/main/scala/scala/meta/internal/metals/DefinitionProvider.scala:280]: It might be non desired one but at least it returns smth and works in a similar way to the current implementation.

There were two places where I wasn't sure how to pass `allowedBuildTargets` properly into this method so I decided to fix them later.

File: tests/slow/src/test/scala/tests/sbt/SbtBloopLspSuite.scala (hunk 8 above)
Comment (dos65) [reply tests/slow/src/test/scala/tests/sbt/SbtBloopLspSuite.scala:456]: They still are in `.metals/readonly` but the path became much longer - `.metals/readonly/dependencies/sbt-${version}-sources.jar/sbt/Keys.scala`.
Honestly, it was easier to fix tests by leaving these paths without full prefix than investigating the right one per every test. Anyway, there isn't a lot of meaning in seeing them.

Also, I think it might be annoying to update jar names in these paths in case if some dependency version will be changed in tests

File: metals/src/main/scala/scala/meta/internal/metals/BuildTargets.scala [hunk 12]
```diff
@@ -461,13 +471,14 @@ final class BuildTargets(
...
+    val acc = inverseDependencySources.getOrElse(sourcesJar, Set.empty)
+    inverseDependencySources(sourcesJar) = acc + target
   }
 
   def inverseDependencySource(
       sourceJar: AbsolutePath
-  ): Option[BuildTargetIdentifier] = {
-    inverseDependencySources.get(sourceJar)
+  ): List[BuildTargetIdentifier] = {
+    inverseDependencySources.get(sourceJar).map(_.toList).getOrElse(List.empty)
```
Comment (ckipp01) [inline metals/src/main/scala/scala/meta/internal/metals/BuildTargets.scala:481]: Not a huge deal, but we could just keep a `Set` here.

File: metals/src/main/scala/scala/meta/internal/metals/DefinitionProvider.scala (hunk 6 above)
Comment (ckipp01) [reply metals/src/main/scala/scala/meta/internal/metals/DefinitionProvider.scala:280]: Sounds good. For those two places, make sure to have TODOs or issues created for them then so we don't forget about them.

File: metals/src/main/scala/scala/meta/internal/metals/DefinitionProvider.scala [hunk 13]
```diff
@@ -254,22 +265,66 @@ class DestinationProvider(
...
+        // aren't registered in buildTargets
+        matched.orElse(definitions.headOption)
+    }
+  }
+
+  private def sourceBuildTargets(
+      source: AbsolutePath
+  ): List[BuildTargetIdentifier] = {
+    def trivialSource: Option[List[BuildTargetIdentifier]] =
+      Option(buildTargets.sourceBuildTargets(source).toList).filter(_.nonEmpty)
```
Comment (ckipp01) [inline metals/src/main/scala/scala/meta/internal/metals/DefinitionProvider.scala:297]: Couldn't this be simplified to just `List`? Whenever I see `Option[List]` I always think that unless there is a real difference between `None` and `Some(List.empty)`.

File: metals/src/main/scala/scala/meta/internal/metals/DefinitionProvider.scala [hunk 14]
```diff
@@ -254,22 +265,66 @@ class DestinationProvider(
...
+
+    def dependencySource: Option[List[BuildTargetIdentifier]] = {
```
Comment (ckipp01) [inline metals/src/main/scala/scala/meta/internal/metals/DefinitionProvider.scala:299]: Same question as above, is the `Option[List` necessary?

File: metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala [hunk 15]
```diff
@@ -275,15 +276,41 @@ object MetalsEnrichments
...
 
+    def toRelativeInside(prefix: AbsolutePath): Option[RelativePath] = {
+      val relative = path.toRelative(prefix)
+      if (relative.toNIO.getName(0).filename != "..") Some(relative)
+      else None
+    }
+
+    def jarPath: Option[AbsolutePath] = {
+      val filesystem = path.toNIO.getFileSystem()
+      if (filesystem.provider().getScheme().equals("jar")) {
```
Comment (ckipp01) [inline metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala:287]: Do we also need to consider srcjars here? https://github.com/scalameta/metals/pull/2710

**Review by ckipp01 — CHANGES_REQUESTED** [review]
Sorry this took me a while to get back to! Just a couple nits/questions. But apart from that I'll use this snapshot today to ensure nothing wonky happens and we should be able to merge this soon!

File: metals/src/main/scala/scala/meta/internal/metals/JarTopLevels.scala (hunk 1 above)
Comment (ckipp01) [reply metals/src/main/scala/scala/meta/internal/metals/JarTopLevels.scala:33]: Alright, sounds good and thanks for the explanation.

File: tests/slow/src/test/scala/tests/sbt/SbtBloopLspSuite.scala (hunk 8 above)
Comment (ckipp01) [reply tests/slow/src/test/scala/tests/sbt/SbtBloopLspSuite.scala:456]: Yea good point about changing these in the future. 👍🏼

File: tests/unit/src/main/scala/tests/BaseAmmoniteSuite.scala (hunk 9 above)
Comment (ckipp01) [reply tests/unit/src/main/scala/tests/BaseAmmoniteSuite.scala:65]: Seen your reason up above. Just ignore this.

File: metals/src/main/scala/scala/meta/internal/metals/DefinitionProvider.scala (hunk 13 above)
Comment (dos65) [reply metals/src/main/scala/scala/meta/internal/metals/DefinitionProvider.scala:297]: Yep, I agree that in most cases `Option[List[A]]` should be reduced to `List[A]`.

However, here it's used only in inner functions just to take benefits from `orElse` combinator in usage below - https://github.com/scalameta/metals/blob/a82a14240bd55284ba220650fe5a70c4198b5cde/metals/src/main/scala/scala/meta/internal/metals/DefinitionProvider.scala#L305-L308
Otherwise, I had to inекщвгсу smth like `orElseIfNil` for `List` for this small part of code.

File: metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala (hunk 15 above)
Comment (dos65) [reply metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala:287]: Good catch. Thx!

File: metals/src/main/scala/scala/meta/internal/metals/DefinitionProvider.scala (hunk 13 above)
Comment (ckipp01) [reply metals/src/main/scala/scala/meta/internal/metals/DefinitionProvider.scala:297]: Alright sounds good 👍🏼

File: metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala (hunk 15 above)
Comment (ckipp01) [reply metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala:287]: Ah ok, I wasn't 100% sure, that's why I brought it up.

**Review by ckipp01 — APPROVED** [review]
Really great job @dos65. 🚀 

This is a LGTM from me, but I'm not sure if @tgodzik wants to take a quick look over first.

**Comment by tgodzik** [comment]
I will take a look tomorrow! I am going slowly through my backlog of reviews 😅

File: mtags/src/main/scala-2/scala/meta/internal/mtags/OnDemandSymbolIndex.scala [hunk 16]
```diff
@@ -51,90 +51,127 @@ final class OnDemandSymbolIndex(
...
   ): Unit = {
     if (source.isAmmoniteScript || !isTrivialToplevelSymbol(path, toplevel)) {
-      toplevels(toplevel) = source
+      val acc = toplevels.getOrElse(toplevel, Set.empty)
+      toplevels(toplevel) = acc + source
     }
   }
 
-  private def tryRun(thunk: => Unit): Unit =
+  private def addToplevelSymbol0(symbol: String, source: AbsolutePath): Unit = {
```
Comment (tgodzik) [inline mtags/src/main/scala-2/scala/meta/internal/mtags/OnDemandSymbolIndex.scala:167]: Can we inline this if it's only used in one palce?

File: tests/unit/src/test/scala/tests/DefinitionLspSuite.scala [hunk 17]
```diff
@@ -326,4 +326,67 @@ class DefinitionLspSuite extends BaseLspSuite("definition") {
     } yield ()
   }
 
+  test("clashing-references") {
```
Comment (tgodzik) [inline tests/unit/src/test/scala/tests/DefinitionLspSuite.scala:329]: You should also uncomment https://github.com/scalameta/metals/blob/03704c17b5397bd8feb4771d0bedf9a6dfe0a660/tests/unit/src/test/scala/tests/debug/BreakpointDapSuite.scala#L633
to see if it's working correctly now.

File: mtags/src/main/scala-2/scala/meta/internal/mtags/OnDemandSymbolIndex.scala [hunk 18]
```diff
@@ -51,90 +51,127 @@ final class OnDemandSymbolIndex(
...
-          onError(InvalidJarException(jar, e))
       }
-    }
+    )
 
   // Used to add cached toplevel symbols to index
-  def addSourceJarTopLevels(
+  def addIndexedSourceJar(
       jar: AbsolutePath,
-      loadTopLevels: () => TrieMap[String, AbsolutePath]
```
Comment (tgodzik) [inline mtags/src/main/scala-2/scala/meta/internal/mtags/OnDemandSymbolIndex.scala:98]: I think this was done so that `loadTopLevels` is not calculated again if a jar was already added. Doesn't your change make it evaluate always? We could maybe make it `=> symbols: List[(String, AbsolutePath)]` and make it lazy val at invocation at the `None` case? It would serve the same purpose.

**Review by tgodzik — CHANGES_REQUESTED** [review]
That is a lot of great changes and I calculate that we can solve 3 issues with this PR. I left some comments, I don't think anything major popped up. Good job!

File: metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala [hunk 19]
```diff
@@ -275,15 +276,41 @@ object MetalsEnrichments
         workspace.resolve(Directories.readonly).toNIO
       )
 
+    def toRelativeInside(prefix: AbsolutePath): Option[RelativePath] = {
+      val relative = path.toRelative(prefix)
+      if (relative.toNIO.getName(0).filename != "..") Some(relative)
```
[the remark this answers is not in the document]
Comment (dos65) [reply metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala:281]: Honestly, I'm not sure about Windows.
In Linux, it can't.

File: metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala [hunk 20]
```diff
@@ -2300,12 +2305,15 @@ class MetalsLanguageServer(
       item <- dependencySources.getItems.asScala
       scalaTarget <- buildTargets.scalaTarget(item.getTarget)
       sourceUri <- Option(item.getSources).toList.flatMap(_.asScala)
+      path = sourceUri.toAbsolutePath
+      _ = buildTargets.addDependencySource(path, item.getTarget)
```
[the remark this answers is not in the document]
Comment (dos65) [reply metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala:2309]: It was needed to correctly call `buildTargets.addDependencySource(path, item.getTarget)`.
Otherwise, it registers jar only once for the first build target where it appeared.

[the remark this answers is not in the document]
Comment (tgodzik) [reply metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala:2309]: Ach alright. This should be fine.

File: mtags/src/main/scala-2/scala/meta/internal/mtags/OnDemandSymbolIndex.scala [hunk 21]
```diff
@@ -51,90 +51,127 @@ final class OnDemandSymbolIndex(
   private val onErrorOption = onError.andThen(_ => None)
 
   override def definition(symbol: Symbol): Option[SymbolDefinition] = {
-    try findSymbolDefinition(symbol, symbol)
+    try findSymbolDefinition(symbol, symbol).headOption
```
[the remark this answers is not in the document]
Comment (dos65) [reply mtags/src/main/scala-2/scala/meta/internal/mtags/OnDemandSymbolIndex.scala:54]: Unfortunately, there are still a lot of places where it's used.

Initially, I thought that this fix will take less time than I already spend on it.
So, I would prefer to turn it into an issue - a kind of the second interaction of fixing wrong definitions. 

I think I will return to it after completing scala 3 related things.

[the remark this answers is not in the document]
Comment (tgodzik) [reply mtags/src/main/scala-2/scala/meta/internal/mtags/OnDemandSymbolIndex.scala:54]: Sure! Let's create a follow up to make sure that all places are properly handled.

File: mtags/src/main/scala-2/scala/meta/internal/mtags/OnDemandSymbolIndex.scala (hunk 18 above)
Comment (dos65) [reply mtags/src/main/scala-2/scala/meta/internal/mtags/OnDemandSymbolIndex.scala:98]: It slightly changes behavior but jar-indexing definitely happens only once as it should
The difference in case if a jar was already added:
 - previously: absolutely nothing happens
 - now: for the first jar occurrence during the import it will request toplevels once from H2 and they will be ignored in this function.

I think it's how it should work.
Also, I've just found that we don't recreate index during build reloading that might lead to stale symbols so we can't rely on `DefinitionIndex` state.

Comment (tgodzik) [reply mtags/src/main/scala-2/scala/meta/internal/mtags/OnDemandSymbolIndex.scala:98]: Makes sense! Let's leave it as is.

File: metals/src/main/scala/scala/meta/internal/metals/debug/SourcePathProvider.scala [hunk 22]
```diff
@@ -29,7 +29,7 @@ final class SourcePathProvider(
     val symbolBase = if (base.contains("/")) base else "_empty_/" + base
     val symbols = for {
       symbol <- Set(symbolBase + ".", symbolBase + "#").toIterator
-      definition <- definitionProvider.fromSymbol(symbol).asScala
+      definition <- definitionProvider.fromSymbol(symbol, None).asScala
```
[the remark this answers is not in the document]
Comment (dos65) [reply metals/src/main/scala/scala/meta/internal/metals/debug/SourcePathProvider.scala]: There is not enough data currently - only stacktrace as a string. I will mention it in the issue for step 2

[the remark this answers is not in the document]
Comment (dos65) [reply metals/src/main/scala/scala/meta/internal/metals/debug/SourcePathProvider.scala]: Fixed

File: metals/src/main/scala/scala/meta/internal/metals/StacktraceAnalyzer.scala [hunk 23]
```diff
@@ -68,7 +68,7 @@ class StacktraceAnalyzer(
 
   def fileLocationFromLine(line: String): Option[l.Location] = {
     def findLocationForSymbol(s: String): Option[Location] =
-      definitionProvider.fromSymbol(s).asScala.headOption
+      definitionProvider.fromSymbol(s, None).asScala.headOption
```
[the remark this answers is not in the document]
Comment (dos65) [reply metals/src/main/scala/scala/meta/internal/metals/StacktraceAnalyzer.scala:71]: There is not enough data currently - only stacktrace as a string. I will mention it in the issue for step 2

File: tests/unit/src/test/scala/tests/DefinitionLspSuite.scala (hunk 17 above)
Comment (dos65) [reply tests/unit/src/test/scala/tests/DefinitionLspSuite.scala:329]: Thx! Now it works.

**Review by tgodzik — APPROVED** [review]
LGTM! Thanks for the great work!
