### PR TITLE
fix: Recompile worksheet on changes even if didFocus is not supported

### LINKED ISSUE #7090: Recompiling worksheet on changes even if didFocus is not supported
### Describe the bug

Based on https://github.com/scalameta/metals/pull/7015#discussion_r1907268676

Some editors do not support didFocus extension which means that we migh sometimes not get worksheet properly evaluated. We should make sure that it works properly even if that extension is not supported.

### Expected behavior

_No response_

### Operating system

Linux

### Editor/Extension

Other

### Version of Metals

v1.4.2

### Extra context or search terms

worksheet didFocus

### PR DESCRIPTION
**Pull request by krrish175-byte**
Fixes #7090

## Problem

When the client (editor) does not support the `didFocus` capability, worksheets were not being evaluated/recompiled on save if another file had been opened after the worksheet. This happened because `onWorksheetChanged` checked `focusedDocument.contains(path)` even when `didFocus` was not supported.

Without `didFocus` events, the `focusedDocument` tracking (which relies on `didOpen`) becomes stale when users switch tabs, causing worksheet evaluations to be skipped.

## Solution

Modified the condition in `onWorksheetChanged` to only check `focusedDocument.contains(path)` when `clientConfig.isDidFocusProvider()` is true. If `didFocus` is not supported, any changed worksheet will be evaluated regardless of the current `focusedDocument` state.

## Changes

- [MetalsLspService.scala](cci:7://file:///Users/krrishbiswas/Desktop/GSoC/metals/metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala:0:0-0:0): Removed `|| focusedDocument.isDefined` from the condition in `onWorksheetChanged`

## Testing

Added a new test suite `Issue7090LspSuite` that:
1. Disables `didFocusProvider` 
2. Opens a worksheet, then opens another file
3. Modifies and saves the worksheet
4. Asserts that the worksheet is evaluated (via diagnostics)

### CODE REVIEW

File: project/V.scala [hunk 1]
```diff
@@ -25,7 +25,7 @@ object V {
 
   val betterMonadicFor = "0.3.1"
 
-  val bloop = "2.0.18"
+  val bloop = "2.0.17"
```
Comment (tgodzik) [inline project/V.scala]:
```suggestion
  val bloop = "2.0.18"
```

**Review by tgodzik — APPROVED** [review]
LGTM
