### PR TITLE
Suppress model-refresh if debugging is unsupported

### LINKED ISSUE #1016: Command metals-model-refresh should only be sent to clients with debugging support
**Describe the bug**

When using the latest SNAPSHOT of Metals with Emacs we get the following warning
```
Warning (lsp-mode): Unknown metals client command: metals-model-refresh
```
The warning origins from
https://github.com/scalameta/metals/blob/68459a7a9fede5cb56685012a2aa8f01a86a8125/metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala#L1536

**Expected behavior**

No warning because the Emacs client doesn't support debugging.

**Additional context**

https://gitter.im/scalameta/metals?at=5db154c72f8a034357c9cd58

### PR DESCRIPTION
**Pull request by marek1840**
closes #1016 

Previously, model-refresh command was sent to the client even though it didn't support debugging.
Now, metals will refrain from sending in in such cases.

### CODE REVIEW

File: metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageClient.scala [hunk 1]
```diff
@@ -1,19 +1,30 @@
...
 import org.eclipse.lsp4j.MessageType
 import org.eclipse.lsp4j.jsonrpc.services.JsonNotification
 import org.eclipse.lsp4j.jsonrpc.services.JsonRequest
 import org.eclipse.lsp4j.services.LanguageClient
-
 import scala.meta.internal.tvp._
 import scala.meta.internal.metals.MetalsEnrichments._
 
 trait MetalsLanguageClient extends LanguageClient with TreeViewClient {
+  @volatile private var debuggingSupported = true
```
Comment (olafurpg) [inline metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageClient.scala]: Any logic related to configuring what gets forwarded to the language client should be handled in `ConfigureLanguageClient`.

As a general rule of thumb, I would recommend avoiding `val` and `var` inside traits.

File: tests/unit/src/main/scala/tests/TestingServer.scala [hunk 2]
```diff
@@ -494,7 +498,7 @@ final class TestingServer(
       _ = client.refreshModelHandler = handler
       // first compilation, to trigger the handler
       _ <- server.compilations.compileFiles(List(path))
-      lenses <- codeLenses.future
+      lenses <- codeLenses.future.withTimeout(30, TimeUnit.SECONDS)
```
Comment (olafurpg) [inline tests/unit/src/main/scala/tests/TestingServer.scala]: what is the motivation for this change? 30 seconds is a long timeout.

File: tests/unit/src/test/scala/tests/UnsupportedDebuggingLspSuite.scala [hunk 3]
```diff
@@ -0,0 +1,68 @@
...
+
+import java.util.concurrent.TimeUnit
+import scala.concurrent.TimeoutException
+import scala.meta.internal.metals.ClientCommands
+import scala.meta.internal.metals.ClientExperimentalCapabilities
+import scala.meta.internal.metals.MetalsEnrichments._
+import scala.util.Failure
+import scala.util.Success
+
+object UnsupportedDebuggingLspSuite
```
Comment (olafurpg) [inline tests/unit/src/test/scala/tests/UnsupportedDebuggingLspSuite.scala]: 👍 Thank you for writing a test case!

File: metals/src/main/scala/scala/meta/internal/metals/ConfiguredLanguageClient.scala [hunk 4]
```diff
@@ -93,7 +99,14 @@ final class ConfiguredLanguageClient(
       params: ExecuteCommandParams
   ): Unit = {
     if (config.executeClientCommand.isOn) {
-      underlying.metalsExecuteClientCommand(params)
+      params.getCommand match {
+        case _ if config.executeClientCommand.isOff =>
+        // ignore
+        case ClientCommands.RefreshModel.id if !debuggingSupported =>
```
Comment (olafurpg) [inline metals/src/main/scala/scala/meta/internal/metals/ConfiguredLanguageClient.scala]: Does this work? I think there's an `unapply`
```suggestion
        case ClientCommands.RefreshModel() if !debuggingSupported =>
```

File: metals/src/main/scala/scala/meta/internal/metals/ConfiguredLanguageClient.scala [hunk 5]
```diff
@@ -93,7 +99,14 @@ final class ConfiguredLanguageClient(
       params: ExecuteCommandParams
   ): Unit = {
     if (config.executeClientCommand.isOn) {
-      underlying.metalsExecuteClientCommand(params)
+      params.getCommand match {
+        case _ if config.executeClientCommand.isOff =>
```
Comment (olafurpg) [inline metals/src/main/scala/scala/meta/internal/metals/ConfiguredLanguageClient.scala]: Why is this line needed? We already guard against `isOn` above

File: metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala [hunk 6]
```diff
@@ -200,6 +199,14 @@ class MetalsLanguageServer(
     MetalsLogger.setupLspLogger(workspace, redirectSystemOut)
     val clientExperimentalCapabilities =
       ClientExperimentalCapabilities.from(params.getCapabilities)
+
+    languageClient.underlying match {
+      case client: ConfiguredLanguageClient =>
+        client.configure(clientExperimentalCapabilities)
```
Comment (olafurpg) [inline metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala]: Would it make sense to add this method to `MetalsLanguageClient` with a default implementation that ignores the argument?

File: metals/src/main/scala/scala/meta/internal/metals/NoopLanguageClient.scala [hunk 7]
```diff
@@ -39,9 +39,6 @@ abstract class NoopLanguageClient extends MetalsLanguageClient {
   override def metalsTreeViewDidChange(
       params: TreeViewDidChangeParams
   ): Unit = ()
-  // override def metalsTreeViewNodeReveal(
```
Comment (olafurpg) [inline metals/src/main/scala/scala/meta/internal/metals/NoopLanguageClient.scala]: Why is this change needed?

File: metals/src/main/scala/scala/meta/metals/Main.scala [hunk 8]
```diff
@@ -35,9 +34,8 @@ object Main {
         .setRemoteInterface(classOf[MetalsLanguageClient])
         .setLocalService(server)
         .create()
-      val underlyingClient = launcher.getRemoteProxy
-      val client = new ConfiguredLanguageClient(underlyingClient, config)(ec)
```
Comment (olafurpg) [inline metals/src/main/scala/scala/meta/metals/Main.scala]: What was the motivation for this change?

File: metals/src/main/scala/scala/meta/internal/metals/NoopLanguageClient.scala (hunk 7 above)
Comment (marek1840) [reply metals/src/main/scala/scala/meta/internal/metals/NoopLanguageClient.scala]: As a rule of thumb, I don't like to keep a commented out code in the codebase. If the code is unused, then it can and probably should be removed.

File: metals/src/main/scala/scala/meta/metals/Main.scala (hunk 8 above)
Comment (marek1840) [reply metals/src/main/scala/scala/meta/metals/Main.scala]: The introduced `UnsupportedDebuggingLspSuite` tests the behavior of the `ConfigurationLanguageClient` which is responsible for suppressing the model-refresh notification. Without this change, we couldn't test it, as the `ConfigurationLanguageClient` was created only inside `Main` object, and then injected to the language server (hence not present in the test suite).

File: metals/src/main/scala/scala/meta/internal/metals/NoopLanguageClient.scala (hunk 7 above)
Comment (olafurpg) [reply metals/src/main/scala/scala/meta/internal/metals/NoopLanguageClient.scala]: I agree! I thought the method was removed in this PR but I didn't see it was commented out.

File: metals/src/main/scala/scala/meta/metals/Main.scala (hunk 8 above)
Comment (olafurpg) [reply metals/src/main/scala/scala/meta/metals/Main.scala]: I see, makes sense, thanks for the explanation!
