### PR TITLE
Handle abstract var overrides

### LINKED ISSUE #1029: Override abstract var not behaving as expected
**Describe the bug**
If you have the following code below and try to trigger a completion for the abstract `var foo`, you aren't able to trigger it by beginning to type `var`. However, you are able to trigger the override completion with beginning to type `def` or `override`. If you do then trigger the completion for it, it will be implemented as `def foo: Int = ???`

```scala
package example

object Hello extends App {
  trait Foo {
    var foo: Int
  }

  val test = new Foo {
    // trigger override here
  }
}
```

**To Reproduce**
Just pace the example object from, move to where it says _trigger override here_, and then attempt to get the correct `var foo` override implementation.

**Expected behavior**
I would expect that the override completion be triggered by starting to type `override` or `var` and that the implementation would both show the correct signature and implementation of a `var` and not a `def`.

**Screenshots**
Screenshot 2019-10-30 at 15 05 12
Screenshot 2019-10-30 at 15 05 33
Screenshot 2019-10-30 at 15 05 46

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code and Vim
- Metals version: v0.7.6-Most recent snapshot

**Search terms**
absract members, var, completions

### PR DESCRIPTION
**Pull request by gabro**
Fixes #1029 

Previously we would prevent overriding `var` members altogether, recently there seems to be been a regression where we suggest `def` completions for `var` members (#1029); now we allow overriding abstract `var` members, while still rejecting concrete `var` overrides.

### CODE REVIEW

File: mtags/src/main/scala/scala/meta/internal/pc/Completions.scala [hunk 1]
```diff
@@ -452,7 +452,7 @@ trait Completions { this: MetalsGlobal =>
           pos,
           text,
           valdef.pos.start,
-          _.isStable
+          _ => true
```
Comment (gabro) [inline mtags/src/main/scala/scala/meta/internal/pc/Completions.scala]: `vars` are not stable symbols, but we can still override them in some cases

File: tests/cross/src/test/scala/tests/pc/CompletionOverrideSuite.scala [hunk 2]
```diff
@@ -648,10 +648,60 @@ object CompletionOverrideSuite extends BaseCompletionSuite {
...
+       |abstract class Val {
+       |  var hello1: Int
+       |  val hello2: Int
+       |  def hello3: Int
+       |}
+       |class Main extends Val {
+       |  override val hello@@
+       }
+       |""".stripMargin,
+    // NOTE(gabro): we inlcude also var and def completions despite the user typed a val
```
Comment (gabro) [inline tests/cross/src/test/scala/tests/pc/CompletionOverrideSuite.scala]: I honestly couldn't make this work, but it's not too terrible as UX

File: mtags/src/main/scala/scala/meta/internal/pc/Completions.scala [hunk 3]
```diff
@@ -1087,7 +1094,7 @@ trait Completions { this: MetalsGlobal =>
         !sym.isEffectivelyFinal &&
         !sym.name.endsWith(CURSOR) &&
         !sym.isConstructor &&
-        !sym.isMutable &&
+        (!isVarSetter(sym) || (isVarSetter(sym) && sym.isAbstract)) &&
```
Comment (gabro) [inline mtags/src/main/scala/scala/meta/internal/pc/Completions.scala]: allow overriding vars, but only if they're abstract

**Comment by ckipp01** [comment]
Awesome! This is exactly what I needed! I just locally rebased on this and my issues with #1031 go away entirely and all tests pass for 2.11, 2.12, and 2.13. Thanks for looking at this 👏

File: tests/cross/src/test/scala/tests/pc/CompletionOverrideSuite.scala (hunk 2 above)
Comment (olafurpg) [reply tests/cross/src/test/scala/tests/pc/CompletionOverrideSuite.scala]: I think this UX is totally fine, you don't always know if the supermethod is a def, val or a var
