### PR TITLE
fix indentation for multiline string when using format selection

### LINKED ISSUE #1509: Range formatting issue within a multiline string
**Describe the bug**
When selecting part of a multiline string that needs to be formatted, the formatting only works when you select after the `|` to start the formatting. This was pointed out in #1505 by @kpbochenek .

**To Reproduce**
1. Go to multiline string that isn't formatted correctly
2. Select portion of string to format including the first `|`
3. Try to format selection
4. Doesn't format as expected unless you don't include the `|`

**Expected behavior**
Expect this to align the `|` like it should.

**Screenshots**

image

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.8.1

**Search terms**
Range formatting, formatting, multiline strings

### PR DESCRIPTION
**Pull request by mlachkar**
The goal is to list the tests we would like to see working.

In the gif below, I listed all cases that work/don't work
hello-world-template-1586167831750

closes #1509

### CODE REVIEW

**Comment by mlachkar** [comment]
hello-world-template-1586214506009

File: tests/unit/src/test/scala/tests/RangeFormattingWhenSelectingSuite.scala [hunk 1]
```diff
@@ -0,0 +1,164 @@
+package tests
+
+import munit.Location
+
+class RangeFormattingWhenSelectingSuite
+    extends BaseLspSuite("rangeFormatting") {
+  check(
+    "selecting starting the line that misindent",
```
Comment (tgodzik) [inline tests/unit/src/test/scala/tests/RangeFormattingWhenSelectingSuite.scala:8]: We are using short names like `select-starting` so that it's easier later to run single test.

Could you change them to more concise names?

File: tests/unit/src/test/scala/tests/RangeFormattingWhenSelectingSuite.scala [hunk 2]
```diff
@@ -0,0 +1,164 @@
...
+       |               |third line
+       |               |fourth line'''.stripMargin
+       |}""".stripMargin
+  )
+
+  check(
+    "selecting two string",
+    s"""
+       |object Main {
+       |<<  val firstString = '''
```
Comment (tgodzik) [inline tests/unit/src/test/scala/tests/RangeFormattingWhenSelectingSuite.scala:110]: This is an interesting case, I think it's fine to leave it as such and document it here.

File: tests/unit/src/test/scala/tests/RangeFormattingWhenSelectingSuite.scala (hunk 1 above)
Comment (mlachkar) [reply tests/unit/src/test/scala/tests/RangeFormattingWhenSelectingSuite.scala:8]: yes

File: metals/src/main/scala/scala/meta/internal/metals/MultilineStringFormattingProvider.scala [hunk 3]
```diff
@@ -3,14 +3,14 @@ package scala.meta.internal.metals
...
 import org.eclipse.lsp4j.Range
 import org.eclipse.lsp4j.TextEdit
+
 import scala.concurrent.ExecutionContext
 import scala.concurrent.Future
 import scala.meta.inputs.Input
 import scala.meta.internal.metals.MetalsEnrichments._
 import scala.meta.tokens.Token
-import scala.meta.tokens.Token.Constant
+import scala.meta.tokens.Token.{Constant, Ident, Interpolation}
```
Comment (tgodzik) [inline metals/src/main/scala/scala/meta/internal/metals/MultilineStringFormattingProvider.scala:12]: Could you split the imports into separate lines? That's the convention we have in Metals. Also, scalafix is failing due to the fact that one of those is no longer used.

File: tests/unit/src/test/scala/tests/RangeFormattingWhenSelectingSuite.scala [hunk 4]
```diff
@@ -0,0 +1,166 @@
+package tests
+
+import munit.Location
+
+class RangeFormattingWhenSelectingSuite
+    extends BaseLspSuite("rangeFormatting") {
+  check(
+    "starting-the-misindent-line",
```
Comment (tgodzik) [inline tests/unit/src/test/scala/tests/RangeFormattingWhenSelectingSuite.scala:8]: `start-misindent-line` ?

File: tests/unit/src/test/scala/tests/RangeFormattingWhenSelectingSuite.scala [hunk 5]
```diff
@@ -0,0 +1,166 @@
...
+       |  val str = '''
+       |              |first line
+       |                   |second line
+       |                   |third line
+       |                   |fourth line'''.stripMargin
+       |}""".stripMargin
+  )
+
+  check(
+    "starting-the-previous-well-indent-line",
```
Comment (tgodzik) [inline tests/unit/src/test/scala/tests/RangeFormattingWhenSelectingSuite.scala:29]: `starting-well-indent-line` ?

File: tests/unit/src/test/scala/tests/RangeFormattingWhenSelectingSuite.scala [hunk 6]
```diff
@@ -0,0 +1,166 @@
...
+       |  val str = '''
+       |              |first line
+       |              |second line
+       |              |third line
+       |              |fourth line'''.stripMargin
+       |}""".stripMargin
+  )
+
+  check(
+    "starting-the-first-line",
```
Comment (tgodzik) [inline tests/unit/src/test/scala/tests/RangeFormattingWhenSelectingSuite.scala:50]: `starting-fist-line` ?

File: tests/unit/src/test/scala/tests/RangeFormattingWhenSelectingSuite.scala [hunk 7]
```diff
@@ -0,0 +1,166 @@
...
+       |object Main {
+       |  val str = '''first line
+       |              |second line
+       |              |third line
+       |              |fourth line'''.stripMargin
+       |}""".stripMargin
+  )
+
+  check(
+    "starting-the-first-line-when-using-a-pipe",
```
Comment (tgodzik) [inline tests/unit/src/test/scala/tests/RangeFormattingWhenSelectingSuite.scala:69]: `first-line-with-pipe`?

File: tests/unit/src/test/scala/tests/RangeFormattingWhenSelectingSuite.scala [hunk 8]
```diff
@@ -0,0 +1,166 @@
...
+       |object Main {
+       |  val str = '''|first line
+       |               |second line
+       |               |third line
+       |               |fourth line'''.stripMargin
+       |}""".stripMargin
+  )
+
+  check(
+    "entire-multi-line-string",
```
Comment (tgodzik) [inline tests/unit/src/test/scala/tests/RangeFormattingWhenSelectingSuite.scala:88]: `entire-string` ?

File: metals/src/main/scala/scala/meta/internal/metals/MultilineStringFormattingProvider.scala (hunk 3 above)
Comment (mlachkar) [reply metals/src/main/scala/scala/meta/internal/metals/MultilineStringFormattingProvider.scala:12]: yes. thanks

File: tests/unit/src/test/scala/tests/RangeFormattingWhenSelectingSuite.scala (hunk 4 above)
Comment (mlachkar) [reply tests/unit/src/test/scala/tests/RangeFormattingWhenSelectingSuite.scala:8]: ok

**Comment by tgodzik** [comment]
Just added a very small commit, since I discovered an old issue was badly tested and just resurfaced.
