### PR TITLE
fix: compile only JVM targets by default

### LINKED ISSUE #7444: Test Explorer causes all targets to compile
### Describe the bug

Looks like even if some native and js projects are not currently worked on, we will ask for test and cause those projects to compile. Which in a clean workspace can use up a lot of your CPU

### Expected behavior

Only the JVM targets are compiled unless JS and Native specific files are touched.

### Operating system

None

### Editor/Extension

None

### Version of Metals

v1.5.2

### Extra context or search terms

CPU excessive compilation

### PR DESCRIPTION
**Pull request by warcholjakub**
## Summary
- Added `activePlatforms` concept - only JVM is active by default
- JS/Native platforms activate when user opens a file from that platform

This prevents unnecessary compilation of JS/Native targets.
Closes #7444

### CODE REVIEW

**Review by tgodzik — COMMENTED** [review]
Would you be able to add some tests? We would probably need to add platform to QuickBuild or use SbtBloopLspSuite

File: tests/slow/src/test/scala/tests/sbt/ActivePlatformsSuite.scala [hunk 1]
```diff
@@ -0,0 +1,75 @@
...
+        |/build.sbt
+        |${SbtBuildLayout.commonSbtSettings}
+        |ThisBuild / scalaVersion := "2.13.17"
+        |
+        |lazy val jvmProject = project.in(file("jvm"))
+        |lazy val jsProject = project.in(file("js")).enablePlugins(ScalaJSPlugin)
+        |lazy val nativeProject = project.in(file("native")).enablePlugins(ScalaNativePlugin)
+        |
+        |/jvm/src/main/scala/JvmMain.scala
+        |object JvmMain { val x = 1 }
```
Comment (tgodzik) [inline tests/slow/src/test/scala/tests/sbt/ActivePlatformsSuite.scala:27]: Maybe instead, we should introduce an error into Native, check if it shows up by default and when it shows up? I would avoid inspecting internals, rather try to see if the behaviour for the user is the same
