### PR TITLE
Use 2.13 dialect for syntax errors

### LINKED ISSUE #787: Literal types not accepted as identifiers
**Describe the bug**
When using string literals as types, as is supported by Scala 2.13, Metals provides an error from scalameta that `identifier expected but string constant found`. With integer literals the same happens, with the message `identifier expected but integer constant found`.

The code compiles fine.

**To Reproduce**
1. Add the line `val o: Option["name"] = ???` to any valid location in a 2.13 project.

**Expected behavior**
No errors in the IDE.

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.6.1+90-cde40f08-SNAPSHOT

### PR DESCRIPTION
**Pull request by gabro**
Fixes #787 

This PR switches to the 2.13 Scalameta dialect for parsing buffers.

It's important to notice that we always the 2.13 dialect even for 2.12 or 2.11 builds, which means that in this case:

```scala
val x: Option["lit"] = Some("lit")
```

we won't be reporting an error as you type for 2.12 / 2.11 builds.

The error is still reported after compilation (i.e. on file save) so this should be an acceptable compromise.

### CODE REVIEW

File: mtags/src/main/scala/scala/meta/internal/mtags/ScalaToplevelMtags.scala [hunk 1]
```diff
@@ -38,7 +38,7 @@ class ScalaToplevelMtags(
     val input: Input.VirtualFile,
     includeInnerClasses: Boolean
 ) extends MtagsIndexer {
-  private val scanner = new LegacyScanner(input, dialects.Scala212)
```
Comment (gabro) [inline mtags/src/main/scala/scala/meta/internal/mtags/ScalaToplevelMtags.scala]: This is not strictly related to the issue at hand, but it felt consistent to update it

File: tests/unit/src/test/scala/tests/SyntaxErrorSlowSuite.scala [hunk 2]
```diff
@@ -312,4 +312,26 @@ object SyntaxErrorSlowSuite extends BaseSlowSuite("syntax-error") {
...
+  testAsync("literal-types") {
+    cleanWorkspace()
+    for {
+      _ <- server.initialize(
+        s"""
+           |/metals.json
+           |{"a": {}}
+           |/project/build.properties
+           |sbt.version=1.2.6
+           |/build.sbt
```
Comment (olafurpg) [inline tests/unit/src/test/scala/tests/SyntaxErrorSlowSuite.scala]: Let's remove all build-related files, we only need a standalone file to test this change.

Side note, tests with sbt builds should live in the `slow` project.

Comment (gabro) [reply tests/unit/src/test/scala/tests/SyntaxErrorSlowSuite.scala]: 👍 I've added those info for debugging, then I forgot to remove them.

Comment (gabro) [reply tests/unit/src/test/scala/tests/SyntaxErrorSlowSuite.scala]: ah, the standalone file reports an error (from scalac, not scalameta) probably because "rambo mode" uses 2.12. Should we change it to use 2.13 instead? This is not strictly related to this issue, again, but it might make sense

Comment (olafurpg) [reply tests/unit/src/test/scala/tests/SyntaxErrorSlowSuite.scala]: Can you elaborate? The standalone compiler doesn't report diagnostics.

The "rambo mode" can stay on 2.12 for now, we can change it to 2.13 when the metals server upgrades to 2.13.

Comment (gabro) [reply tests/unit/src/test/scala/tests/SyntaxErrorSlowSuite.scala]: Sorry, I got confused. :D Tests should be ok now.

**Comment by gabro** [comment]
Ci failure on Azure seems unrelated

**Comment by olafurpg** [comment]
Yeah azure has been flaky recently.
