### PR TITLE
fix: ZIO test explorer reveals sub-tasks with provideLayer (#8054)

### LINKED ISSUE #8054: ZIO Test: Test explorer does not reveal sub-tasks if a layer is provided
### Describe the bug

MRE:
```scala
import zio.test.*
import zio.*
import zio.test.TestAspect.*

trait SomeLayer {}

object HelloTest extends ZIOSpecDefault {
  def spec =
    suite("HelloTest")(
      suite("testA")(
        test("testA1") {
          assertTrue(true)
        },
        test("testA2") {
          assertTrue(true)
        },
        test("testA3") {
          assertTrue(true)
        }
      ),
      suite("testB")(
        test("testB1") {
          assertTrue(true)
        },
        test("testB2") {
          assertTrue(true)
        },
        test("testB3") {
          assertTrue(true)
        }
      )
    ).provideLayer(ZLayer.succeed(new SomeLayer {})) // <------
}
```

The highlighted line prevents the test explorer from acquiring the list of sub-tasks:

Image

Removing the call (and then reloading window) would reveal the list of sub-tasks again:

Image

### Expected behavior

It should always reveal the sub-tasks.

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

1.6.4+60-a63f9e5c-SNAPSHOT

### Scala version/s

3.7.1

### Extra context or search terms

Used sbt bsp server, not bloop.

The main use case hindered by this bug is that I can't debug only a specific test inside a large suite.

I also tried workaround using `args` in launch.json (like `-t testA` which usually works on ZIO Test) but it doesn't seem to pass them to the test class so I'm stuck. Maybe it deserves its own issue?

### PR DESCRIPTION
**Pull request by krrish175-byte**
## Closing Issue

closes #8054

### CODE REVIEW

File: tests/unit/src/test/scala/tests/testProvider/ZioTestFinderSuite.scala [hunk 1]
```diff
@@ -304,6 +304,83 @@ class ZioTestFinderSuite extends FunSuite {
...
+       |      assertTrue(true)
+       |    }
+       |  ).provideLayer(ZLayer.succeed(new SomeLayer {}))
+       |}
+       |""".stripMargin,
+    FullyQualifiedName("HelloTest"),
+    Set(
+      (
+        "HelloTest",
+        QuickRange(7, 13, 17, 3),
```
Comment (tgodzik) [inline tests/unit/src/test/scala/tests/testProvider/ZioTestFinderSuite.scala]: Looks like the tests do not have correct ranges. Could you run the tests and fix them? If using LLMs you can use MEtals MCP to make it run the tests for you
