### PR TITLE
fix: scala3 match-case completions - improve autoimports

### LINKED ISSUE #4368: Inconsistent case completions with conflicts
### Describe the bug

Case completions in scala 3 don't add prefix when conflict with another symbol occurs. Triggering completions in
```scala
object Hello extends App{
  val e: Either[Int, String] = ???
  type Left = String
  e match {
    case Le@@ =>
  }
}
```
results in
```scala
object Hello extends App{
  val e: Either[Int, String] = ???
  type Left = String
  e match {
    case Left(value) =>
  }
}
```

### Expected behavior

In scala 2 we get
```scala
object Hello extends App{
  val e: Either[Int, String] = ???
  type Left = String
  e match {
    case scala.util.Left(value) =>
  }
}
```

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

v0.11.8

### Extra context or search terms

_No response_

### PR DESCRIPTION
**Pull request by dos65**
Fixes #4368
Also, ports cases ordering logic from Scala2

### CODE REVIEW

File: mtags/src/main/scala-3/scala/meta/internal/pc/AutoImports.scala [hunk 1]
```diff
@@ -202,6 +220,41 @@ object AutoImports:
             case _ => None
         case IndexedContext.Result.InScope => None
 
+    def inferSymbolImport(symbol: Symbol): SymbolImport =
```
Comment (dos65) [inline mtags/src/main/scala-3/scala/meta/internal/pc/AutoImports.scala:223]: This PR adds some duplications. `SymbolImport` is an extended form of `AutoImport` that allows to customize import section edits logic.

Previously, we were adding only one import per action but for exhaustive match completions we need to add several at once.
I'm going to get rid of `AutoImport` in other places but I think it would be better to merge it as it is as this change blocks @jkciesluk

**Comment by jkciesluk** [comment]
> Fixes https://github.com/scalameta/metals/issues/4368

I don't see any change there, it works the same as before

**Comment by jkciesluk** [comment]
> Fixes https://github.com/scalameta/metals/issues/4368

I don't see any change there, it works the same

File: mtags/src/main/scala-3/scala/meta/internal/pc/completions/MatchCaseCompletions.scala [hunk 2]
```diff
@@ -158,7 +153,7 @@ object CaseKeywordCompletion:
         case _ =>
           if !(selectorSym.is(Sealed) &&
               (selectorSym.is(Abstract) || selectorSym.is(Trait)))
-          then visit(selectorSym, selectorSym.decodedName, Nil)
+          then visit(SymbolImport.simple(selectorSym))
```
Comment (jkciesluk) [inline mtags/src/main/scala-3/scala/meta/internal/pc/completions/MatchCaseCompletions.scala:156]:
```suggestion
          then visit(autoImportsGen.inferSymbolImport(ts))
```

> >Fixes https://github.com/scalameta/metals/issues/4368

> It is fixed in exhaustive match, but in single case completions it works the same

This should fix it

**Review by jkciesluk — CHANGES_REQUESTED** [review]

File: mtags/src/main/scala-3/scala/meta/internal/pc/completions/MatchCaseCompletions.scala [hunk 3]
```diff
@@ -168,55 +163,63 @@ object CaseKeywordCompletion:
       indexedContext.scopeSymbols
         .foreach(s =>
           val ts = s.info.dealias.typeSymbol
-          if (isValid(ts)) then visit(ts, ts.decodedName, Nil)
+          if (isValid(ts)) then visit(SymbolImport.simple(ts))
```
Comment (jkciesluk) [inline mtags/src/main/scala-3/scala/meta/internal/pc/completions/MatchCaseCompletions.scala:166]:
```suggestion
          if (isValid(ts)) then visit(autoImportsGen.inferSymbolImport(selectorSym))
```
Maybe also here?

File: mtags/src/main/scala-3/scala/meta/internal/pc/AutoImports.scala [hunk 4]
```diff
@@ -79,6 +79,24 @@ object AutoImports:
       }.toMap
   end AutoImport
 
+  sealed trait ImportSel:
+    def sym: Symbol
+
+  object ImportSel:
+    final case class Direct(sym: Symbol) extends ImportSel
```
[the remark this answers is not in the document]
Comment (dos65) [reply mtags/src/main/scala-3/scala/meta/internal/pc/AutoImports.scala:67]: Upd: removed the duplication. Now old methods are based on `inferSymbolImport`.

File: mtags/src/main/scala-3/scala/meta/internal/pc/IndexedContext.scala [hunk 5]
```diff
@@ -12,6 +12,7 @@ import dotty.tools.dotc.core.Names.*
 import dotty.tools.dotc.core.Symbols.*
 import dotty.tools.dotc.core.Types.*
 import dotty.tools.dotc.typer.ImportInfo
+import dotty.tools.dotc.core.Flags
```
Comment (jkciesluk) [inline mtags/src/main/scala-3/scala/meta/internal/pc/IndexedContext.scala:15]: Scalafix is failing because of it, I think we can remove this import since it's not used

**Review by jkciesluk — APPROVED** [review]
LGTM! Great work!

File: mtags/src/main/scala-3/scala/meta/internal/pc/AutoImports.scala [hunk 6]
```diff
@@ -160,77 +160,118 @@ object AutoImports extends AutoImportsBackticks:
...
-      val editPos = pos.withSpan(Spans.Span(importPosition.offset)).toLsp
-      new l.TextEdit(editPos, formatted)
-    end importEdit
+              val importSel =
+                if rename != owner.showName then
+                  Some(ImportSel.Rename(owner, rename)).filter(_ =>
+                    !indexedContext.hasRename(owner, rename)
+                  )
+                else
+                  Some(ImportSel.Direct(owner)).filter(_ =>
```
Comment (tgodzik) [inline mtags/src/main/scala-3/scala/meta/internal/pc/AutoImports.scala:229]: What if owner also have conflict, shouldn't we go up the onwer chain in this case?

Comment (dos65) [reply mtags/src/main/scala-3/scala/meta/internal/pc/AutoImports.scala:229]: > What if owner also have conflict, shouldn't we go up the onwer chain in this case?

Yep, that's what I noticed too but when I started doing that properly it opened much more questions than I expected and it led to a bigger rework. At least right now it works as previously + as in Scala2

I have wip branch for that.

Comment (tgodzik) [reply mtags/src/main/scala-3/scala/meta/internal/pc/AutoImports.scala:228]: Ok sure, we can improve it later on. If you don't manage to create a PR, could you open an issue mentioning that?

**Review by tgodzik — APPROVED** [review]

File: mtags/src/main/scala-3/scala/meta/internal/pc/AutoImports.scala (hunk 6 above)
Comment (dos65) [reply mtags/src/main/scala-3/scala/meta/internal/pc/AutoImports.scala:228]: I'm planning to turn it into PR during this week.
If it won't happen I will create an issue
