### PR TITLE
Fix Scala 3 Presentation Compiler

### LINKED ISSUE #8257: Metals V2.0.0-M8: VS Code does not highlight compile errors in cross platform projects
### Describe the bug

This particular issue makes working in VSCode almost impossible - luckily I do most of my editing in Helix, but I thought I should report it.

This monorepo (https://github.com/PurpleKingdomGames/indigoengine) is built against Mill, and I switched to Metals v2 because it's so much faster! However, where the terminal shows compile errors, and they show up in Helix, VSCode does not show them. I'll attach screenshots.

### Expected behavior

The expected behaviour is that VSCode shows compile errors inline, as Helix does.

Mill's output:

Image

Helix, showing the error:

Image

VSCode, during recompile flashes red a few times, but ultimately shows no useful information.

Image

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

v2.0.0-M8

### Scala version/s

3.8.1

### Extra context or search terms

M7 had the same behaviour. I'm cross building to Scala.js, JVM, and Scala Native, but they all target the same Scala version.

### PR DESCRIPTION
**Pull request by snjeza**
Fixes #8257

### CODE REVIEW

File: metals/src/main/scala/scala/meta/internal/metals/Compilers.scala [hunk 1]
```diff
@@ -1607,7 +1614,11 @@ class Compilers(
 
         modifiedFiles.foreach(path =>
           pc.didChange(
-            CompilerVirtualFileParams(path.toNIO.toUri, buffers.get(path).get)
+            CompilerVirtualFileParams(
+              path.toNIO.toUri,
+              buffers.get(path).get,
+              shouldReturnDiagnostics = true,
```
Comment (tgodzik) [inline metals/src/main/scala/scala/meta/internal/metals/Compilers.scala]: We don't need diagnostics here, they are ignored.

File: metals/src/main/scala/scala/meta/internal/metals/Compilers.scala [hunk 2]
```diff
@@ -1032,7 +1035,11 @@ class Compilers(
             val (input, _, adjust) =
               sourceAdjustments(uri.toString(), compiler.scalaVersion())
             val requestParams = new internal.pc.PcReferencesRequest(
-              CompilerVirtualFileParams(uri, input.text),
+              CompilerVirtualFileParams(
+                uri,
+                input.text,
+                shouldReturnDiagnostics = true,
```
Comment (tgodzik) [inline metals/src/main/scala/scala/meta/internal/metals/Compilers.scala]: No need for diagnostics here as well

File: metals/src/main/scala/scala/meta/internal/metals/Compilers.scala [hunk 3]
```diff
@@ -727,6 +729,7 @@ class Compilers(
               input.text,
               token,
               outlineFilesProvider.getOutlineFiles(compiler.buildTargetId()),
+              shouldReturnDiagnostics = true,
```
Comment (tgodzik) [inline metals/src/main/scala/scala/meta/internal/metals/Compilers.scala]: Not needed

**Review by tgodzik — CHANGES_REQUESTED** [review]
Thanks for working on this! I forgot about fixing this, a lot of moving pieces here.

File: metals/src/main/scala/scala/meta/internal/metals/Compilers.scala (hunk 1 above)
Comment (snjeza) [reply metals/src/main/scala/scala/meta/internal/metals/Compilers.scala]: Fixed.

File: metals/src/main/scala/scala/meta/internal/metals/Compilers.scala (hunk 2 above)
Comment (snjeza) [reply metals/src/main/scala/scala/meta/internal/metals/Compilers.scala]: Fixed.

File: metals/src/main/scala/scala/meta/internal/metals/Compilers.scala (hunk 3 above)
Comment (snjeza) [reply metals/src/main/scala/scala/meta/internal/metals/Compilers.scala]: Fixed.

**Comment by snjeza** [comment]
@tgodzik I have updated the PR.

File: tests/unit/src/test/scala/tests/mbt/MbtScalaReferenceSuite.scala [hunk 4]
```diff
@@ -224,9 +224,6 @@ class MbtScalaReferenceSuite
         """|a/src/main/scala/a/Downstream.scala:4:12: reference
            |    val a: Point = Point(1, 2)
            |           ^^^^^
-           |a/src/main/scala/a/Downstream.scala:4:20: reference
```
Comment (tgodzik) [inline tests/unit/src/test/scala/tests/mbt/MbtScalaReferenceSuite.scala:227]: This is unexpected, references should not be impacted here. Any idea what is going on? There might be some incompatibility between the two options

Comment (snjeza) [reply tests/unit/src/test/scala/tests/mbt/MbtScalaReferenceSuite.scala:227]: The Scala 3 Presentation Compiler doesn't report:
```
          |a/src/main/scala/a/Downstream.scala:4:20: reference
          |    val a: Point = Point(1, 2)
          |                   ^^^^^
```
~~I can try to add~~ 
```
"metals.presentation-compiler-diagnostics": false,
```
~~for this test.~~

Comment (tgodzik) [reply tests/unit/src/test/scala/tests/mbt/MbtScalaReferenceSuite.scala:227]: You could yeah, but having diagnostics should not influence this, would be great to investigate why it's needed. This is Scala 2 code, so nothing should really have changed.

Comment (snjeza) [reply tests/unit/src/test/scala/tests/mbt/MbtScalaReferenceSuite.scala:227]: ~~The test calls~~ 
https://github.com/scalameta/metals/blob/6d6a5f15d01c56863028fefc571bd757380c7605/metals/src/main/scala/scala/meta/internal/metals/Compilers.scala#L338
~~which was changed~~.

Comment (snjeza) [reply tests/unit/src/test/scala/tests/mbt/MbtScalaReferenceSuite.scala:227]: I have fixed this issue. Now, the PR does not change any test.
Could you, please, check again?

**Review by tgodzik — APPROVED** [review]
LGTM!
