### PR TITLE
Make goto definition work for worksheets, fixes #1067

### LINKED ISSUE #1067: Goto definition doesn't work in worksheets
**Describe the bug**

Doing goto definition inside `*.worksheet.sc` files returns "No definition found"

**Expected behavior**

Definition in `*.sc` files should work the same way as in `*.scala` files.
**Screenshots**

Screenshot 2019-11-14 at 16 06 18

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: 0.7.6+218-e9e219e9-SNAPSHOT

### PR DESCRIPTION
**Pull request by olafurpg**
Previously, goto definition didn't work in `*.worksheet.sc` files
because there were several guards in the implementation against
`*.scala` filenames. Now, goto definition treats `*.sc` files the same
way as `*.scala` files.

### CODE REVIEW

File: metals/src/main/scala/scala/meta/internal/metals/Embedded.scala [hunk 1]
```diff
@@ -30,6 +33,23 @@ final class Embedded(
 
   override def cancel(): Unit = {
     presentationCompilers.clear()
+    mdocs.clear()
+  }
+
+  private val mdocs: TrieMap[String, URLClassLoader] =
```
Comment (tgodzik) [inline metals/src/main/scala/scala/meta/internal/metals/Embedded.scala]: Can we move this value up to the top of the file?

File: metals/src/main/scala/scala/meta/internal/metals/Embedded.scala [hunk 2]
```diff
@@ -40,23 +60,34 @@ final class Embedded(
...
+  ): T = {
+    val services = ServiceLoader.load(cls, classloader).iterator()
     if (services.hasNext) services.next()
     else {
-      // NOTE(olafur): ServiceLoader doesn't find the presentation compiler service
-      // on Appveyor for some reason, I'm unable to reproduce on my computer. Here below
-      // we fallback to manual classloading.
-      val cls =
-        classloader.loadClass(classOf[ScalaPresentationCompiler].getName)
+      // NOTE(olafur): ServiceLoader doesn't find the service on Appveyor for
```
Comment (tgodzik) [inline metals/src/main/scala/scala/meta/internal/metals/Embedded.scala]: We no longer use AppVeyor, do we need to load ScalaPresentationCompiler explicitely?

File: metals/src/main/scala/scala/meta/internal/worksheets/WorksheetClassLoader.scala [hunk 3]
```diff
@@ -0,0 +1,15 @@
+package scala.meta.internal.worksheets
+
+/**
+ * ClassLoader that is used to reflectively invoke mdoc for worksheet evaluation.
+ */
+class MdocClassLoader(parent: ClassLoader) extends ClassLoader(null) {
```
Comment (tgodzik) [inline metals/src/main/scala/scala/meta/internal/worksheets/WorksheetClassLoader.scala]: Why do we need this classloader? It just loads mdoc, but aside from filtering doesn't do anything.

File: metals/src/main/scala/scala/meta/internal/worksheets/WorksheetProvider.scala [hunk 4]
```diff
@@ -210,185 +187,109 @@ class WorksheetProvider(
...
+        diagnostics.onPublishDiagnostics(
+          path,
+          worksheet.diagnostics().iterator().asScala.map(toLsp).toSeq,
+          isReset = true
+        )
+        worksheet
+          .statements()
+          .iterator()
+          .asScala
+          .map { s =>
```
Comment (tgodzik) [inline metals/src/main/scala/scala/meta/internal/worksheets/WorksheetProvider.scala]: `s` seems to get a bit lost in the code. Maybe at least `stmt` ? You can test rename on this :sweat_smile:

File: mtags/src/main/scala/scala/meta/internal/pc/CompilerJobQueue.scala [hunk 5]
```diff
@@ -26,39 +27,66 @@ import java.util.concurrent.CancellationException
...
-    )
-    singleThreadExecutor.setRejectedExecutionHandler((r, _) => {
-      r match {
-        case j: Job =>
-          j.reject()
-        case _ =>
-      }
+    new CompilerJobQueue(() => {
+      val singleThreadExecutor = new ThreadPoolExecutor(
+        1,
```
Comment (tgodzik) [inline mtags/src/main/scala/scala/meta/internal/pc/CompilerJobQueue.scala]: Could we use named params here? Or at least add /* name= */? The numbers are bit unclear what they mean.

File: metals/src/main/scala/scala/meta/internal/metals/Embedded.scala (hunk 1 above)
Comment (olafurpg) [reply metals/src/main/scala/scala/meta/internal/metals/Embedded.scala]: Done

File: metals/src/main/scala/scala/meta/internal/metals/Embedded.scala (hunk 2 above)
Comment (olafurpg) [reply metals/src/main/scala/scala/meta/internal/metals/Embedded.scala]: This is a reasonable fallback mechanism if the service loader doesn't work for some reason. This code was here before so I don't stir up things in this PR

File: metals/src/main/scala/scala/meta/internal/worksheets/WorksheetClassLoader.scala (hunk 3 above)
Comment (olafurpg) [reply metals/src/main/scala/scala/meta/internal/worksheets/WorksheetClassLoader.scala]: I updated the docstring to explain why this classloader is necessary, it isolates the mdoc classloader from the metals classloader so that we can call mdoc 2.11/2.13 from the metals 2.12 server.

File: mtags/src/main/scala/scala/meta/internal/pc/CompilerJobQueue.scala (hunk 5 above)
Comment (olafurpg) [reply mtags/src/main/scala/scala/meta/internal/pc/CompilerJobQueue.scala]: Done.

**Comment by olafurpg** [comment]
The CI is failing with the known test `tests.pc.MacroCompletionSuite.2.12.9-bm4`. @tgodzik Any chance we can merge this to unblock #1089 ?

**Comment by tgodzik** [comment]
> The CI is failing with the known test `tests.pc.MacroCompletionSuite.2.12.9-bm4`. @tgodzik Any chance we can merge this to unblock #1089 ?

I totally forgot about it, sorry! I think we can merge it! I will take a look at the failing test in the evening.
