### PR TITLE
Don't insert parentheses when importing

### LINKED ISSUE #1281: Import completions for methods should not insert parentheses
Seems to be related to #251, but in reverse.

Edit: oops, didn't notice that's the old completions.

**Describe the bug**

When importing a method with parameters, parentheses are inserted. That's illegal in Scala and shouldn't happen.

**To Reproduce**
1. Create an object with a method taking parameters
2. Import that object's method in another object
3. See the parens appear

Here's an example of a file exhibiting this:

```scala
package example

object demo {
  def method(a: Int) = a
}

object usage {
  import demo.m<tab>
}
```

**Expected behavior**
No parentheses are inserted in imports.

**Screenshots**

image

image

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: 0.7.6+720-7b699bd6-SNAPSHOT

**Search terms**
parentheses, suggestions, completions, imports, import

### PR DESCRIPTION
**Pull request by kubukoz**
Previously, if completions were used for importing a method that has parameters, its name would appear with parentheses. Now, the parentheses won't be inserted if the completion is requested in an import statement.

Will close #1281.

~Leaving this as a draft for now, as I wasn't able to make tests fail locally, hopefully I can confirm what's going on in CI.~

### CODE REVIEW

File: mtags/src/main/scala/scala/meta/internal/pc/CompletionProvider.scala [hunk 1]
```diff
@@ -39,44 +39,49 @@ class CompletionProvider(
       cursor = Some(params.offset),
       cursorName = cursorName
     )
+
     val pos = unit.position(params.offset)
     val isSnippet = isSnippetEnabled(pos, params.text())
-    val clientSupportsSnippets =
```
Comment (ckipp01) [inline mtags/src/main/scala/scala/meta/internal/pc/CompletionProvider.scala]: I believe this is needed a bit further down to get the correct suffixes?

Comment (kubukoz) [reply mtags/src/main/scala/scala/meta/internal/pc/CompletionProvider.scala]: We have access to it already from a val in a trait that's mixed in here (`Completions#clientSupportsSnippets`). I believe it's the same value...

File: mtags/src/main/scala/scala/meta/internal/pc/CompletionProvider.scala [hunk 2]
```diff
@@ -144,10 +149,11 @@ class CompletionProvider(
                 item.setAdditionalTextEdits(edits.asJava)
                 item.setTextEdit(textEdit(short + suffix))
             }
-          case _ =>
+          case _ if importPosition.isEmpty =>
```
Comment (kubukoz) [inline mtags/src/main/scala/scala/meta/internal/pc/CompletionProvider.scala]: I'm not entirely sure this is accurately coupled with "the current position is an import"... could there be any other case in which importPosition is empty?

File: mtags/src/main/scala/scala/meta/internal/pc/CompletionProvider.scala (hunk 1 above)
Comment (ckipp01) [reply mtags/src/main/scala/scala/meta/internal/pc/CompletionProvider.scala]: Ahh, I didn't notice that. Cool!

File: mtags/src/main/scala/scala/meta/internal/pc/CompletionProvider.scala (hunk 2 above)
Comment (olafurpg) [reply mtags/src/main/scala/scala/meta/internal/pc/CompletionProvider.scala]: Judging by the implementation of `autoImportPosition` it only returns `None` for import expressions, but there's nothing in the contract of that method which prevents this implementation detail from changing in the future. It would be better do something custom instead which implements exactly what we want for this purpose https://gist.github.com/olafurpg/d15833f9b519ac286e36a5daad8f07a5

Comment (kubukoz) [reply mtags/src/main/scala/scala/meta/internal/pc/CompletionProvider.scala]: I'll give this a try :)
